import type { DesignSystem } from '../types'

export const professionalDesigns: DesignSystem[] = [
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    category: 'Professional',
    tags: ['enterprise', 'trust', 'navy', 'b2b', 'saas'],
    description: 'Enterprise trust: navy, steel, and quiet confidence.',
    designPhilosophy:
      'The bank vault of design systems. Deep navy, steel greys, and a disciplined cobalt accent. Nothing surprises, nothing breaks, everything aligns. Built for enterprises whose customers equate boring with safe — and mean it as a compliment.',
    colors: {
      primary: '#1b2f8a',
      secondary: '#12284c',
      accent: '#0e7490',
      neutral: '#e2e8f0',
      background: '#ffffff',
      text: '#1e293b',
    },
    typography: {
      displayFont: 'Source Sans 3',
      bodyFont: 'Source Sans 3',
      scale: '13 / 15 / 17 / 20 / 26 / 34 / 48',
      lineHeights: 'Display 1.15, body 1.6',
      letterSpacing: 'Labels 0.06em uppercase, display -0.01em',
    },
    components: {
      primary: 'Solid #1b2f8a, white text, radius 4px, padding 12px 24px, 600',
      secondary: '1px #cbd5e1 border, white bg, navy text, same metrics',
      tertiary: 'Cobalt text link, underline on hover, external-link icons on new tabs',
      radius: '4px buttons/inputs, 8px cards',
      hover: '150ms darken; card borders → cobalt',
      cards: 'White, 1px #e2e8f0 border, 4px left accent bar, radius 8px, padding 24px',
      forms: 'Inputs 42px, 1px borders, labels above, cobalt focus ring 0 0 0 3px rgba(29,78,216,.25)',
      navigation: '72px navy top bar, white links, cobalt CTA button right',
      modals: 'Radius 8px, navy header band with white title, steel backdrop',
    },
    accent: '#1b2f8a',
    motif: 'big-stat-row',
    layout: 'split-hero',
    useCases: ['SaaS', 'Fintech', 'Real Estate'],
signatureCss: `
.dv-card { border-left: 4px solid #1b2f8a; }
.dv-stat { font-size: clamp(2.5rem, 6vw, 4rem); font-weight: 700; color: #12284c; }
.dv-nav { background: #12284c; }
.dv-nav a { color: #e2e8f0; }`,
    author: 'Jonas Keller',
    createdAt: '2026-01-18',
    popularity: 78,
  },
  {
    id: 'startup-serious',
    name: 'Startup Serious',
    category: 'Professional',
    tags: ['fintech', 'modern', 'crisp', 'growth', 'dark-accent'],
    description: 'Fintech crisp: near-black, electric blue, data-forward.',
    designPhilosophy:
      'Serious money, modern interface. Near-black surfaces, electric blue actions, and tabular numerals everywhere data appears. Stripe-style polish without Stripe-style ubiquity — dense, crisp, and fast.',
    colors: {
      primary: '#2563eb',
      secondary: '#0f172a',
      accent: '#10b981',
      neutral: '#eef2f6',
      background: '#ffffff',
      text: '#0f172a',
    },
    typography: {
      displayFont: 'Space Grotesk',
      bodyFont: 'Manrope',
      scale: '12 / 14 / 16 / 18 / 24 / 32 / 48',
      lineHeights: 'Display 1.1, body 1.6',
      letterSpacing: 'Display -0.02em, labels 0.04em',
    },
    components: {
      primary: 'Solid #2563eb, white text, radius 6px, padding 12px 24px, 600, border 1px #1d4ed8',
      secondary: 'White bg, 1px #cbd5e1 border, #0f172a text, same metrics',
      tertiary: 'Cobalt text link with subtle arrow-slide on hover',
      radius: '6px buttons, 12px cards',
      hover: '150ms border-color → #2563eb; no lifts, no shadows grow',
      cards: 'White, no border, shadow 0 1px 3px rgba(15,23,42,.08), radius 12px, padding 24px',
      forms: '1px border inputs with mono numerals where numeric, cobalt focus ring',
      navigation: '60px white bar, bottom 1px border, logo left, links right, cobalt CTA',
      modals: 'Radius 12px, 1px border + soft shadow, header 16px padding',
    },
    accent: '#2563eb',
    motif: 'big-stat-row',
    layout: 'dashboard',
    useCases: ['Fintech', 'SaaS', 'AI/ML'],
signatureCss: `
.dv-stat .value { font-variant-numeric: tabular-nums; font-weight: 700; }
.dv-stat .delta { color: #10b981; font-weight: 600; }
.dv-card { box-shadow: 0 1px 3px rgba(15,23,42,.08); }
.dv-btn { border: 1px solid #1d4ed8; }`,
    author: 'Priya Nair',
    createdAt: '2026-02-28',
    popularity: 82,
    trending: true,
  },
  {
    id: 'tech-corporate',
    name: 'Tech Corporate',
    category: 'Professional',
    tags: ['infrastructure', 'cloud', 'technical', 'grid', 'devops'],
    description: 'Infrastructure-grade: slate, cyan, engineering precision.',
    designPhilosophy:
      'For companies whose product is a datacenter. Slate greys, cloud cyan, IBM Plex Sans engineering sobriety, and grid-paper section backgrounds. Dense tables, precise diagrams, and copy that respects the reader’s IQ.',
    colors: {
      primary: '#0891b2',
      secondary: '#1e293b',
      accent: '#7c3aed',
      neutral: '#e2e8f0',
      background: '#f8fafc',
      text: '#0f172a',
    },
    typography: {
      displayFont: 'Familjen Grotesk',
      bodyFont: 'IBM Plex Sans',
      scale: '12 / 14 / 16 / 18 / 24 / 32 / 46',
      lineHeights: 'Display 1.15, body 1.6, mono 1.5',
      letterSpacing: 'Mono labels 0.08em uppercase, display -0.01em',
    },
    components: {
      primary: 'Solid #0891b2, white text, radius 3px, padding 12px 24px, 600',
      secondary: '1px #94a3b8 border, white bg, slate text',
      tertiary: 'Cyan text link with ↗ external arrow',
      radius: '3px buttons/inputs, 6px cards — engineering precision',
      hover: '150ms border→cyan; diagram nodes highlight',
      cards: 'White, 1px #e2e8f0, radius 6px, mono spec header row, padding 24px',
      forms: 'Mono-labeled inputs, 1px borders, cyan focus',
      navigation: '56px bar, bottom 1px border, mono breadcrumb, cyan active underline',
      modals: 'Radius 6px, slate header band, mono close [×]',
    },
    accent: '#0891b2',
    motif: 'mono-labels',
    layout: 'dashboard',
    useCases: ['AI/ML', 'SaaS', 'Crypto'],
signatureCss: `
.dv-spec { font-family: 'IBM Plex Mono', monospace; font-size: 12px; letter-spacing: .08em; text-transform: uppercase; color: #0891b2; }
.dv-stage { background-image: linear-gradient(rgba(30,41,59,.04) 1px, transparent 1px), linear-gradient(90deg, rgba(30,41,59,.04) 1px, transparent 1px); background-size: 24px 24px; }
.dv-card .spechead { font-family: 'IBM Plex Mono', monospace; font-size: 11px; color: #64748b; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; margin-bottom: 12px; }`,
    author: 'Jonas Keller',
    createdAt: '2026-03-28',
    popularity: 75,
  },
  {
    id: 'ledger-fintech',
    name: 'Ledger Fintech',
    category: 'Professional',
    tags: ['fintech', 'ledger', 'numbers', 'green'],
    description: 'Money software that shows its work — double-entry calm.',
    designPhilosophy:
      'Finance UI earns trust by exposing the math. Every figure is typographically exact, every action leaves a trail, and the ledger green reassures without decorating. The dashboard is a balance sheet that happens to be beautiful.',
    colors: {
      primary: '#0d7a5f',
      secondary: '#10201b',
      accent: '#d97706',
      neutral: '#dbe4e0',
      background: '#f4f6f5',
      text: '#12261f',
    },
    typography: {
      displayFont: 'IBM Plex Mono',
      bodyFont: 'Public Sans',
      scale: '12 / 14 / 16 / 19 / 24 / 32 / 52',
      lineHeights: 'Display 1.2, body 1.6',
      letterSpacing: 'Display -0.01em, figures 0.02em',
    },
    components: {
      primary:
        'Ledger-emerald #0d7a5f button, 6px radius, mint text, weight 600; hover deepens to #0a5f4a with a mono “✓ posting” microcopy swap',
      secondary: 'Statement button with 1px #c9d6d1 border and ink text; hover tints mint 6%',
      tertiary: 'Mono footnote link with a running-total index that underlines in emerald',
      radius: '6px controls, 10px statements — banker’s millwork',
      hover: 'Color and microcopy only, 140ms; numbers never move',
      cards: 'Statement panels: white, 10px radius, 1px #dbe4e0 rule, 24px padding, mono header row with a stamped date',
      forms: 'Amount fields: mono input right-aligned, 1px rule bottom, emerald focus; currency chip left-anchored',
      navigation: 'Left 230px statement rail: accounts grouped with mono balances; the active account carries an emerald margin bar',
      modals: 'Entry sheet: white panel with a double-rule top and mint scrim rgba(16,32,27,.45)',
    },
    accent: '#0d7a5f',
    motif: 'big-stat-row',
    layout: 'dashboard',
    useCases: ['Fintech', 'SaaS', 'Productivity'],
    signatureCss: `
.dv-card { border-radius: 10px; border: 1px solid #dbe4e0; background: #fff; }
.dv-btn { border-radius: 6px; font-variant-numeric: tabular-nums; }
.dv-kicker { font-family: "IBM Plex Mono", monospace; font-size: 11px; letter-spacing: .06em; text-transform: uppercase; }`,
    author: 'Priya Anand',
    createdAt: '2026-08-25',
    popularity: 83,
    trending: true,
  },
  {
    id: 'briefcase-slate',
    name: 'Briefcase Slate',
    category: 'Professional',
    tags: ['consulting', 'slate', 'b2b', 'sober'],
    description: 'Consulting-grade B2B: slate suits, hairline grids, zero fluff.',
    designPhilosophy:
      'The deck your most skeptical client approves. Slate surfaces, a hairline grid you could rule with a straightedge, and copy that respects the reader’s time. Confidence comes from restraint: no gradients, no gimmicks, just structure.',
    colors: {
      primary: '#33415c',
      secondary: '#1b2432',
      accent: '#b45f18',
      neutral: '#dfe3ea',
      background: '#f5f6f8',
      text: '#1f2733',
    },
    typography: {
      displayFont: 'Familjen Grotesk',
      bodyFont: 'Hanken Grotesk',
      scale: '12 / 14 / 16 / 19 / 24 / 32 / 54',
      lineHeights: 'Display 1.18, body 1.62',
      letterSpacing: 'Display -0.01em, labels 0.08em uppercase',
    },
    components: {
      primary:
        'Suit-slate #33415c button, 4px radius, paper text, weight 600; hover darkens one step with a 2px tan left edge',
      secondary: 'Dossier button with 1px #c7ced9 border; hover fills slate 6%',
      tertiary: 'Charcoal link with a tan dossier-tab underline on hover',
      radius: '4px controls, 6px dossiers — manila, not rounded',
      hover: 'One-step tone shifts and tab edges, 130ms',
      cards: 'Dossier pages: white with 1px #dfe3ea rule, 6px radius, a slate tab strip on top, 24px padding, mono exhibit numbers',
      forms: 'Filing fields: 1px bottom rules with mono input; focus re-inks the rule tan',
      navigation: 'Top agenda bar with numbered sections; the active item carries the tan tab',
      modals: 'Briefing sheet: white with a slate header band and slate scrim rgba(27,36,50,.5)',
    },
    accent: '#33415c',
    motif: 'swiss-grid',
    layout: 'split-hero',
    useCases: ['SaaS', 'Education', 'Productivity'],
    signatureCss: `
.dv-card { border-radius: 6px; border: 1px solid #dfe3ea; background: #fff; }
.dv-btn { border-radius: 4px; }
.dv-kicker { letter-spacing: .08em; text-transform: uppercase; font-size: 11px; color: #b45f18; }`,
    author: 'Jonas Whitfield',
    createdAt: '2026-08-08',
    popularity: 77,
  },
  {
    id: 'campus-lms',
    name: 'Campus LMS',
    category: 'Professional',
    tags: ['education', 'campus', 'plum', 'courses'],
    description: 'A learning platform with collegiate warmth — plum, gold, and progress.',
    designPhilosophy:
      'School spirit, software-grade. Plum banners, old-gold honors cords, and progress you can feel: streaks, credits, and checkmarks that celebrate without infantilizing. The dashboard is a hallway of open doors.',
    colors: {
      primary: '#7b2d5e',
      secondary: '#2c2136',
      accent: '#d9a441',
      neutral: '#e8dfcf',
      background: '#faf6ee',
      text: '#241b2e',
    },
    typography: {
      displayFont: 'Familjen Grotesk',
      bodyFont: 'Karla',
      scale: '13 / 15 / 17 / 20 / 25 / 33 / 56',
      lineHeights: 'Display 1.16, body 1.6',
      letterSpacing: 'Display 0, labels 0.06em uppercase',
    },
    components: {
      primary:
        'Plum #7b2d5e button, 8px radius, parchment text, weight 600; hover honors it with a gold top cord',
      secondary: 'Parchment button with 1px plum border; hover fills plum 6%',
      tertiary: 'Ivy link with a gold honor tick before it',
      radius: '8px controls, 12px doors — campus arches',
      hover: 'Cords and tints, 180ms; celebratory but composed',
      cards: 'Course doors: #fffdf7 panels, 12px radius, 4px plum lintel, 24px padding, gold cord + “Completed” ribbon on done',
      forms: 'Enrollment fields: 1px plum rules with gold focus; due dates chip in ivy',
      navigation: 'Left 220px hallway rail: course list with progress bars; the active door stands open (plum fill)',
      modals: 'Registrar sheet: parchment panel with a plum seal header and plum scrim rgba(44,33,54,.5)',
    },
    accent: '#7b2d5e',
    motif: 'numbered-steps',
    layout: 'dashboard',
    useCases: ['Education', 'SaaS', 'Nonprofit'],
    signatureCss: `
.dv-card { border-radius: 12px; background: #fffdf7; border-top: 4px solid #7b2d5e; }
.dv-btn { border-radius: 8px; }
.dv-card.done { border-top-color: #d9a441; }`,
    author: 'Thea Okonkwo',
    createdAt: '2026-08-01',
    popularity: 79,
  },
  {
    id: 'clinic-warm',
    name: 'Clinic Warm',
    category: 'Professional',
    tags: ['healthcare', 'bedside', 'rose', 'calm'],
    description: 'Healthcare with bedside manner — rose warmth, sage calm.',
    designPhilosophy:
      'Medicine is human. Rose warmth replaces clinical blue; sage green keeps vitals honest; every screen explains itself in plain language before asking anything. Consent and clarity are the design system.',
    colors: {
      primary: '#c65f72',
      secondary: '#4a3b3f',
      accent: '#7fa88b',
      neutral: '#f0e2dc',
      background: '#fdf8f5',
      text: '#38302e',
    },
    typography: {
      displayFont: 'Fraunces',
      bodyFont: 'Source Sans 3',
      scale: '13 / 15 / 17 / 21 / 26 / 34 / 56',
      lineHeights: 'Display 1.18, body 1.64',
      letterSpacing: 'Display 0, labels 0.05em',
    },
    components: {
      primary:
        'Rose #c65f72 button, 999px pill, warm text, weight 600; hover deepens to #b04d60 and holds a 4px sage halo',
      secondary: 'Paper pill with 1px rose border and umber text; hover tints rose 5%',
      tertiary: 'Sage plain-language link with a small “what this does” tooltip affordance',
      radius: '999px buttons, 14px sheets — soft as a waiting-room chair',
      hover: 'Warm halos and tint fills, 220ms ease-out',
      cards: 'Referral sheets: #fffdfc, 14px radius, 1px rgba(198,95,114,.35) rule, 26px padding, sage vitals chip row',
      forms: 'Intake fields: 1px rose rules with plain-language helper text beneath; focus rings sage',
      navigation: 'Top reception bar with pill links; the active desk carries a rose dot and label',
      modals: 'Consultation card: paper sheet with a rose header rule and umber scrim rgba(74,59,63,.45)',
    },
    accent: '#c65f72',
    motif: 'leaf-divider',
    layout: 'split-hero',
    useCases: ['Health', 'Nonprofit', 'Education'],
    signatureCss: `
.dv-card { border-radius: 14px; background: #fffdfc; border: 1px solid rgba(198,95,114,.35); }
.dv-btn { border-radius: 999px; }
.dv-hero h1 { font-weight: 500; }`,
    author: 'Amara Osei',
    createdAt: '2026-07-27',
    popularity: 78,
  },
  {
    id: 'terminal-ops',
    name: 'Terminal Ops',
    category: 'Professional',
    tags: ['devops', 'terminal', 'mono', 'oncall'],
    description: 'An on-call console for people who live in terminals — green prompt, amber alerts.',
    designPhilosophy:
      'Built for 3 a.m. The whole design is a terminal that respects operators: monospace everything, green confirmation, amber warnings, red incidents, and keyboard-first everything. No dashboard theater — state, logs, and actions.',
    colors: {
      primary: '#3fb950',
      secondary: '#161b22',
      accent: '#ff9f43',
      neutral: '#21262d',
      background: '#0d1117',
      text: '#e6edf3',
    },
    typography: {
      displayFont: 'Space Mono',
      bodyFont: 'IBM Plex Sans',
      scale: '12 / 13 / 15 / 18 / 24 / 30 / 46',
      lineHeights: 'Display 1.25, body 1.6',
      letterSpacing: 'Display 0, code 0',
    },
    components: {
      primary:
        'Prompt-green command button: dark fill, green text + border, 4px radius, mono, with a ⏎ kbd hint; hover inverts to green fill with console text',
      secondary: 'Panel command with 1px #21262d border; hover brightens the border to #30363d',
      tertiary: 'Mono flag-style link [--flag] that greens on hover',
      radius: '4px consoles, 6px panels — soft terminal corners',
      hover: 'Cursor blink (1.1s steps) on focused panels; instant border brightens',
      cards: 'Console windows: #161b22, 1px #21262d, 6px radius, mono title bar with a green ● status and 20px padding',
      forms: 'Prompt inputs: “$ ” prefix, mono text, green caret, amber focus border on warnings',
      navigation: 'Left 210px service tree in mono; the active service carries a green ● and bold row',
      modals: 'Incident modal: panel with an amber header bar, mono timestamps, rgba(1,4,9,.8) scrim',
    },
    accent: '#3fb950',
    motif: 'mono-labels',
    layout: 'dashboard',
    useCases: ['SaaS', 'Productivity', 'AI/ML'],
    signatureCss: `
.dv-card { background: #161b22; border: 1px solid #21262d; border-radius: 6px; }
.dv-btn { border-radius: 4px; font-family: "Space Mono", monospace; }
.dv-hero h1 { font-family: "Space Mono", monospace; }`,
    author: 'Viktor Lindgren',
    createdAt: '2026-08-18',
    popularity: 82,
  },
  {
    id: 'civic-trust',
    name: 'Civic Trust',
    category: 'Professional',
    tags: ['civic', 'government', 'limestone', 'olive'],
    description: 'Public-sector clarity: limestone, olive-bronze, and plain-language promise.',
    designPhilosophy:
      'A civic building, digitized: limestone permanence, bronze plaque accents, and signage written in plain language. The design promises accountability — every service shows its steps, its fees, and its office hours. Trust through legibility.',
    colors: {
      primary: '#556b2f',
      secondary: '#3c4429',
      accent: '#8a6d3b',
      neutral: '#e3e0d2',
      background: '#f6f4ec',
      text: '#2b2a24',
    },
    typography: {
      displayFont: 'Archivo',
      bodyFont: 'Source Sans 3',
      scale: '13 / 15 / 17 / 20 / 25 / 33 / 56',
      lineHeights: 'Display 1.16, body 1.62',
      letterSpacing: 'Display 0.02em, signage 0.1em uppercase',
    },
    components: {
      primary:
        'Civic-olive #556b2f counter button, 2px radius, limestone text, weight 700; hover raises a bronze plaque underline',
      secondary: 'Limestone button with 1px olive border; hover fills olive 8%',
      tertiary: 'Bronze plaque link — small-caps with a dotted rule beneath',
      radius: '2px controls, 4px counters — stonemason tolerances',
      hover: 'Plaques raise and tints fill, 160ms; government steady',
      cards: 'Service counters: #fbfaf3, 4px radius, 2px olive lintel, 26px padding, bronze step numbers in outline circles',
      forms: 'Application fields: 1px olive rules with plain-language help text; focus inks the rule bronze',
      navigation: 'Department bar: limestone with uppercase signage links; the active department carries the bronze plaque dot',
      modals: 'Public notice sheet: limestone with a double olive rule header and ink scrim rgba(43,42,36,.5)',
    },
    accent: '#556b2f',
    motif: 'editorial-columns',
    layout: 'dashboard',
    useCases: ['Nonprofit', 'Education', 'SaaS'],
    signatureCss: `
.dv-card { border-radius: 4px; background: #fbfaf3; border-top: 2px solid #556b2f; }
.dv-btn { border-radius: 2px; }
.dv-kicker { letter-spacing: .1em; text-transform: uppercase; color: #8a6d3b; font-size: 11px; }`,
    author: 'Miriam Adler',
    createdAt: '2026-07-23',
    popularity: 74,
  },
]