import type { DesignSystem } from '../types'
import { row } from './build'

/**
 * Wave 19 — Instruments and Hands: the trades that listen, measure, or shape
 * with a tool that has a voice of its own.
 * Row format: id, name, category, tags, useCases, hero, description,
 * philosophy, colors, display, body, motif, layout, radius, depth,
 * accentRole, author.
 */

export const wave19Designs: DesignSystem[] = [
  row("'piano-tuner'-w19", 'Piano Tuner', 'Professional', 'piano tuning tuning forks dissonance aural', 'Professional Services|Education|Music', 'Listen, then *move the pin.*', 'A room full of strings and one small wrench.', 'A piano is a conversation between felt and steel: pin set, stretch measured, and an octave that has to sit under a hand even when nobody is playing. The design is quiet and warm — single notes, beat rates, and one amber dot for a string still speaking out of tune.', '#6b4f2a #9a8c6a #c99a2a #dcd0b8 #f4f0e6 #151108', 'Marcellus', 'Manrope', 'tape-labels', 'field-notes', 4, 'soft', 'dotting the string still out', 'Roland Devereux'),
  row("'violin-restorer'-w19", 'Violin Restorer', 'Luxury', 'violins varnish repair arches soundpost', 'Art Gallery|Fashion|E-commerce', 'Lift the top, *read the soul.*', 'An instrument that has survived three owners.', 'Violin repair is listening under the varnish: a bridge reset, a soundpost adjusted by a millimetre, and a crack glued from the inside where nobody will see. The page is amber and grain — arch profiles, label dates, and one gilt line for a seam left visible on purpose.', '#7a3a2a #9c7a4a #c99a3a #d4c0a8 #f2ece0 #180e08', 'Cormorant Garamond', 'Literata', 'quilt-patch', 'editorial', 6, 'soft', 'gilding the seam left visible', 'Marguerite Chastain'),
  row("'reed-maker'-w19", 'Reed Maker', 'Professional', 'reeds scraping cane shaping cane scraping knives', 'Music|Education|E-commerce', 'Scrape, *test, rest.*', 'A knife and a piece of cane in a quiet room.', 'A reed is a blade and a breath: cane split, scraped to a thickness map, and tested against a mouth that already knows the tune. The design is warm and brittle — cane grades, scrape profiles, and one amber tag for a reed that came back flat.', '#8a5a2a #b08a4a #c99a2a #d8c8a8 #f4efe0 #1a1208', 'Fraunces', 'Literata', 'torn-edge', 'bento', 8, 'hairline', 'tagging the reed that came back flat', 'Hana Fujimoto'),
  row("'voice-coach'-w19", 'Voice Coach', 'Creative', 'voice lessons breath support pitch diction', 'Education|Wellness|Music', 'Find the note *before the words.*', 'A room, a mirror, and a lot of silence between notes.', 'Voice work is trust placed in a room: breath counted, pitch matched, and a sentence shaped so the consonants do not fight the vowel. The page is studio light — scale charts, recording notes, and one violet marker for a phrase still catching.', '#7a4a8a #a894b2 #2a7a9a #d4c9d6 #f2eef6 #16101c', 'Bungee Shade', 'Figtree', 'duotone-media', 'split-hero', 10, 'soft', 'marking the phrase still catching', 'Sunny Marchetti'),
  row("'prosthetist'-w19", 'Prosthetist', 'Professional', 'prosthetics sockets casting gait alignment', 'Health|Clinic|Manufacturing', 'Fit by *millimetre, then walk.*', 'A socket that has to become part of a body.', 'Prosthetic fitting is a promise made in plaster: a cast taken, a socket relieved where it will rub, and a gait educated one stride at a time. The design is clean and clinical — cast notes, alignment marks, and one amber line for an edge still to trim.', '#2a3a5a #9aa6b0 #c99a2a #d4d2c8 #f2f4f0 #0e141c', 'Chakra Petch', 'Source Sans 3', 'blueprint-grid', 'docs', 2, 'flat', 'lining the edge still to trim', 'Marek Dolny'),
  row("'orthotist'-w19", 'Orthotist', 'Professional', 'braces supports alignment arthritis posture', 'Health|Clinic|Education', 'Brace the joint, *free the stride.*', 'A support that has to feel like nothing.', 'An orthosis is a frame around a living joint: measured, padded, and adjusted until it disappears into a step. The page is steady and instructive — range notes, adjustment logs, and one teal tag for a setting still to settle.', '#3a5a6a #9aa6a8 #2a7a4a #d0d8d2 #f2f6f4 #10181c', 'IBM Plex Mono', 'Manrope', 'numbered-steps', 'centered', 6, 'flat', 'tagging the setting still settling', 'Dr. Andrea Sun'),
  row("'glass-blower'-w19", 'Glass Blower', 'Luxury', 'glass blowing furnace anneal punty colour', 'Art Gallery|E-commerce|Wedding', 'Heat, *then catch it.*', 'A pipe, a furnace, and a shape held in the hand.', 'Glassblowing is timing inside a furnace: gather, inflate, and shape with a breath and a tool while the glass is molten and unforgiving. The design is hot and molten — temperature notes, colour batches, and one amber ring for a piece still to anneal.', '#c93a2a #d47a3a #2a1a3a #d4d0c8 #f4ede4 #1a1210', 'Anton', 'Literata', 'oil-slick', 'spotlight', 14, 'glow', 'ringing the piece still to anneal', 'Imogen Blake'),
  row("'lamp-worker'-w19", 'Lamp Worker', 'Creative', 'lampworking borosilicate glass rods torches beads', 'Art Gallery|E-commerce|Education', 'Fuse, *pull, shape.*', 'A torch small enough to sit on a bench.', 'Lampworking is glass drawn small enough to fit a room: rod melted to a gather, pulled to a stem, and shaped by a hand that already knows the feel of hot silica. The page is amber and studious — colour mixes, pull lengths, and one gold dot for a bead still in the kiln.', '#d46a1a #c98a2a #1a3a6a #d4c8b8 #f4efe0 #1a100c', 'Bebas Neue', 'Space Grotesk', 'tape-labels', 'bento', 4, 'soft', 'dotting the bead still in the kiln', 'Bea Solano'),
  row("'silversmith'-w19", 'Silversmith', 'Luxury', 'silver forging raising planishing hallmarks', 'Fashion|E-commerce|Art Gallery', 'Raise it *from inside.*', 'A sheet of silver, a hammer, and an inside form.', 'Raising silver is a conversation of force and patience: sheet annealed, folded onto an iron stake, and planished until the inside curve reads as born rather than made. The design is bright and quiet — gauge notes, hammer marks, and one gilt stripe for a piece awaiting hallmark.', '#8a8a9a #b8b6c0 #c99a2a #dcd8d0 #f2f0ec #141418', 'Cinzel', 'Hanken Grotesk', 'rivet-row', 'editorial', 6, 'flat', 'striping the piece awaiting hallmark', 'Siobhán Walsh'),
  row("'wheel-thrower'-w19", 'Wheel Thrower', 'Organic', 'pottery wheel clay centering glaze kiln', 'Art Gallery|Education|Wellness', 'Centre, *then open.*', 'A wheel that answers the weight of a hand.', 'Centring clay is the first argument: a lump pressed to the wheel head, opened under a palm, and pulled up until the walls remember the pressure that made them. The page is mud and patience — clay bodies, firing notes, and one terracotta tag for a pot that ran left.', '#8a5a2a #b08a5a #3a6a4a #d4c8a8 #f4efe2 #1a140e', 'Caveat', 'Mulish', 'leaf-divider', 'field-notes', 8, 'soft', 'tagging the pot that ran left', 'Aurélie Fontaine'),
  row("'calligrapher'-w19", 'Calligrapher', 'Creative', 'calligraphy ink nibs broad-edge copperplate scripts', 'Education|E-commerce|Wedding', 'Write slow *to make it legible.*', 'A nib, an inkwell, and a line that becomes a shape.', 'Calligraphy is motion slowed down enough to read: a pen angled, a stroke weighted by pressure, and a letter that lives in the space between hand and breath. The design is ink-dark and poised — script samples, nib sizes, and one amber line for a word still to be reflowed.', '#1a1410 #3a322a #c99a2a #c8c0a8 #f2efe0 #100c08', 'Playfair Display', 'Marcellus', 'swiss-grid', 'editorial', 4, 'hairline', 'lining the word still to reflow', 'Poppy Lang'),
  row("'book-binder'-w19", 'Book Binder', 'Creative', 'bookbinding sewing signatures leather headbands', 'Bookstore|E-commerce|Education', 'Fold, sew, *then case in.*', 'A book that is stitched, not perfect-bound.', 'Bookbinding is assembly you can feel: signatures folded, sewn on tapes, and cased in cloth that has to lie flat on the spine. The page is library-tonal — paper stocks, thread colours, and one mustard tag for a signature still loose.', '#6a4a2a #8a6a3a #3a4a5a #c8c0b0 #f0ece0 #120e0a', 'EB Garamond', 'Source Sans 3', 'torn-edge', 'bento', 6, 'hairline', 'tagging the loose signature', 'Bea Solano'),
  row("'parchment-cutter'-w19", 'Parchment Cutter', 'Professional', 'parchment vellum trimming knives bone folders', 'Bookstore|Education|E-commerce', 'Cut *with the grain, not against.*', 'A knife guided by a bone folder and a feel for hair.', 'Parchment cutting is a discipline of direction: scored along the grain, sliced with the hair line, and trimmed so the edge does not fray under its own weight. The design is pale and precise — sheet sizes, grain notes, and one amber mark for a sheet still to be skived.', '#d4c8a8 #b8a88a #4a3a2a #d8d4c4 #f4f0e6 #1a1410', 'IBM Plex Mono', 'Literata', 'double-rule', 'centered', 2, 'flat', 'marking the sheet still to skive', 'Junko Arai'),
  row("'leather-corsetier'-w19", 'Corsetier', 'Luxury', 'corsetry leather boning eyelets lacing', 'Fashion|E-commerce|Wedding', 'Lace up *and measure again.*', 'A garment held by bone and lace.', 'Corsetry is structure with a waistline: a pattern cut to a body, boning set into channels, and lacing tightened until the silhouette holds without fighting the skin. The page is intimate and structured — boning counts, eyelet pitches, and one blush tag for a fit still to settle.', '#7a3a4a #a87a8a #c99a2a #d8c8c0 #f2ece8 #181012', 'Marcellus', 'Outfit', 'dashed-borders', 'split-hero', 8, 'soft', 'tagging the fit still settling', 'Imogen Blake'),
  row("'screen-printer'-w19", 'Screen Printer', 'Creative', 'screen printing mesh emulsion squeegee registration', 'E-commerce|Art Gallery|Apparel', 'Burn the mesh, *pull the print.*', 'A screen, a squeegee, and a registration pin.', 'Screen printing is colour through a veil: mesh burned to an image, ink flooded, and a pull that has to land on the same point every time. The design is flat and graphic — colour breaks, mesh counts, and one magenta line for a print still off-register.', '#c93a4a #d47a4a #1a3a4a #d4c8b8 #f4efe0 #1a1014', 'Archivo Black', 'Space Grotesk', 'halftone-dots', 'split-hero', 10, 'flat', 'lining the print still off', 'Charlie Ngata'),
  row("'block-printer'-w19", 'Block Printer', 'Retro', 'block printing carving chisels mallets ink', 'E-commerce|Grocery|Art Gallery', 'Carve, inkwash, *press.*', 'A block of fruitwood and a mallet that remembers its swing.', 'Block printing is image and pressure: the block carved against the grain, inked with a dab rather than a flood, and pressed by hand or foot until the cloth takes an impression worth keeping. The page is warm and process-heavy — carving notes, ink mixes, and one amber stamp on a block still to be cleaned.', '#8a4a2a #b07a3a #3a5a2a #d4c0a8 #f2ece0 #1a120e', 'Bitter', 'Mulish', 'torn-edge', 'split-scroll', 12, 'soft', 'stamping the block still to clean', 'Frank Delaney'),
  row("'letterpress-operator'-w19", 'Letterpress Operator', 'Retro', 'letterpress type lockup ink impression platen', 'E-commerce|Bookstore|Art Gallery', 'Set, lock, *ink, pull.*', 'A press that asks for even pressure and patient inking.', 'Letterpress is relief made physical: type set and proofed loose, a forme locked on the press, and an impression so clean the paper remembers where it was kissed. The design is deep and mechanical — type sizes, ink tack notes, and one copper line for a forme still to be beveled.', '#2a2a2a #4a4a3a #c99a2a #d4c8a8 #f4efe0 #101010', 'Courier Prime', 'Source Sans 3', 'rivet-row', 'editorial', 2, 'flat', 'lining the forme still to bevel', 'Dee Ramírez'),
  row("'engraver'-w19", 'Engraver', 'Professional', 'engraving burins metal lines depth cuts', 'Manufacturing|Art Gallery|E-commerce', 'Cut one line *deep enough.*', 'A burin held at an angle only by feel.', 'Engraving is line drawn at a depth: a burin pushed through metal, a line widened by a second pass, and a cut that holds its edge under a loupe. The page is dark and precise — line styles, burin numbers, and one silver stroke for a pass still to be burnished.', '#1a1a1a #3a3a3a #c99a2a #c8c8c0 #f2f0ec #101010', 'Space Mono', 'Inter', 'pcb-trace', 'centered', 2, 'flat', 'stroking the pass still to burnish', 'Gethin Price'),
  row("'seal-engraver'-w19", 'Seal Engraver', 'Luxury', 'seals signets wax emblems wax sticks', 'E-commerce|Wedding|Art Gallery', 'Press the emblem, *read the wax.*', 'A seal that says the same thing every time.', 'Seal engraving is a miniature portrait in negative: a face carved smooth where it should be white, and a wax impression that reads clearly only when pressed clean. The design is gilt and waiting — emblem descriptions, wax colours, and one amber dot for a seal still to be warmed.', '#5a4a2a #c99a2a #1a1a1a #d4c8a8 #f4efe0 #1a1410', 'Cinzel', 'Marcellus', 'quilt-patch', 'spotlight', 6, 'soft', 'dotting the seal still to warm', 'Marguerite Chastain'),
  row("'bench-chemist'-w19", 'Bench Chemist', 'Professional', 'chemistry titrations reagents glassware pH', 'Health|Education|Manufacturing', 'Titrate to *the first true colour.*', 'A bench where precision is measured in drops.', 'Bench chemistry is counting to the end: reagents measured, a titre read at the first stable colour, and a record that must survive a later audit. The design is clean and exact — concentration notes, glassware sizes, and one amber band for a titre still to be confirmed.', '#2a3a5a #8a9a8a #c99a2a #d4d0c0 #f2f0e6 #0e1820', 'Chakra Petch', 'Source Sans 3', 'blueprint-grid', 'docs', 2, 'flat', 'banding the titre still to confirm', 'Dr. Andrea Sun'),
  row("'blood-typist'-w19", 'Blood Typist', 'Minimalism', 'blood typing serology cards agglutination', 'Health|Clinic|Education', 'One drop, *four answers.*', 'A card that turns colour for everybody who is watching.', 'Blood typing is a small drama with four endings: serum added, card read, and an answer written before the next patient waits. The design is clinical and closed-up — sample IDs, reaction reads, and one red marker on a result still to be double-checked.', '#b83a2a #a08a7a #2a3a5a #d8d4c8 #f2f0ec #1a1010', 'Quicksand', 'Inter', 'watermark-glyph', 'centered', 4, 'hairline', 'marking the result still to recheck', 'Priya Balan'),
  row("'microscopist'-w19", 'Microscopist', 'Professional', 'microscopy slides stains objectives samples', 'Health|Education|Research', 'Focus, *then trust the eye.*', 'A lens, a slide, and a world too small to name at first.', 'Microscopy is scale turned inside out: a slide mounted, a stain set, and an image resolved one objective at a time until the thing shows itself. The page is cool and investigative — stain recipes, objective notes, and one blue tag for a sample still to be restained.', '#3a5a6a #6a8a8a #c99a2a #d0d4c8 #f2f4ec #0e181c', 'Sora', 'IBM Plex Sans', 'scanlines', 'split-scroll', 6, 'hairline', 'tagging the sample still to restain', 'Siobhán Walsh'),
  row("'microbiologist'-w19", 'Microbiologist', 'Professional', 'microbiology cultures plates incubators counts', 'Health|Education|Energy', 'Grow, *count, record.*', 'A plate that tells you what was there.', 'Microbiology is patience with numbers: a plate swabbed, a culture grown, and a count taken before the colony grows into its neighbours. The design is clinical and methodical — plate IDs, colony counts, and one amber square for a plate still incubating.', '#3a4a2a #7a8a5a #c99a2a #d4d0b8 #f2f0e2 #101812', 'IBM Plex Mono', 'Mulish', 'halftone-dots', 'dashboard', 4, 'flat', 'squaring the plate still incubating', 'Marta Keskküla'),
  row("'pendulum-clock-make'-w19", 'Clockmaker', 'Retro', 'clocks escapement pendulums gearing springs', 'Manufacturing|E-commerce|Crafts', 'Regulate the *beat, not the hour.*', 'A clock that is heard before it is read.', 'A clock is a trained rhythm: escapement set, pendulum length measured, and beat adjusted until the ticks sit evenly across every silent hour. The design is brass and rhythm — gear notes, pendulum lengths, and one amber tick on a beat still to be eased.', '#8a6a2a #b08a4a #1a3a3a #d4c8a8 #f2efe0 #1a1410', 'VT323', 'Space Grotesk', 'tape-labels', 'timeline', 6, 'flat', 'ticking the beat still to ease', 'Marcy Kane'),
  row("'watch-repairer'-w19", 'Watch Repairer', 'Luxury', 'watches movements jewels mainsprings regulation', 'E-commerce|Fashion|Manufacturing', 'Open the case, *listen to the beat.*', 'A movement that lives on a pegwood and a loupe.', 'Watch repair is a world you enter sideways: a case opened, a movement cleaned, and a regulation set so the time keeps to the hand that set it. The design is precise and small — hairspring notes, jewel counts, and one gold dot for a time still to settle.', '#2a2a3a #5a5a6a #c99a2a #d4d0c8 #f2f0ec #101018', 'IBM Plex Mono', 'Literata', 'isometric-lattice', 'editorial', 2, 'hairline', 'dotting the time still to settle', 'Imogen Blake'),
  row("'photomicrographer'-w19", 'Photomicrographer', 'Creative', 'microscopy photography lighting focus stacking', 'Research|Art Gallery|Education', 'Stack, *then choose the plane.*', 'A camera that sees what the eye cannot hold.', 'Photomicrography is focus as a canvas: a series of slices stacked into one plane, and a final image chosen from the place where the subject comes clear. The design is deep and scrupulous — stack counts, exposure notes, and one violet marker for a plane still to be chosen.', '#2a3a5a #5a6a8a #c99a2a #d4d0d0 #f2f2ec #0e1018', 'Chakra Petch', 'Outfit', 'moire-rings', 'split-hero', 8, 'soft', 'marking the plane still to choose', 'Nostalgia Engine'),
  row("'tuning-fork-maker'-w19", 'Tuning Fork Maker', 'Professional', 'tuning forks steel filing pitch calibration', 'Manufacturing|Education|Music', 'File to pitch, *then listen.*', 'A fork that holds one note for a lifetime.', 'Tuning fork making is subtraction to a frequency: steel filed, tested on a fork, and adjusted until the note speaks clean and stays there under the hand. The design is exact and metallic — frequency notes, filing records, and one amber line for a fork still to be relieved.', '#6a6a6a #9a9a8a #c99a2a #dcd8c8 #f4f0e6 #141410', 'IBM Plex Mono', 'Hanken Grotesk', 'double-rule', 'centered', 2, 'flat', 'lining the fork still to relieve', 'Billy Hart'),
  row("'saddle-fitter'-w19", 'Saddle Fitter', 'Professional', 'saddlery fitting leather panels flocking pressure', 'E-commerce|Sports|Agriculture', 'Fit the panel, *not the saddle.*', 'A saddle that has to disappear under a horse.', 'Saddle fitting is pressure onto a back: panel shaved, flocking topped up, and a fit found by watching a horse move rather than by eye alone. The design is honest and close-up — panel measurements, pressure notes, and one amber strip on a pressure point still to relieve.', '#6a4a2a #8a6a3a #3a4a5a #d4c8b0 #f2ece0 #120e08', 'Bitter', 'Literata', 'torn-edge', 'bento', 8, 'hairline', 'striping the pressure point still to relieve', 'Siobhán Walsh'),
  row("'farrier'-w19", 'Farrier', 'Professional', 'farriery horses hooves trimming shoes forge', 'Agriculture|Sports|Community', 'Trim the hoof, *then shoe the stride.*', 'A forge and a horse that will not stand still.', 'Farriery is timing with iron: hoof trimmed, shoe shaped hot, and a fit nailed before the foot has a chance to shift. The page is forge-warm — hoof records, shoe shapes, and one ember-red mark for a shoe still to be reset.', '#8a3a1a #b06a2a #2a3a1a #d4c0a0 #f2ece0 #1a100c', 'Anton', 'Courier Prime', 'rivet-row', 'field-notes', 6, 'hard', 'marking the shoe still to reset', 'Owen Pryce'),
  row("'saddler'-w19", 'Saddler', 'Luxury', 'saddlery leather stitching harnesses rigging', 'E-commerce|Fashion|Sports', 'Stitch the line, *then pull the seam.*', 'A harness held together by thread and intent.', 'Saddlery is leather working with a purpose: a strap cut to a length that must not ease, a seam stitched tight, and a fit that has to hold under a pull. The design is rich and functional — leather grades, stitch counts, and one gilt line for a seam still to be struck.', '#5a3a1a #8a5a2a #c99a2a #d4c8a8 #f2ece0 #1a100c', 'Marcellus', 'Hanken Grotesk', 'dashed-borders', 'split-hero', 6, 'soft', 'gilding the seam still to strike', 'Marguerite Chastain'),
  row("'equine-vet'-w19", 'Equine Vet', 'Professional', 'equine veterinary lameness nerve blocks', 'Health|Clinic|Sports', 'Watch the gait, *then name it.*', 'A diagnosis made in a field and a gait.', 'Equine veterinary work is diagnosis made by watching: a horse jogged, a nerve blocked, and a lameness named before the day runs out. The design is clean and decisive — exam notes, block results, and one amber marker for a gait still to be re-examined.', '#3a5a4a #7a9a8a #c99a2a #d4d0b8 #f2f0e2 #101814', 'Chakra Petch', 'Manrope', 'numbered-steps', 'field-notes', 4, 'flat', 'marking the gait still to reexamine', 'Dr. Andrea Sun'),
  row("'apothecary'-w19", 'Apothecary', 'Professional', 'apothecary tinctures jars herbs compounding', 'Health|Grocery|E-commerce', 'Compound by *the dram, not the scoop.*', 'A shop of jars, scales, and paper labels.', 'An apothecary is remedy assembled to order: a tincture measured, a jar labelled in ink, and a compound that must keep its shape on the shelf. The page is apothecary-tonal — formula notes, jar sizes, and one amber tag for a tincture still to be bottled.', '#7a5a2a #a88a4a #3a4a2a #d4c8a8 #f2efe0 #1a120e', 'Fraunces', 'Source Sans 3', 'torn-edge', 'catalog', 6, 'hairline', 'tagging the tincture still to bottle', 'Aurélie Fontaine'),
  row("'herbalist'-w19", 'Herbalist', 'Organic', 'herbalism herbs tinctures teas remedies', 'Health|Grocery|Wellness', 'Pick, *dry, remember.*', 'A herb that works because it was gathered in its season.', 'Herbalism is remedy remembered in season: a herb picked dry, stored by colour and scent, and used in a way that respects the plant as much as the patient. The design is herbal and soft — harvest notes, drying times, and one green tag for a herb still to be identified.', '#3a6a3a #7a9a5a #c99a2a #d4d0a8 #f2f0e0 #101810', 'Young Serif', 'Figtree', 'leaf-divider', 'split-hero', 10, 'soft', 'tagging the herb still to identify', 'Siobhán Walsh'),
  row("'perfumer'-w19", 'Perfumer', 'Luxury', 'perfumery accords notes absolutes compounds', 'E-commerce|Grocery|Wedding', 'Build the scent *one accord at a time.*', 'A still room and a nose that remembers everything.', 'Perfumery is memory turned into liquid: an accord chosen, a base weighed, and a compound that has to age before it is the thing you meant. The design is glass and air — note pyramids, batch numbers, and one amber dot for a scent still to be rested.', '#6a3a4a #9a6a5a #3a4a6a #d4c8c0 #f2efe8 #181014', 'Bodoni Moda', 'Literata', 'oil-slick', 'spotlight', 12, 'soft', 'dotting the scent still to rest', 'Bea Solano'),
  row("'incense-maker'-w19", 'Incense Maker', 'Creative', 'incense blends sticks cones binders agarwood', 'E-commerce|Wellness|Grocery', 'Blend, *bind, then wait.*', 'A room full of resin and a prayer of smoke.', 'Incense making is dry things coaxed to burn as one: resin ground, a binder cut in, and a stick rolled until it holds its shape and its smoke. The page is warm and fragrant — blend notes, cure times, and one amber line for a stick still to be dried.', '#7a4a2a #9a6a3a #3a2a1a #d4c0a0 #f2ece0 #1a1210', 'Caveat', 'Mulish', 'torn-edge', 'split-scroll', 8, 'soft', 'lining the stick still to dry', 'Frank Delaney'),
]

// __W19__
