import type { DesignSystem } from '../types'
import { row } from './build'

/**
 * Wave 14 — Night Shift: the city that works while you sleep.
 * Row format: id, name, category, tags, useCases, hero, description,
 * philosophy, colors, display, body, motif, layout, radius, depth,
 * accentRole, author.
 */

export const wave14Designs: DesignSystem[] = [
  row('night-bakery', 'Night Bakery', 'Organic', 'bread ovens yeast proof flour', 'Restaurant|Grocery|Manufacturing', 'The ovens are *already on.*', 'A bakery whose day starts at two in the morning.', 'Night baking is a schedule measured in dough: the proof is either ready or it is not, and the ovens do not negotiate. This system keeps the timetable warm — flour-dusted neutrals, one amber for whatever is ready, and numbers written where the bench can actually see them.', '#b38019 #d9b382 #f59e0b #f0e2cf #fffaf1 #2a1c10', 'Merriweather', 'Rubik', 'quilt-patch', 'catalog', 8, 'soft', 'batches ready to come out', 'Nadia Ferraro'),
  row('fish-auction', 'Fish Auction', 'Professional', 'auction harbour crates ice bids', 'Marketplace|Logistics|Restaurant', 'The floor clears *by six.*', 'A dawn auction run on a Dutch clock.', 'A fish auction is price discovery with ice involved: the clock starts high and falls until someone bids, so every second is money. The interface stays out of the way — one ticker, one lot number, one ring for the last call.', '#2e56c7 #9fb8c4 #ff6b5e #dbe6ec #f4f9fc #0b1f2a', 'IBM Plex Sans', 'Oxanium', 'ticker-marquee', 'dashboard', 2, 'flat', 'lots below reserve, one row each', 'Tomas Reyes'),
  row('press-room', 'Press Room', 'Creative', 'newspaper press ink plates edition', 'Publishing|News|Design Tools', 'Ink dries *before the news does.*', 'A nightly print run, counted in copies.', 'A press room is a deadline made physical: plates are burned, the run starts, and a stopped press costs more per minute than any redesign. The system is newsprint and packing tape — halftones, one press red, and rules that hold at speed.', '#212763 #8f8f8f #a4161a #ded9cf #f6f4ee #121112', 'Source Sans 3', 'Courier Prime', 'halftone-dots', 'magazine', 0, 'hairline', 'runs past deadline, one plate each', 'Colin Bhaskar'),
  row('steam-laundry', 'Steam Laundry', 'Professional', 'linen press steam folds hotel', 'Hotel|Health|Wedding', 'Everything comes out *warm.*', 'Commercial laundry for hotels and hospitals.', 'Industrial laundry is throughput you can touch: weights in, folds out, and a press that never quite cools down. The design leans clean — steam whites, one hot accent for what is still damp, and labels stitched rather than stuck.', '#0698f9 #9dc3da #f4845f #cfe0ea #eef6fb #0a1c28', 'Livvic', 'Raleway', 'glass-sheen', 'centered', 6, 'soft', 'loads still in the dryer, one per drum', 'Ada Nkemelu'),
  row('nightline-desk', 'Nightline Desk', 'Professional', 'hotline overnight crisis listening', 'Mental Health|Nonprofit|Health', 'Someone is *awake.*', 'An overnight support line that never rings out.', 'A nightline is calm engineered as a procedure: greet, listen, log, escalate, and never leave a caller in silence. Type stays large and quiet, and the only loud colour is reserved for the moment a call needs a second listener.', '#0f0f57 #8b9dc3 #f2b705 #dde4f0 #f5f8fd #12192b', 'Sora', 'Familjen Grotesk', 'scanlines', 'poster', 4, 'hairline', 'calls waiting for a second listener', 'Ravi Chandran'),
  row('depot-yard', 'Depot Yard', 'Brutalism', 'buses depot bays fuelling shifts', 'Logistics|Government|Travel', 'Buses sleep *in rows.*', 'A bus depot that is loudest at 4am.', 'A depot yard is a diagram of the morning: bays numbered, fuelling queues ordered, and drivers collecting keys in a windowless room. The design is a yard map first — hard labels, painted-line arrows, and status read at a glance from across the apron.', '#946a1f #4b5563 #22d3ee #e5e7eb #f6f7f9 #1b1b1f', 'Unbounded', 'Hanken Grotesk', 'tape-labels', 'timeline', 2, 'hard', 'bays blocked, one board each', 'Marek Dolny'),
  row('street-sweeper', 'Street Sweeper', 'Brutalism', 'municipal sweeping routes grit bins', 'Government|Community|Logistics', 'The street is *washed by eight.*', 'Municipal cleaning, routed before the traffic.', 'Sweeping is a promise about a time of day: the machine cannot work once the street fills, so the route is planned backwards from rush hour. The design is high-visibility and municipal — route numbers, grit bins, and a map that admits which streets were skipped.', '#54a028 #b9c4a8 #eab308 #e2e7dc #f6f8f2 #1f2a1c', 'Bebas Neue', 'Red Hat Display', 'diagonal-bars', 'full-bleed', 0, 'flat', 'streets skipped, one route at a time', 'Elsie Fairweather'),
  row('overnight-radio', 'Overnight Radio', 'Retro', 'radio night callers requests dial', 'Music|Podcast|Community', 'The frequency *never sleeps.*', 'Talk radio for the small hours.', 'Overnight radio is made by its callers: a host, a request line, and a town’s worth of insomniacs keeping each other company. The dial glows a little, the type is generous, and the schedule is honest about how few people are listening.', '#562d1b #c9a27a #f0a500 #ecdfd0 #fdf6ec #2b1d12', 'Hi Melody', 'Courier Prime', 'moire-rings', 'split-scroll', 999, 'glow', 'requests held over, one card each', 'Junko Arai'),
  row('sleep-lab', 'Sleep Lab', 'Professional', 'sleep study polysomnography nights', 'Health|Clinic|Data & Analytics', 'Sleep is *the measurement.*', 'Overnight studies read in the morning.', 'A sleep lab watches what the body does when nobody is watching: leads placed, lights out, and a night of signals reduced to events. The design is deliberately drowsy — low contrast on purpose, no pure white, and charts that read left to right like a night.', '#724096 #9c93bd #8b5cf6 #ddd9ec #f7f5fd #191430', 'Be Vietnam Pro', 'Merriweather', 'stencil-mask', 'centered', 12, 'soft', 'studies awaiting scoring, one night each', 'Dr. Priya Raghunathan'),
  row('grill-line', 'Grill Line', 'Retro', 'diner grill short-order tickets', 'Restaurant|Events|Film & TV', 'Tickets in, *plates out.*', 'A short-order line for a diner that never closes.', 'The grill line is the original real-time system: tickets on a rail, a bell, and a cook who reads the whole board at once. The design is chrome and grease — a hard ticket rail, one red for what is burning, and no decoration a cook has to look past.', '#ff1500 #a8adb5 #facc15 #e8eaed #fafbfc #17181a', 'Rubik Doodle Shadow', 'Rubik', 'numbered-steps', 'hero-cards', 0, 'hard', 'tickets over four minutes, one rail each', 'Charlie Mbeki'),
  row('pumping-station', 'Pumping Station', 'Brutalism', 'water pumps mains valves pressure', 'Energy|Government|Construction', 'Lift it, *then let gravity pay.*', 'Mains pressure, kept inside a band.', 'A pumping station exists to hold one number steady: pressure at the far end of the main. Everything is duty and standby — pumps named, hours counted, and alarms that mean a street is about to lose water.', '#653874 #7d7694 #e07a5f #d9d5e0 #f5f3f8 #1b1826', 'Archivo Black', 'Familjen Grotesk', 'rivet-row', 'docs', 2, 'hairline', 'pumps past duty hours, one set each', 'Marek Dolny'),
  row('night-load', 'Night Load', 'Professional', 'grid substation voltage demand peaks', 'Energy|Data & Analytics|Government', 'Demand *after dark.*', 'The grid at the hour nobody is watching.', 'Baseload is the quietest engineering in the country: forecasts, set points, and a curve that has to hold while a city sleeps. The design is a control room — monospaced set points, one hot colour for deviation, and nothing decorative after midnight.', '#cebe08 #4a5a7a #38bdf8 #e6e2d6 #f8f7f2 #1a2333', 'Oxanium', 'Sora', 'outline-type', 'dashboard', 4, 'inset', 'feeders out of band, one trace each', 'Elsie Fairweather'),
  row('guard-room', 'Guard Room', 'Professional', 'security patrol keys logbook site', 'Real Estate|Government|Logistics', 'Sign in, *then walk the site.*', 'A site office that stays staffed all night.', 'A guard room is a logbook with a torch: handovers, patrol rounds, and a radio that has to work in the stairwell. Type is blunt, the route is a checklist, and the only bright element is the call button nobody wants to press.', '#0c356e #7c8aa0 #ffb020 #ccd6e2 #e8edf4 #0c1420', 'Space Mono', 'Raleway', 'scanlines', 'dashboard', 2, 'inset', 'rounds missed, one checkpoint each', 'Ravi Chandran'),
  row('cold-aisle', 'Cold Aisle', 'Professional', 'datacentre cooling racks servers', 'Data & Analytics|DevOps & Cloud|Cybersecurity', 'Cold by *design.*', 'A data hall where nothing is supposed to happen.', 'A cold aisle is a promise about temperature: racks in rows, blanking panels fitted, and a floor plan that quietly encodes which cabinet can die without anyone noticing. The system is a facility drawing — index numbers, aisle letters, and thermals plotted where engineers stand.', '#58888d #8fa8b5 #22d3ee #cfdde4 #eef6f9 #0b1a22', 'Inter', 'Red Hat Display', 'blueprint-grid', 'field-notes', 4, 'flat', 'cabinets above thermal budget', 'Gerard Ilunga'),
  row('carpark-night', 'Car Park Night', 'Brutalism', 'multistorey parking levels tickets bays', 'Automotive|Real Estate|Events', 'Level four, *space eighty-eight.*', 'A multi-storey with a concert on level one.', 'A car park at event time is a queue with circles in it: entry barriers, level counts, and a ticket that has to be found again afterwards. The design is signage — level letters at a glance, bay counts by floor, and arrows that forgive a wrong turn.', '#c88c41 #6f6a66 #f2c400 #ddd8d0 #f2efe9 #181713', 'Anton', 'Raleway', 'pill-nav', 'catalog', 0, 'hard', 'levels full, one ramp at a time', 'Charlie Mbeki'),
  row('corner-store-night', 'Corner Store Night', 'Playful', 'convenience shelves ice fluorescent till', 'Grocery|E-commerce|Community', 'Lit up *all night.*', 'A 24-hour store that is the only thing open.', 'A corner store at two in the morning is a public service with a freezer: three shelves, one clerk, and a fluorescent hum you can hear from the street. The design is bright and unglamorous — aisle numbers, price stickers, and a lottery board that never quite sells out.', '#ff0046 #2a2a3a #22d3ee #dcd8e0 #faf7fb #16121c', 'Syne', 'Gaegu', 'riso-offset', 'mosaic', 12, 'glow', 'shelves needing a restock, one aisle each', 'Mei-Lin Tan'),
  row('cinema-usher', 'Cinema Usher', 'Retro', 'cinema usher aisles late show', 'Film & TV|Events|Art Gallery', 'Last show, *first broom.*', 'An usher’s round after the credits.', 'The usher sees the cinema twice: once as an audience, once as rows of seats to be checked. The design is marquee and velvet — a ticket stub as a layout, house lights in gold, and a schedule that admits which screens overran.', '#a20921 #b08d3a #e8c547 #efe3d0 #fdf8f0 #241013', 'Gloock', 'Marcellus', 'ticket-stub', 'spotlight', 999, 'soft', 'screens running long, one reel each', 'Junko Arai'),
  row('sleep-coach', 'Sleep Coach', 'Minimalism', 'sleep winddown routine bedtime', 'Wellness|Mental Health|Health', 'Wind down, *on schedule.*', 'A bedtime routine that argues with nobody.', 'A sleep coach is a gentle system: a wind-down script, a light level, and a refusal to gamify rest. The design whispers with a single lavender accent, generous line height, and notifications that arrive before the evening starts to fade.', '#2c1f47 #a7a4c8 #c4b5fd #e4e6f2 #f8f9fd #141a2b', 'Mrs Saint Delafield', 'EB Garamond', 'vignette', 'centered', 20, 'soft', 'nights the routine slipped', 'Rosa Delgado'),
  row('rink-master', 'Rink Master', 'Playful', 'ice rink resurfacing skate sessions', 'Sports|Events|Kids', 'The ice is *ready at six.*', 'A rink that resurfaces between every session.', 'Resurfacing is the real product: the machine goes out, the water freezes, and a scratch-free sheet is what people actually bought. The design is cold and cheerful — session blocks, blade rules, and one pink for the moment the doors open.', '#42bcf0 #a9d5ea #ef476f #d3e6f0 #f2fafd #0a1f2c', 'Fredoka', 'Rubik', 'glass-sheen', 'split-hero', 999, 'soft', 'sessions cut short, one sheet each', 'Billy Hart'),
  row('milk-round', 'Milk Round', 'Organic', 'delivery milk crates route dawn', 'Grocery|Logistics|Community', 'Out before *the birds.*', 'A dairy round that still uses crates.', 'A milk round is logistics with a memory attached: standing orders, glass bottles, and a route that has not changed in thirty years. The system is a round sheet — crate counts, doorstep notes, and a depot list that reads like a village.', '#495bab #cfd8e3 #e8b04b #ece5d8 #fdfaf3 #221d16', 'Petrona', 'Lora', 'stitch-line', 'catalog', 4, 'soft', 'standing orders paused, one doorstep each', 'Elsie Fairweather'),
  row('flower-clock', 'Flower Clock', 'Organic', 'flowers auction clock stems growers', 'Marketplace|Agriculture|Grocery', 'The clock *sets the price.*', 'A flower auction where the price only falls.', 'Cut flowers are a perishable market with a deadline built in: stems arrive at midnight, the clock starts high, and the first bidder wins. The design keeps the room bright and the numbers ruthlessly legible — variety, clock state, and hours since cut.', '#9b4261 #a8c0a0 #f4a261 #f0dfe4 #fdf6f8 #2a1820', 'Cormorant Garamond', 'Familjen Grotesk', 'terrazzo-speck', 'mosaic', 8, 'soft', 'lots unsold at clock end, one tray each', 'Ada Nkemelu'),
  row('red-eye-desk', 'Red-Eye Desk', 'Professional', 'airport red-eye departures gates', 'Travel|Logistics|Booking', 'Departing *at 02:40.*', 'The counter for flights nobody enjoys.', 'A red-eye desk is a gate with a queue and a coffee machine: seat changes, standby lists, and announcements that arrive when passengers are least able to hear them. Type is bright against a night terminal, and the clock is the largest object on the screen.', '#070d86 #7b88a8 #f59e0b #d6dbea #f4f6fc #0b1120', 'Chakra Petch', 'Oxanium', 'ticker-marquee', 'receipt', 2, 'flat', 'standby seats released, one flight each', 'Tomas Reyes'),
  row('beacon-keeper', 'Beacon Keeper', 'Brutalism', 'lighthouse beacon shipping coast fog', 'Government|Travel|Energy', 'One light, *every night.*', 'A lighthouse that reports its own health.', 'A lighthouse is a maintenance schedule with a tower attached: lamp hours, fog signals, and a logbook that another keeper may read. The design is weatherproof — high contrast at the top, brass-tinted instruments, and one beam colour that never appears twice on a page.', '#2cbaa2 #7f9aa6 #ffd166 #d8e3e7 #f2f7f9 #101f26', 'Gloock', 'Hanken Grotesk', 'sonar-sweep', 'full-bleed', 4, 'glow', 'lamp hours past service, one watch each', 'Cornelius Pike'),
  row('cellar-barrel', 'Cellar Barrel', 'Organic', 'brewery barrels fermentation cellar', 'Manufacturing|Restaurant|Marketplace', 'The cellar *keeps its own time.*', 'Barrels that decide when the beer is ready.', 'Cellar work is patience with gravity: racking, gravity readings, and a barrel that is either clean or a problem. The system is quiet and damp — stencilled barrel numbers, one amber for what is ready, and no urgency anywhere in the type.', '#923e0c #b39270 #d97706 #e8dfd2 #faf5ec #241a12', 'Lora', 'Courier Prime', 'watermark-glyph', 'editorial', 4, 'hairline', 'barrels ready to rack, one stencil each', 'Gerard Ilunga'),
  row('sugar-shed', 'Sugar Shed', 'Playful', 'confectionery sweets boiling sugar', 'Manufacturing|Grocery|E-commerce', 'Boiled, pulled, *cut at dawn.*', 'A sweet factory that runs while it is cool.', 'Sugar work is temperature work: hard crack, soft ball, and a window of seconds between them. The design is cheerful and precise — pastel batches, a spinner of flavours, and numbers that stay readable through the steam.', '#cf6da6 #f7cddc #6d28d9 #f6e3ea #fff8fb #2c1622', 'Caveat', 'Rubik', 'quilt-patch', 'bento', 999, 'soft', 'batches on the boil, one pan each', 'Posy Nakamura'),
  row('vet-night', 'Vet Night', 'Professional', 'veterinary emergency animals night', 'Pets|Health|Clinic', 'Anything, *any hour.*', 'Emergency veterinary care after midnight.', 'A night vet practice triages by breathing first and paperwork second: species, weight, owner, and an estimate delivered kindly. The design is calm in green, with one warm accent for the animal currently in theatre and a queue that tells the truth about waiting.', '#2fa56a #a8c0b2 #e07a5f #dde8e1 #f6faf7 #131f19', 'Source Sans 3', 'Familjen Grotesk', 'stitch-line', 'docs', 6, 'soft', 'cases in theatre, one collar each', 'Dr. Priya Raghunathan'),
  row('patrol-log', 'Patrol Log', 'Professional', 'incidents logging patrol radio', 'Government|Cybersecurity|Community', 'Logged *as it happens.*', 'An incident log that timestamps itself.', 'A patrol log is a legal document written under a torch: radio traffic, times, and a narrative that has to survive a review six months later. The design is a terminal for the street — mono timestamps, terse entries, and no editable history.', '#050539 #6b7c96 #3b82f6 #ccd5e0 #f2f5f9 #0a1018', 'Space Mono', 'Hanken Grotesk', 'ledger-rules', 'dashboard', 0, 'flat', 'incidents awaiting closure, one entry each', 'Colin Bhaskar'),
  row('tunnel-bore', 'Tunnel Bore', 'Brutalism', 'tunnelling boring machine segments', 'Construction|Government|Energy', 'Under the city, *all night.*', 'A boring machine that never stops turning.', 'Tunnelling is a factory that moves: rings erected, spoil removed, and a control room watching pressure at the face. The design is heavy and sectional — ring numbers, segment counts, and a shift board that reads like a machine manual.', '#7b735b #9c9284 #d97a1e #d5cec4 #f2efe9 #1c1815', 'Anton', 'Public Sans', 'rivet-row', 'film-strip', 0, 'hard', 'rings behind schedule, one section each', 'Marek Dolny'),
  row('plough-route', 'Plough Route', 'Professional', 'snow plough grit routes winter', 'Government|Logistics|Automotive', 'Routes cleared *before six.*', 'Winter maintenance, routed by priority.', 'A snow route is a hierarchy agreed in summer: arterials first, hills before flats, and grit measured against a forecast that is always partly wrong. The design is a map with an argument — route order, spread rates, and a dispatch list anyone can read in a cab.', '#3c637b #8ea1b4 #c7f000 #d5dee6 #f0f4f7 #0e1720', 'Archivo', 'Zilla Slab', 'diagonal-bars', 'map-plate', 2, 'hard', 'routes not cleared by priority, one leg each', 'Elsie Fairweather'),
  row('audit-desk', 'Night Audit', 'Luxury', 'hotel audit night desk folio', 'Hotel|Banking|Accounting', 'The day *closes here.*', 'A hotel night audit that balances the house.', 'Night audit is the hour when the hotel is reconciled: folios posted, no-shows charged, and the day’s revenue signed off by one person at a quiet desk. The design is late-night luxury — deep plum, a gold seal, and totals that never round in the hotel’s favour.', '#8d1e85 #8a6a80 #d4af37 #e3d5dd #f9f4f7 #1e0f19', 'Gilda Display', 'Spectral', 'stamp-seal', 'split-scroll', 8, 'soft', 'folios out of balance, one room each', 'Constance Whitfield'),
  row('ramen-late', 'Ramen Late', 'Maximalism', 'ramen broth late counter stools', 'Restaurant|Events|Travel', 'Open until *the broth runs out.*', 'A ramen counter that opens at ten and closes when it is empty.', 'Late-night ramen is a countdown you can taste: broth simmered since noon, tickets taped to the counter, and a queue that thins after the last train. The design is steam and lanterns — heavy type, one red for sold-out bowls, and no small print a hungry person has to read.', '#9c513b #d9a08c #f4c95d #e9d7cb #faf2ea #1f120e', 'Baloo 2', 'Gaegu', 'halftone-dots', 'hero-cards', 6, 'hard', 'bowls sold out, one line per broth', 'Mei-Lin Tan'),
  row('dispatch-cab', 'Cab Dispatch', 'Retro', 'taxi dispatch fares night ranks', 'Automotive|Travel|Logistics', 'Best route, *worst hour.*', 'A radio dispatch that knows the city by street.', 'Cab dispatch is a matching problem at speed: nearest car, best route, and a driver who will argue with the algorithm. The design is a radio room — call signs, a fare board, and zones colour-coded the way the old operators used them.', '#ada71f #55534e #2563eb #ebe8df #faf8f2 #1d1c1a', 'Oswald', 'Rubik', 'corner-brackets', 'poster', 0, 'hard', 'cars waiting past ten minutes, one zone each', 'Charlie Mbeki'),
  row('dock-watch', 'Dock Watch', 'Professional', 'dock watch tide berths cargo', 'Logistics|Government|Energy', 'Tide first, *shift second.*', 'Berth scheduling that answers to the moon.', 'A dock watch plans around water that refuses to negotiate: berth windows, draft limits, and gangs stood down when the tide turns. The design is a ledger of arrivals — ship names, windows, and a running comment on weather nobody can control.', '#3093a6 #6f9aa8 #e2543a #cfdde3 #eef5f8 #0a1a22', 'Manrope', 'Courier Prime', 'dashed-borders', 'timeline', 0, 'flat', 'berths over window, one vessel each', 'Gerard Ilunga'),
  row('wet-market', 'Wet Market', 'Organic', 'market produce stalls scales fish', 'Grocery|Community|Marketplace', 'Best before *nine.*', 'A covered market that sells out by mid-morning.', 'A wet market prices by the hour: the best fish at six, a bargain at ten, and a bin that has to be empty by noon. The design is tiled and practical — stall numbers, scale readings, and a freshness mark that cannot be faked on a label.', '#24c322 #a4c3a8 #e2543a #dfe9e0 #f6faf6 #14231a', 'Petrona', 'Poppins', 'riso-offset', 'catalog', 2, 'hard', 'stalls low on stock, one tray each', 'Ada Nkemelu'),
  row('boiler-room', 'Boiler Room', 'Brutalism', 'boiler steam pressure heating plant', 'Energy|Construction|Real Estate', 'Steam up *before seven.*', 'A plant room that wakes a building.', 'A boiler room is a promise made in iron: pressure tested, valves tagged, and a schedule that starts hours before anyone wants heat. The design is gauges and grease — pipe labels, a log sheet, and one brass tone that marks anything a hand has touched.', '#62170e #9a8f7a #c9971b #e0d6c4 #f4eee2 #1f1610', 'Archivo Black', 'Raleway', 'grain-overlay', 'docs', 0, 'hard', 'boilers below set point, one plant each', 'Marek Dolny'),
  row('handover-ward', 'Handover Ward', 'Professional', 'handover shift wards clinicians', 'Health|Clinic|Mental Health', 'Shift notes, *passed on.*', 'The half hour where a ward changes hands.', 'Handover is where a hospital is most likely to drop something: who is sickest, what changed overnight, and which family is waiting for a call. The design is a structured board — one row per patient, escalations in the margin, and nothing that needs scrolling to be safe.', '#249094 #8fb3b0 #f59e0b #d9e6e5 #f4fafa #10201f', 'Sora', 'Rubik', 'outline-type', 'docs', 2, 'hairline', 'patients with open escalations', 'Dr. Priya Raghunathan'),
  row('laundromat-late', 'Laundromat Late', 'Minimalism', 'laundromat machines tokens late', 'Community|Real Estate|E-commerce', 'Wash, dry, *go home.*', 'A laundromat that runs on tokens and silence.', 'A laundromat after ten is a room of strangers agreeing not to talk: machines numbered, cycles timed, and a change machine that eats notes. The design is appliance-white and obliging — big timers, soft blue lights, and no branding louder than the machines.', '#68c4e4 #bcd3e4 #f4845f #dbe8f1 #f4fafc #131f28', 'Karla', 'Outfit', 'pill-nav', 'centered', 999, 'flat', 'machines out of service, one drum each', 'Posy Nakamura'),
  row('newsroom-wire', 'Newsroom Wire', 'Creative', 'newsroom wire copy desk filing', 'News|Publishing|Podcast', 'Filed *before the desk wakes.*', 'The wire desk that writes the first draft of the day.', 'A wire desk works against a clock set by other time zones: copy filed, headlines written, and a budget meeting at an hour nobody enjoys. The design is type-led — a column measure, a filing stamp, and one red reserved for a story that has to move now.', '#51391b #8a7f74 #b3261e #ded4c8 #f8f3ec #181310', 'EB Garamond', 'Courier Prime', 'editorial-columns', 'magazine', 0, 'hairline', 'copy past filing time, one desk each', 'Junko Arai'),
  row('mushroom-night', 'Mushroom Night', 'Organic', 'mushrooms foraging night harvest', 'Agriculture|Restaurant|Marketplace', 'Picked *by headlamp.*', 'A night harvest that has to reach market by dawn.', 'Some crops are picked in the dark because daylight costs them a day of shelf life: headlamps, shallow crates, and a cold room waiting. The design is quiet and mossy — field notes as a layout, one earthy accent, and weights recorded where hands are dirty.', '#948b38 #a2937f #7d8c45 #e2dac9 #f7f3ea #1d1710', 'Spectral', 'Zilla Slab', 'paper-cut', 'field-notes', 4, 'soft', 'crates behind the cold chain, one shed each', 'Ravi Chandran'),
  row('mortar-works', 'Mortar Works', 'Brutalism', 'repairs mortar masons night crew', 'Construction|Government|Real Estate', 'Repairs that *beat the traffic.*', 'Masonry crews that work while a street is closed.', 'Night masonry is a permit with a deadline: scaffold up by ten, mortar mixed in batches, and everything swept before the first bus. The design is a work order — mix ratios, gang hours, and one safety orange that only ever marks an opening in the ground.', '#89708f #a8a8a2 #e8630a #e0dfda #f6f6f4 #1d1d1b', 'Rubik', 'Merriweather', 'rivet-row', 'asymmetric', 0, 'flat', 'gangs past permit hours, one street each', 'Marek Dolny'),
  // __W14__
]
