import type { DesignSystem } from '../types'
import { sys } from './build'

/**
 * Wave 11 — the expansion toward five hundred.
 *
 * These seeds were authored against the taste audit's thresholds: every
 * palette here is a new set of six tokens, every structure combo (motif +
 * arrangement + radius + depth) is unused, every hero line is bespoke, and no
 * display/body pairing appears more than twice in the whole catalog. The
 * mechanical specifications (component states, spacing scale, contrast notes,
 * motion) are derived by src/designs/build.ts from the palette and character
 * declared below, so the file stays about *design decisions*.
 */

export const wave11Designs: DesignSystem[] = [
  /* ————————————————————————— Minimalism ————————————————————————— */
  sys({
    id: 'airmail',
    name: 'Airmail',
    category: 'Minimalism',
    tags: ['postal', 'aviation', 'forms', 'stripes', '1930s'],
    useCases: ['Logistics', 'Publishing', 'Travel'],
    hero: 'By air, *if it matters.*',
    description: 'The fastest way to say it travelled first class.',
    philosophy:
      'Air mail is the romance of infrastructure: stripes on the envelope, a customs form, and a promise that distance is a solved problem. The system is a printed form — every value has a line, every line has a label — and the only decoration is the edge stripe that says how it will travel.',
    colors: { primary: '#1d3f8f', secondary: '#c8322b', accent: '#f0c93c', neutral: '#e8e6df', background: '#f7f5ee', text: '#1c1b18' },
    display: 'Archivo',
    body: 'Courier Prime',
    motif: 'ticket-stub',
    layout: 'receipt',
    radius: 2,
    depth: 'flat',
    density: 'compact',
    accentRole: 'reserved for the customs stamp and nothing else',
    author: 'Tomas Ferreira',
    popularity: 78,
    cta: 'Send it express',
  }),
  sys({
    id: 'low-water',
    name: 'Low Water',
    category: 'Minimalism',
    tags: ['tides', 'tables', 'coastal', 'timing', 'quiet'],
    useCases: ['Travel', 'Energy', 'News'],
    hero: 'The sea keeps *appointments.*',
    description: 'A tide table you can read at a glance.',
    philosophy:
      'A tide table is a promise about the future written in numbers: the water will be here at 04:12 and gone by 10:40. Low Water sets those numbers as the page’s spine — chronological, tabular, undecorated — and admits exactly one colour, the coral that marks the next turning tide.',
    colors: { primary: '#0f5f6e', secondary: '#7b8f84', accent: '#e06c4b', neutral: '#e3e6e1', background: '#f5f6f3', text: '#15201f' },
    display: 'Jost',
    body: 'Public Sans',
    motif: 'slat-shadow',
    layout: 'timeline',
    radius: 3,
    depth: 'hairline',
    density: 'compact',
    accentRole: 'marks the next turning tide, nothing else',
    author: 'Aoife Manning',
    popularity: 74,
    cta: 'Read the table',
  }),
  sys({
    id: 'bone-china',
    name: 'Bone China',
    category: 'Minimalism',
    tags: ['porcelain', 'celadon', 'studio', 'light', 'seal'],
    useCases: ['Art Gallery', 'Fashion', 'Architecture'],
    hero: 'Thin walls, *held light.*',
    description: 'Porcelain, drawn in one breath.',
    philosophy:
      'Porcelain is the least forgiving material in the studio: one second of hesitation and the wall collapses. Bone China takes that discipline onto the page — a single stroke weight, a celadon that appears only where the light would fall, and a cobalt seal that is spent once per page.',
    colors: { primary: '#4d6b76', secondary: '#b9c6c9', accent: '#26418f', neutral: '#eceee9', background: '#f8f7f3', text: '#1e262b' },
    display: 'Marcellus',
    body: 'Karla',
    motif: 'inset-frame',
    layout: 'poster',
    radius: 0,
    depth: 'hairline',
    density: 'airy',
    accentRole: 'the maker’s seal, spent once per page',
    author: 'Yuki Tanabe',
    popularity: 82,
    trending: true,
    cta: 'See the kiln log',
  }),

  /* ————————————————————————— Maximalism ————————————————————————— */
  sys({
    id: 'crate-label',
    name: 'Crate Label',
    category: 'Maximalism',
    tags: ['citrus', 'growers', 'lithograph', 'sun', 'orchards'],
    useCases: ['Agriculture', 'Grocery', 'Marketplace'],
    hero: 'Picked *this morning,* sold by noon.',
    description: 'Grower labels for fruit with a fan club.',
    philosophy:
      'Before barcodes, a crate label was a fruit’s whole marketing department: six inks, a sunrise, and a promise of ripeness. Crate Label is that lithograph as an interface — saturated grounds, gold-leaf headers, and type that leans back and shouts the harvest.',
    colors: { primary: '#e2622b', secondary: '#1f7a4d', accent: '#f4c531', neutral: '#f7e6c4', background: '#fff6e3', text: '#3a1f12' },
    display: 'Alfa Slab One',
    body: 'Cabin',
    motif: 'stamp-seal',
    layout: 'catalog',
    radius: 6,
    depth: 'hard',
    density: 'regular',
    accentRole: 'stamped on anything graded premium',
    author: 'Marisol Vega',
    popularity: 85,
  }),
  sys({
    id: 'poster-wall',
    name: 'Poster Wall',
    category: 'Maximalism',
    tags: ['gig', 'paste-up', 'overlap', 'street', 'layers'],
    useCases: ['Music', 'Events', 'Community'],
    hero: 'Every night *worth pasting.*',
    description: 'A city wall that never stops arguing with itself.',
    philosophy:
      'A good gig wall is a conversation with no moderator: four promoters, three palettes, one roll of wheatpaste. Poster Wall keeps that argument on the page — overlapping sheets, torn corners, and a type mix that changes promoter with every panel.',
    colors: { primary: '#d7263d', secondary: '#2e1a47', accent: '#f9c22e', neutral: '#efe3d0', background: '#f6efe2', text: '#231a26' },
    display: 'Bungee',
    body: 'Space Grotesk',
    motif: 'quilt-patch',
    layout: 'mosaic',
    radius: 4,
    depth: 'hard',
    density: 'compact',
    accentRole: 'one poster in five, never more',
    author: 'Dee Ramírez',
    popularity: 87,
    trending: true,
  }),

  /* ————————————————————————— Brutalism ————————————————————————— */
  sys({
    id: 'loading-bay',
    name: 'Loading Bay',
    category: 'Brutalism',
    tags: ['warehouse', 'freight', 'bays', 'stencils', 'tonnage'],
    useCases: ['Logistics', 'Manufacturing', 'Marketplace'],
    hero: 'BAY 4. *TWELVE TONNES.* DEPARTED.',
    description: 'A dock that speaks only in stencils and numbers.',
    philosophy:
      'A loading bay communicates in three registers: bay number, weight, and time gone. Loading Bay refuses anything beyond that — stencilled labels knocked out of slab type, hazard yellow for moving parts, and a table where every row is a vehicle that is no longer your problem.',
    colors: { primary: '#1f5f3f', secondary: '#d97706', accent: '#facc15', neutral: '#d5d8d3', background: '#e8eae4', text: '#1a1d1a' },
    display: 'Archivo Black',
    body: 'Bitter',
    motif: 'rivet-row',
    layout: 'catalog',
    radius: 0,
    depth: 'hard',
    density: 'compact',
    accentRole: 'hazard only — moving machinery and overdue trailers',
    author: 'Gunther Weiss',
    popularity: 83,
  }),
  sys({
    id: 'bunker-hall',
    name: 'Bunker Hall',
    category: 'Brutalism',
    tags: ['data', 'subterranean', 'concrete', 'ledger', 'archival'],
    useCases: ['Data & Analytics', 'Government', 'Cybersecurity'],
    hero: 'COLD STORAGE FOR *LOUD NUMBERS.*',
    description: 'A records hall that outlives its builders.',
    philosophy:
      'Deep archives are architecture first: concrete, redundancy, and a ledger that assumes the reader is not yet born. Bunker Hall sets records in slab type on gunmetal grounds, with a single signal green for what is currently readable and nothing else allowed to glow.',
    colors: { primary: '#4b5320', secondary: '#2f3438', accent: '#8db600', neutral: '#c9c8c2', background: '#dedcd6', text: '#1b1d1c' },
    display: 'Archivo Black',
    body: 'Source Sans 3',
    motif: 'blueprint-grid',
    layout: 'docs',
    radius: 0,
    depth: 'flat',
    density: 'compact',
    accentRole: 'readable-status only, one row at a time',
    author: 'Ingrid Solheim',
    popularity: 79,
  }),

  /* ————————————————————————— Luxury ————————————————————————— */
  sys({
    id: 'perfume-organ',
    name: 'Perfume Organ',
    category: 'Luxury',
    tags: ['perfumery', 'accords', 'violet', 'brass', 'atelier'],
    useCases: ['Beauty & Spa', 'Fashion', 'Hotel'],
    hero: 'A hundred bottles, *one idea.*',
    description: 'Perfumery as an instrument you play.',
    philosophy:
      'A perfume organ is a keyboard of raw materials, and the perfumer plays accords, not notes. This system is that instrument — dark violet felt, a brass weft through every surface, and one petal tone that behaves like a top note: the first thing you notice, the first to disappear.',
    colors: { primary: '#4c1d95', secondary: '#b98a5e', accent: '#e8c9d6', neutral: '#221733', background: '#120b1d', text: '#f3ecf8' },
    display: 'Gilda Display',
    body: 'Hanken Grotesk',
    motif: 'glass-sheen',
    layout: 'split-scroll',
    radius: 14,
    depth: 'glow',
    density: 'airy',
    accentRole: 'the top note, first on the page and gone by the fold',
    author: 'Camille Aubert',
    popularity: 88,
    trending: true,
    cta: 'Open the organ',
  }),
  sys({
    id: 'silver-service',
    name: 'Silver Service',
    category: 'Luxury',
    tags: ['dining', 'service', 'menu', 'silver', 'ritual'],
    useCases: ['Restaurant', 'Hotel', 'Wedding'],
    hero: 'Served from the *left,* always.',
    description: 'Fine dining, plated as a rulebook.',
    philosophy:
      'Silver service is a choreography with a manual: which side, which hand, which order. The system mirrors that etiquette — a menu set as a program, double rules where courses change, and a silverpoint grey that never once raises its voice.',
    colors: { primary: '#3f4a52', secondary: '#8b9aa1', accent: '#c9a97a', neutral: '#e9e7e1', background: '#f7f6f2', text: '#23282c' },
    display: 'Cormorant Garamond',
    body: 'Mulish',
    motif: 'double-rule',
    layout: 'spotlight',
    radius: 0,
    depth: 'hairline',
    density: 'airy',
    accentRole: 'the house pour and nothing else',
    author: 'Étienne Rocher',
    popularity: 84,
  }),

  /* ————————————————————————— Creative ————————————————————————— */
  sys({
    id: 'signal-flag',
    name: 'Signal Flag',
    category: 'Creative',
    tags: ['maritime', 'semaphore', 'flags', 'codes', 'geometry'],
    useCases: ['Logistics', 'Community', 'Sports'],
    hero: 'Forty flags, *no vowels.*',
    description: 'The alphabet that flies.',
    philosophy:
      'Signal flags are a vocabulary of shapes: each one means a letter, a number, or a warning, and the message is only as good as the rope it hangs on. Signal Flag builds the page as a hoist — bold geometric panels, thick cord lines, and a legend that refuses to guess.',
    colors: { primary: '#1f4e79', secondary: '#d64545', accent: '#f2b134', neutral: '#e4e7ea', background: '#f4f7f9', text: '#12232f' },
    display: 'Chakra Petch',
    body: 'Inter',
    motif: 'lattice-weave',
    layout: 'bento',
    radius: 2,
    depth: 'flat',
    density: 'regular',
    accentRole: 'flies only at the top of the hoist',
    author: 'Noor Haddad',
    popularity: 80,
  }),
  sys({
    id: 'cover-art',
    name: 'Cover Art',
    category: 'Creative',
    tags: ['records', 'sleeves', 'print', 'offset', 'studio'],
    useCases: ['Music', 'Art Gallery', 'Publishing'],
    hero: 'One sleeve, *one second* to earn the flip.',
    description: 'Record covers designed like posters you keep.',
    philosophy:
      'A record sleeve is the smallest poster in the world and the only one people keep for fifty years. Cover Art treats every panel as a print: misregistered inks, paper stock that shows its tooth, and type placed like it was set by hand because it was.',
    colors: { primary: '#ff4d6d', secondary: '#1b998b', accent: '#ffd166', neutral: '#efe6dd', background: '#f9f3ec', text: '#201a26' },
    display: 'Bricolage Grotesque',
    body: 'Figtree',
    motif: 'riso-offset',
    layout: 'mosaic',
    radius: 2,
    depth: 'flat',
    density: 'regular',
    accentRole: 'one pressing in ten, numbered',
    author: 'Jonas Beck',
    popularity: 86,
  }),

  /* ————————————————————————— Professional ————————————————————————— */
  sys({
    id: 'escrow',
    name: 'Escrow',
    category: 'Professional',
    tags: ['funds', 'settlement', 'conditions', 'trust', 'ledger'],
    useCases: ['Fintech', 'Legal', 'Real Estate'],
    hero: 'Released when *the conditions clear.*',
    description: 'Money that waits until the paperwork agrees.',
    philosophy:
      'Escrow is the discipline of holding: funds sit outside both parties until every condition is met, and the interface’s job is to make those conditions countable. Escrow lists them as a register — dated, initialled, and never rounded — over a paper that will not be rushed.',
    colors: { primary: '#0e6b5c', secondary: '#4a5568', accent: '#b7791f', neutral: '#e6e4dd', background: '#f7f6f2', text: '#1a2422' },
    display: 'IBM Plex Sans',
    body: 'IBM Plex Sans',
    motif: 'ledger-rules',
    layout: 'docs',
    radius: 4,
    depth: 'flat',
    density: 'compact',
    accentRole: 'marks funds still held, never released',
    author: 'Priyanka Shah',
    popularity: 77,
  }),
  sys({
    id: 'on-call',
    name: 'On Call',
    category: 'Professional',
    tags: ['incident', 'pager', 'runbook', 'night', 'ops'],
    useCases: ['DevOps & Cloud', 'Developer Tools', 'Cybersecurity'],
    hero: 'Paged at *03:12.* Awake by 03:13.',
    description: 'A console built for the worst hour of the week.',
    philosophy:
      'An incident console has one reader: a tired engineer with one hand on a phone. On Call is built for that hand — enormous status type, runbook steps as a checklist that never scrolls away, and one alarm red that is impossible to mistake for decoration.',
    colors: { primary: '#d92d20', secondary: '#384152', accent: '#f79009', neutral: '#1f2733', background: '#131a24', text: '#e8edf5' },
    display: 'Sora',
    body: 'IBM Plex Sans',
    motif: 'scanlines',
    layout: 'dashboard',
    radius: 3,
    depth: 'inset',
    density: 'compact',
    accentRole: 'acknowledgement state, nothing else',
    author: 'Marcus Oyelaran',
    popularity: 84,
    trending: true,
  }),
  sys({
    id: 'assay-office',
    name: 'Assay Office',
    category: 'Professional',
    tags: ['laboratory', 'tolerances', 'metals', 'certificates', 'precision'],
    useCases: ['Manufacturing', 'Energy', 'Data & Analytics'],
    hero: 'Within *0.02 mm* or it goes back.',
    description: 'A testing lab that publishes its tolerances.',
    philosophy:
      'An assay office exists to say no: the sample is measured, the tolerance is checked, and the certificate carries a number you can be sued over. The system is that certificate as a workspace — ruled tables, figures with aligned decimals, and a stamp blue that means the result is final.',
    colors: { primary: '#4a4037', secondary: '#6b7280', accent: '#b45309', neutral: '#e6e2da', background: '#f7f5f1', text: '#1d1a16' },
    display: 'Literata',
    body: 'Source Sans 3',
    motif: 'double-rule',
    layout: 'field-notes',
    radius: 2,
    depth: 'hairline',
    density: 'compact',
    accentRole: 'failed samples only, once per certificate',
    author: 'Helena Brandt',
    popularity: 75,
  }),

  /* ————————————————————————— Organic ————————————————————————— */
  sys({
    id: 'shearwater',
    name: 'Shearwater',
    category: 'Organic',
    tags: ['seabird', 'migration', 'tracking', 'coasts', 'patience'],
    useCases: ['Nonprofit', 'Travel', 'Data & Analytics'],
    hero: 'Ninety grams, *ten thousand kilometres.*',
    description: 'Tracking the longest commute on earth.',
    philosophy:
      'The shearwater crosses an ocean twice a year and returns to the same burrow, and the science of following it is mostly patience and a good map. The system reads like a field report — slate sea, one amber tag colour, and coordinates given without decoration.',
    colors: { primary: '#2f4858', secondary: '#7fa8a0', accent: '#d98e3e', neutral: '#dfe4df', background: '#f2f5f3', text: '#1c2a30' },
    display: 'Newsreader',
    body: 'Manrope',
    motif: 'vignette',
    layout: 'map-plate',
    radius: 4,
    depth: 'flat',
    density: 'regular',
    accentRole: 'tagged birds and only tagged birds',
    author: 'Rún Petersen',
    popularity: 76,
  }),
  sys({
    id: 'malt-house',
    name: 'Malt House',
    category: 'Organic',
    tags: ['barley', 'kiln', 'distillery', 'floor', 'patience'],
    useCases: ['Manufacturing', 'Restaurant', 'Agriculture'],
    hero: 'Slow barley, *loud peat.*',
    description: 'A distilling floor that keeps its own books.',
    philosophy:
      'Malting is patience with a schedule: steep, germinate, kiln, rest. The system keeps a floor book rather than a brochure — ruled pages, a barley gold that only touches numbers, and margins wide enough for a hand to disagree with the last shift.',
    colors: { primary: '#7a4a1f', secondary: '#3f4a3a', accent: '#d9a441', neutral: '#e6dcc8', background: '#f6efe2', text: '#241a12' },
    display: 'Bitter',
    body: 'Work Sans',
    motif: 'terrazzo-speck',
    layout: 'field-notes',
    radius: 6,
    depth: 'soft',
    density: 'regular',
    accentRole: 'the kiln log — dates and temperatures only',
    author: 'Callum Mackay',
    popularity: 80,
  }),

  /* ————————————————————————— Retro ————————————————————————— */
  sys({
    id: 'ticket-window',
    name: 'Ticket Window',
    category: 'Retro',
    tags: ['railway', 'tickets', 'brass', 'punch', 'departures'],
    useCases: ['Travel', 'Booking', 'Logistics'],
    hero: 'One way, *third class,* 1954.',
    description: 'The romance of the ticket window.',
    philosophy:
      'Railway tickets were printed objects with rules: holes punched, dates stamped, fares in pounds and shillings. Ticket Window revives that bureaucracy as a language — punched edges, stamp seals, and a brass that appears only where money changes hands.',
    colors: { primary: '#14532d', secondary: '#8c1d2f', accent: '#d6a419', neutral: '#e7e2d6', background: '#f4efe3', text: '#1f1a14' },
    display: 'Instrument Serif',
    body: 'Karla',
    motif: 'stamp-seal',
    layout: 'receipt',
    radius: 1,
    depth: 'hairline',
    density: 'compact',
    accentRole: 'fares and nothing else — money is the only brass',
    author: 'Edith Hollis',
    popularity: 83,
  }),
  sys({
    id: 'newsreel',
    name: 'Newsreel',
    category: 'Retro',
    tags: ['cinema', 'narration', 'frames', 'sepia', 'archive'],
    useCases: ['Film & TV', 'News', 'Publishing'],
    hero: 'The world, *reel by reel.*',
    description: 'News, cut at twenty-four frames a second.',
    philosophy:
      'A newsreel was an argument delivered in ninety seconds: a stentorian voice, a camera that always found the flag, and titles that told you what to feel. Newsreel rebuilds that grammar honestly — film frames, sprocket rails, and captions that admit they are captions.',
    colors: { primary: '#2f2a22', secondary: '#7a6a52', accent: '#c9743a', neutral: '#ded4bd', background: '#f0e9d6', text: '#241f18' },
    display: 'Oswald',
    body: 'Cabin',
    motif: 'slat-shadow',
    layout: 'film-strip',
    radius: 2,
    depth: 'flat',
    density: 'compact',
    accentRole: 'the one item in the reel that is not history yet',
    author: 'Frank Delaney',
    popularity: 81,
  }),

  /* ————————————————————————— Playful ————————————————————————— */
  sys({
    id: 'bubble-wrap',
    name: 'Bubble Wrap',
    category: 'Playful',
    tags: ['packaging', 'popping', 'protect', 'satisfying', 'mail'],
    useCases: ['E-commerce', 'Subscription Box', 'Kids'],
    hero: 'Pop *responsibly.*',
    description: 'Everything arrives intact, including the fun.',
    philosophy:
      'Bubble wrap is the only packaging people fight over: it protects a thing and then becomes a toy. The system treats protection as pleasure — inflated rounds, satisfying press states, and a mint that makes the foam look colder than it is.',
    colors: { primary: '#0ea5a3', secondary: '#5b7cfa', accent: '#fda4af', neutral: '#e8f1f2', background: '#f6fbfb', text: '#123033' },
    display: 'Fredoka',
    body: 'Nunito',
    motif: 'terrazzo-speck',
    layout: 'bento',
    radius: 999,
    depth: 'soft',
    density: 'airy',
    accentRole: 'handle-with-care items, once per shipment',
    author: 'Posy Nakamura',
    popularity: 86,
  }),
  sys({
    id: 'slot-car',
    name: 'Slot Car',
    category: 'Playful',
    tags: ['racing', 'tabletop', 'club', 'scale', 'lap times'],
    useCases: ['Sports', 'Community', 'Events'],
    hero: 'Lap *7.42.* Beat that.',
    description: 'A tabletop racing club with real standings.',
    philosophy:
      'Slot car racing is motorsport shrunk to a table, which means the drama scales perfectly: tyre choice arguments, disputed lap counts, and a ladder board that matters more than any trophy. The system is the club noticeboard — bold numbers, track tape, and standings updated in pen.',
    colors: { primary: '#d90429', secondary: '#0f7a6c', accent: '#ffb703', neutral: '#e9e6e1', background: '#f7f4ef', text: '#241a1a' },
    display: 'Rubik',
    body: 'Quicksand',
    motif: 'ribbon-band',
    layout: 'mosaic',
    radius: 10,
    depth: 'soft',
    density: 'regular',
    accentRole: 'fastest lap of the night, one board only',
    author: 'Beto Sá',
    popularity: 79,
  }),

  /* ————————————————————————— part 2 ————————————————————————— */
  sys({
    id: 'paperback',
    name: 'Paperback',
    category: 'Minimalism',
    tags: ['books', 'pocket', 'series', 'cream', 'colophon'],
    useCases: ['Publishing', 'Education', 'Community'],
    hero: 'Two hundred pages, *one pocket.*',
    description: 'A paperback series with a spine you can read across a room.',
    philosophy:
      'The paperback is the most democratic object in publishing: cheap enough to fold, good enough to keep. Paperback designs the series as a spine language — a cream ground, a single oxblood band, and a colophon that treats paper stock as a design decision.',
    colors: { primary: '#7c2d12', secondary: '#57534e', accent: '#ca8a04', neutral: '#eadfc8', background: '#faf4e6', text: '#2a2018' },
    display: 'Gloock',
    body: 'EB Garamond',
    motif: 'stitch-line',
    layout: 'editorial',
    radius: 1,
    depth: 'hairline',
    density: 'regular',
    accentRole: 'the series band — one per cover, never inside',
    author: 'Hattie Voss',
    popularity: 79,
  }),
  sys({
    id: 'survey-pin',
    name: 'Survey Pin',
    category: 'Minimalism',
    tags: ['geodesy', 'benchmarks', 'plans', 'fieldwork', 'accuracy'],
    useCases: ['Construction', 'Real Estate', 'Data & Analytics'],
    hero: 'Accuracy you can *walk to.*',
    description: 'Land survey notes, drawn to scale.',
    philosophy:
      'A survey pin is a fact you can stand on: a brass disc in the ground that says this point has been agreed. Survey Pin draws the trade around that disc — plot numbers in a light face, a single olive that means measured, and brackets that refuse to round anything.',
    colors: { primary: '#3f6212', secondary: '#8a8f7c', accent: '#d97706', neutral: '#e5e6de', background: '#f4f5ef', text: '#1f2416' },
    display: 'Instrument Serif',
    body: 'Public Sans',
    motif: 'blueprint-grid',
    layout: 'map-plate',
    radius: 0,
    depth: 'flat',
    density: 'compact',
    accentRole: 'tolerances outside spec and nothing else',
    author: 'Rafel Bosch',
    popularity: 72,
  }),
  sys({
    id: 'typo-slam',
    name: 'Typo Slam',
    category: 'Maximalism',
    tags: ['manifesto', 'rants', 'type', 'zine', 'argument'],
    useCases: ['Publishing', 'Community', 'Design Tools'],
    hero: 'LOUD IS A *POSITION.*',
    description: 'A zine that argues in display sizes.',
    philosophy:
      'A slam poem and a broadside have the same job: make the room quiet before you finish. Typo Slam sets every page as an argument — giant type, one fluorescent interruption, and a watermark glyph that watches the debate from behind.',
    colors: { primary: '#171717', secondary: '#b45309', accent: '#d4ff00', neutral: '#e6e6e2', background: '#f4f4f0', text: '#101010' },
    display: 'Anton',
    body: 'Space Mono',
    motif: 'watermark-glyph',
    layout: 'manifesto',
    radius: 0,
    depth: 'hard',
    density: 'compact',
    accentRole: 'one fluorescent interruption per spread',
    author: 'Ines Duarte',
    popularity: 84,
  }),
  sys({
    id: 'pinball-parlour',
    name: 'Pinball Parlour',
    category: 'Maximalism',
    tags: ['arcade', 'backglass', 'flippers', 'neon', 'scores'],
    useCases: ['Gaming', 'Events', 'Community'],
    hero: 'TILT IS A *TEACHER.*',
    description: 'A parlour where the machines outnumber the seats.',
    philosophy:
      'A pinball backglass is a painting that also keeps score: hot pink lightning, a chrome logo, and numbers that light up in the dark. Pinball Parlour treats every surface as a cabinet — saturated, legible from three metres, and never sorry.',
    colors: { primary: '#d81b60', secondary: '#1b3a8f', accent: '#ffd166', neutral: '#241a33', background: '#150f24', text: '#f6ecff' },
    display: 'Righteous',
    body: 'Livvic',
    motif: 'sonar-sweep',
    layout: 'spotlight',
    radius: 8,
    depth: 'glow',
    density: 'regular',
    accentRole: 'high scores only — the one number allowed to burn',
    author: 'Rosa Delgado',
    popularity: 86,
  }),
  sys({
    id: 'freight-lift',
    name: 'Freight Lift',
    category: 'Brutalism',
    tags: ['elevator', 'vertical', 'tonnage', 'steel', 'schedule'],
    useCases: ['Logistics', 'Construction', 'Manufacturing'],
    hero: 'UP 14 TONNES. *NO PASSENGERS.*',
    description: 'A goods lift with a weight limit and opinions.',
    philosophy:
      'A freight lift is a promise measured in tonnes: the gate closes, the counterweight decides, and the schedule is not negotiable. The system is that machine — steel grey, hazard markings at the edges, and rivets where the load goes.',
    colors: { primary: '#374151', secondary: '#b45309', accent: '#facc15', neutral: '#d1d5db', background: '#e5e7eb', text: '#111827' },
    display: 'Bebas Neue',
    body: 'IBM Plex Sans',
    motif: 'rivet-row',
    layout: 'full-bleed',
    radius: 0,
    depth: 'hard',
    density: 'compact',
    accentRole: 'overload warnings, welded on',
    author: 'Piotr Kowalczyk',
    popularity: 76,
  }),
  sys({
    id: 'rebar-house',
    name: 'Rebar House',
    category: 'Brutalism',
    tags: ['concrete', 'reinforcement', 'ties', 'structure', 'site'],
    useCases: ['Construction', 'Architecture', 'Manufacturing'],
    hero: 'The steel is the *argument.*',
    description: 'Concrete that admits what holds it up.',
    philosophy:
      'Rebar is never meant to be seen, which is exactly why it is worth showing: the grid of steel that decides whether a slab survives is also the honest drawing of the building. Rebar House puts the cage on the surface — tied intersections, concrete grey, and a signal orange for anything load-bearing.',
    colors: { primary: '#78716c', secondary: '#44403c', accent: '#a16207', neutral: '#d6d3d1', background: '#e7e5e4', text: '#1c1917' },
    display: 'Archivo',
    body: 'Work Sans',
    motif: 'stitch-line',
    layout: 'bento',
    radius: 0,
    depth: 'hard',
    density: 'compact',
    accentRole: 'load paths — one drawing per page marks them',
    author: 'Sofia Marchetti',
    popularity: 78,
  }),
  sys({
    id: 'first-class',
    name: 'First Class',
    category: 'Luxury',
    tags: ['aviation', 'cabin', 'silver', 'itinerary', 'calm'],
    useCases: ['Travel', 'Hotel', 'Booking'],
    hero: 'The seat folds *into a bed.*',
    description: 'The front cabin, rendered as an itinerary.',
    philosophy:
      'First class is not about the seat; it is about the fact that nobody will ask you anything for eleven hours. The system reads like a printed itinerary — night navy, a silverpoint that never glares, and a cabin bronze spent only on time.',
    colors: { primary: '#2b3a63', secondary: '#a3aab8', accent: '#b06a33', neutral: '#e9e7e3', background: '#f8f7f4', text: '#1a2033' },
    display: 'Cormorant Garamond',
    body: 'Jost',
    motif: 'inset-frame',
    layout: 'film-strip',
    radius: 2,
    depth: 'hairline',
    density: 'airy',
    accentRole: 'departure times, once per itinerary',
    author: 'Margaux Lefèvre',
    popularity: 85,
  }),
  sys({
    id: 'sable-coat',
    name: 'Sable Coat',
    category: 'Luxury',
    tags: ['tailoring', 'bespoke', 'lapel', 'wool', 'fit'],
    useCases: ['Fashion', 'Hotel', 'Wedding'],
    hero: 'Measured *thirty-one times.*',
    description: 'Bespoke tailoring that shows its seams.',
    philosophy:
      'A bespoke coat is a record of a body: thirty-one measurements, four fittings, and a maker who remembers your shoulders. Sable Coat presents the atelier honestly — oxblood lining, chalk marks, and a page that fits like it was cut for you.',
    colors: { primary: '#7f1d1d', secondary: '#57534e', accent: '#d6d3d1', neutral: '#e7e2dc', background: '#f6f2ec', text: '#1f1a17' },
    display: 'Playfair Display',
    body: 'Mulish',
    motif: 'torn-edge',
    layout: 'asymmetric',
    radius: 2,
    depth: 'soft',
    density: 'airy',
    accentRole: 'the basted stitch line during a fitting',
    author: 'Osman Yilmaz',
    popularity: 83,
  }),
  sys({
    id: 'neon-sign-shop',
    name: 'Neon Sign Shop',
    category: 'Creative',
    tags: ['neon', 'glassbending', 'tubes', 'dusk', 'workshop'],
    useCases: ['Design Tools', 'E-commerce', 'Community'],
    hero: 'Bent by hand, *lit by dusk.*',
    description: 'A workshop where letters are made of light.',
    philosophy:
      'Neon is glass that argues with physics: a tube is bent, pumped, gassed, and then it either glows or it does not. Neon Sign Shop keeps that workshop honesty — dark walls, one cyan tube colour, and letters that look bent rather than typed.',
    colors: { primary: '#06b6d4', secondary: '#e11d48', accent: '#fde047', neutral: '#1f2937', background: '#0c1220', text: '#e6f4f8' },
    display: 'Monoton',
    body: 'Figtree',
    motif: 'glow-pulse',
    layout: 'catalog',
    radius: 6,
    depth: 'glow',
    density: 'regular',
    accentRole: 'the transformer hum — one live sign per page',
    author: 'Lena Kovač',
    popularity: 87,
    trending: true,
  }),
  sys({
    id: 'paper-marble',
    name: 'Paper Marble',
    category: 'Creative',
    tags: ['bookbinding', 'endpapers', 'ink', 'float', 'craft'],
    useCases: ['Publishing', 'Art Gallery', 'Design Tools'],
    hero: 'Ink floats, *paper remembers.*',
    description: 'Endpapers swirled by hand, one sheet at a time.',
    philosophy:
      'Marbling is a printing technique with no control and complete authorship: the ink floats, the comb decides, and every sheet is unrepeatable. Paper Marble lets that accident lead — oil-slick swirls on soft paper, a violet that behaves like ink, and rules that keep quiet around the edges.',
    colors: { primary: '#9333ea', secondary: '#0e7490', accent: '#f472b6', neutral: '#eee6f5', background: '#faf6fd', text: '#241a2e' },
    display: 'Spectral',
    body: 'Karla',
    motif: 'oil-slick',
    layout: 'editorial',
    radius: 0,
    depth: 'soft',
    density: 'regular',
    accentRole: 'the combed edge of a single sheet',
    author: 'Ondine Belle',
    popularity: 81,
  }),
  sys({
    id: 'redaction',
    name: 'Redaction',
    category: 'Professional',
    tags: ['legal', 'disclosure', 'privacy', 'black', 'review'],
    useCases: ['Legal', 'Government', 'Cybersecurity'],
    hero: 'What you *can’t read* matters too.',
    description: 'Document review where the black bars are the point.',
    philosophy:
      'A redacted page is a design problem disguised as a legal one: what to hide, what to reveal, and how to prove the difference. Redaction treats the black bar as a first-class element — precise, countable, and never mistaken for decoration.',
    colors: { primary: '#0f172a', secondary: '#64748b', accent: '#dc2626', neutral: '#e2e8f0', background: '#f8fafc', text: '#0b1220' },
    display: 'Newsreader',
    body: 'IBM Plex Sans',
    motif: 'punched-card',
    layout: 'docs',
    radius: 2,
    depth: 'flat',
    density: 'compact',
    accentRole: 'unresolved redactions, one pending claim each',
    author: 'Yolanda Reyes',
    popularity: 79,
  }),
  sys({
    id: 'throughput',
    name: 'Throughput',
    category: 'Professional',
    tags: ['ports', 'containers', 'berths', 'schedules', 'tonnage'],
    useCases: ['Logistics', 'Data & Analytics', 'Manufacturing'],
    hero: 'Berth 7 clears *at 04:00.*',
    description: 'Port operations, counted in moves per hour.',
    philosophy:
      'A port measures itself in moves per hour and apologises to no one. Throughput is the operations board for that world — harbour blue, crane amber, and berth rows a dispatcher can read with one eye while talking on the radio.',
    colors: { primary: '#075985', secondary: '#64748b', accent: '#f59e0b', neutral: '#dbe4ea', background: '#eef3f6', text: '#10222e' },
    display: 'Chakra Petch',
    body: 'Work Sans',
    motif: 'slat-shadow',
    layout: 'dashboard',
    radius: 2,
    depth: 'flat',
    density: 'compact',
    accentRole: 'delayed berths, and only delayed berths',
    author: 'Dmitri Volkov',
    popularity: 77,
  }),
  sys({
    id: 'kelp-line',
    name: 'Kelp Line',
    category: 'Organic',
    tags: ['seaweed', 'farming', 'ropes', 'tidal', 'harvest'],
    useCases: ['Agriculture', 'Energy', 'Grocery'],
    hero: 'Grown in *cold water,* harvested by hand.',
    description: 'A seaweed farm that reads the tide for a living.',
    philosophy:
      'Kelp farming is rope and patience: seeded lines, six metres down, a harvest decided by water temperature. Kelp Line draws that farm as a long scroll — sea green, rope lines that carry the eye, and torn edges where the harvest ends.',
    colors: { primary: '#3c6e47', secondary: '#0e7490', accent: '#f59e0b', neutral: '#dce8e0', background: '#eff6f1', text: '#12261a' },
    display: 'Literata',
    body: 'Public Sans',
    motif: 'torn-edge',
    layout: 'film-strip',
    radius: 3,
    depth: 'flat',
    density: 'regular',
    accentRole: 'harvest weeks and nothing else',
    author: 'Maren Sørvik',
    popularity: 74,
  }),
  sys({
    id: 'smokehouse',
    name: 'Smokehouse',
    category: 'Organic',
    tags: ['barbecue', 'woods', 'briskets', 'patience', 'fire'],
    useCases: ['Restaurant', 'Grocery', 'Events'],
    hero: 'Fourteen hours, *no shortcuts.*',
    description: 'A pitmaster’s log with the temperature kept honest.',
    philosophy:
      'Barbecue is patience with a probe in it: the fire is tended, the stall is respected, and the meat decides when it is done. Smokehouse is the pit log — warm stone, ember notes, and ticket-stub edges for the orders that never sit.',
    colors: { primary: '#57534e', secondary: '#9a3412', accent: '#d97706', neutral: '#e7e0d5', background: '#f6f0e6', text: '#241d18' },
    display: 'Bitter',
    body: 'Cabin',
    motif: 'ticket-stub',
    layout: 'catalog',
    radius: 2,
    depth: 'soft',
    density: 'regular',
    accentRole: 'the pit temperature at its current reading',
    author: 'Curtis Bowen',
    popularity: 82,
  }),
  sys({
    id: 'drive-in',
    name: 'Drive-In',
    category: 'Retro',
    tags: ['cinema', 'cars', 'dusk', 'speakers', 'double-bill'],
    useCases: ['Film & TV', 'Events', 'Automotive'],
    hero: 'Showtime at *dusk, engine off.*',
    description: 'A double bill under an enormous sky.',
    philosophy:
      'The drive-in is a cinema where the car is the seat and the sky is the ceiling, and the whole experience is designed backwards from nightfall. Drive-In keeps that amber dusk — glowing marquee numbers, slatted shadows, and a programme that knows you will stay for the second feature.',
    colors: { primary: '#be123c', secondary: '#1e3a8a', accent: '#facc15', neutral: '#2a2233', background: '#151021', text: '#f7eef2' },
    display: 'Bungee Shade',
    body: 'Karla',
    motif: 'slat-shadow',
    layout: 'spotlight',
    radius: 4,
    depth: 'glow',
    density: 'regular',
    accentRole: 'showtime, once per night',
    author: 'Ray Mackey',
    popularity: 85,
  }),
  sys({
    id: 'shoebox-slides',
    name: 'Shoebox Slides',
    category: 'Retro',
    tags: ['photography', 'archives', 'family', 'kodachrome', 'memory'],
    useCases: ['Photography', 'Publishing', 'Community'],
    hero: 'Somebody *labelled them all.*',
    description: 'A family archive, eight slides at a time.',
    philosophy:
      'A shoebox of slides is a family’s real history: over-exposed beaches, a garden that no longer exists, and handwriting on every mount. Shoebox Slides builds the archive as a timeline — amber stock, a vignette where memory fades, and captions in the same blue pen.',
    colors: { primary: '#a16207', secondary: '#b45309', accent: '#0e7490', neutral: '#e8dfcc', background: '#f7f1e4', text: '#2a2113' },
    display: 'Amatic SC',
    body: 'Spectral',
    motif: 'vignette',
    layout: 'timeline',
    radius: 2,
    depth: 'soft',
    density: 'regular',
    accentRole: 'the pen date on every mount',
    author: 'Ruth Anders',
    popularity: 78,
  }),
  sys({
    id: 'candy-stand',
    name: 'Candy Stand',
    category: 'Playful',
    tags: ['fair', 'stall', 'sweets', 'stripes', 'pennies'],
    useCases: ['Events', 'Kids', 'Grocery'],
    hero: 'Everything is *three pennies.*',
    description: 'A school-fair stand with a ledger of joy.',
    philosophy:
      'A candy stand is economics for children: inventory becomes emotion, and the price list is a poem. Candy Stand keeps that first-economics energy — fuchsia stripes, quilted panels of stock, and a till that always rounds in your favour.',
    colors: { primary: '#c026d3', secondary: '#2563eb', accent: '#fde047', neutral: '#fdf0ff', background: '#fffaf0', text: '#2d1440' },
    display: 'Caveat',
    body: 'Nunito',
    motif: 'quilt-patch',
    layout: 'bento',
    radius: 999,
    depth: 'hard',
    density: 'airy',
    accentRole: 'the daily special, one per stall',
    author: 'Nia Okafor',
    popularity: 83,
  }),
  sys({
    id: 'paper-plane',
    name: 'Paper Plane',
    category: 'Playful',
    tags: ['fold', 'flight', 'contests', 'creases', 'daylight'],
    useCases: ['Kids', 'Education', 'Sports'],
    hero: 'Fold, *aim, release.*',
    description: 'A throwing contest where the design flies.',
    philosophy:
      'A paper plane is engineering you can hold: one sheet, four folds, and a flight shaped entirely by the crease. Paper Plane turns the page into that contest — dashed fold guides, a sky blue that starts the moment the nose lifts, and scores kept like a school league.',
    colors: { primary: '#0ea5e9', secondary: '#f97316', accent: '#22c55e', neutral: '#e8f4fb', background: '#f8fcfe', text: '#123043' },
    display: 'Gaegu',
    body: 'Nunito',
    motif: 'ribbon-band',
    layout: 'film-strip',
    radius: 10,
    depth: 'soft',
    density: 'airy',
    accentRole: 'the winning distance, once per contest',
    author: 'Sam Whitfield',
    popularity: 80,
  }),
]
