import type { DesignSystem } from '../types'
import { row, sys } from './build'

/**
 * Wave 12 — places and institutions: the systems that run a city, a service,
 * or a quiet room. Same rules as wave 11: unique palettes, unique structure
 * combos, bespoke heroes, and no type pairing used more than twice.
 */

export const wave12Designs: DesignSystem[] = [
  sys({
    id: 'white-room',
    name: 'White Room',
    category: 'Minimalism',
    tags: ['gallery', 'install', 'light', 'plumb', 'labels'],
    useCases: ['Art Gallery', 'Architecture', 'Events'],
    hero: 'Nothing hangs until *the wall is right.*',
    description: 'Gallery installation, measured to the millimetre.',
    philosophy:
      'The white cube is not empty; it is tuned — light temperature, hanging height, and the exact distance a visitor stands from a label. White Room is the installer’s system: a slate that stays quiet, one safety orange, and measurements that are never rounded.',
    colors: { primary: '#64748b', secondary: '#94a3b8', accent: '#ea580c', neutral: '#f1f5f9', background: '#fbfcfd', text: '#0f172a' },
    display: 'Instrument Serif',
    body: 'Inter',
    motif: 'inset-frame',
    layout: 'split-scroll',
    radius: 0,
    depth: 'hairline',
    density: 'airy',
    accentRole: 'tapes and levels — scale drawing only',
    author: 'Marta Keskküla',
    popularity: 76,
  }),
  sys({
    id: 'timetable',
    name: 'Timetable',
    category: 'Minimalism',
    tags: ['rail', 'departures', 'columns', 'punctual', 'notice'],
    useCases: ['Travel', 'Booking', 'News'],
    hero: 'Departs *07:04.* Not 07:03.',
    description: 'A departure board that respects your time.',
    philosophy:
      'A timetable is a public promise written in columns. Timetable sets every service as a ruled row, keeps cancellations in the only accent allowed, and refuses decoration on the grounds that a platform is not a poster.',
    colors: { primary: '#1f2937', secondary: '#6b7280', accent: '#f59e0b', neutral: '#e5e7eb', background: '#f9fafb', text: '#111827' },
    display: 'Archivo',
    body: 'Public Sans',
    motif: 'ledger-rules',
    layout: 'timeline',
    radius: 0,
    depth: 'flat',
    density: 'compact',
    accentRole: 'delays and cancellations only',
    author: 'Owen Pryce',
    popularity: 74,
  }),
  sys({
    id: 'still-air',
    name: 'Still Air',
    category: 'Minimalism',
    tags: ['hvac', 'commissioning', 'quiet', 'balance', 'flow'],
    useCases: ['Construction', 'Energy', 'Health'],
    hero: 'The room breathes *at 40 decibels.*',
    description: 'Air balancing for buildings that must not be heard.',
    philosophy:
      'The best HVAC system is the one nobody notices: balanced, quiet, and commissioned before the furniture arrives. Still Air is the balancing report — cool grey-green, airflow diagrams, and a wake-up call for anything that hums.',
    colors: { primary: '#4b6a63', secondary: '#94a3a0', accent: '#fb923c', neutral: '#e8ecea', background: '#f6f8f7', text: '#16211e' },
    display: 'Jost',
    body: 'Source Sans 3',
    motif: 'vignette',
    layout: 'centered',
    radius: 8,
    depth: 'soft',
    density: 'airy',
    accentRole: 'fan noise above spec, one room per report',
    author: 'Åke Lindberg',
    popularity: 72,
  }),
  sys({
    id: 'notebook-margin',
    name: 'Notebook Margin',
    category: 'Minimalism',
    tags: ['study', 'notes', 'revision', 'quiet', 'margins'],
    useCases: ['E-learning', 'University', 'Productivity'],
    hero: 'The margin is *where thinking happens.*',
    description: 'A study tool that leaves room for doubt.',
    philosophy:
      'Notes are not records; they are arguments with your earlier self. Notebook Margin keeps a wide gutter for exactly that — ruled lines, a single ink, and a margin that can hold a correction without breaking the page.',
    colors: { primary: '#334155', secondary: '#94a3b8', accent: '#0ea5e9', neutral: '#eef2f7', background: '#fafbfd', text: '#0f172a' },
    display: 'Literata',
    body: 'Red Hat Display',
    motif: 'double-rule',
    layout: 'field-notes',
    radius: 4,
    depth: 'hairline',
    density: 'regular',
    accentRole: 'unresolved questions, marked once each',
    author: 'Selin Aydın',
    popularity: 78,
  }),
  sys({
    id: 'toy-shelf',
    name: 'Toy Shelf',
    category: 'Maximalism',
    tags: ['toys', 'shelves', 'plastic', 'weekend', 'bright'],
    useCases: ['Kids', 'E-commerce', 'Marketplace'],
    hero: 'Every shelf is *a small world.*',
    description: 'A toy shop that stocks happiness by the metre.',
    philosophy:
      'A toy shop’s shelf is a machine for wanting: colour-coded, stacked to the ceiling, and rearranged every Saturday. Toy Shelf keeps that density — speckled vinyl, fat packages, and a mascot tone that changes aisle by aisle.',
    colors: { primary: '#f43f5e', secondary: '#2563eb', accent: '#fde047', neutral: '#fff1f2', background: '#fffaf5', text: '#2b1030' },
    display: 'Patrick Hand',
    body: 'Nunito',
    motif: 'terrazzo-speck',
    layout: 'bento',
    radius: 8,
    depth: 'soft',
    density: 'airy',
    accentRole: 'new-in-this-week, one shelf at a time',
    author: 'Pia Lindqvist',
    popularity: 82,
  }),
  sys({
    id: 'hot-sauce-wall',
    name: 'Hot Sauce Wall',
    category: 'Maximalism',
    tags: ['condiments', 'heat', 'labels', 'scoville', 'kitchen'],
    useCases: ['Grocery', 'Restaurant', 'E-commerce'],
    hero: 'Heat is *a category.*',
    description: 'Condiments ranked by Scoville and swagger.',
    philosophy:
      'A hot sauce wall is a library of capsaicin: dozens of labels competing for the same shelf, each one convinced it is the hottest. The system leans into the aisle — ribbon banners, bottle-forward cards, and a heat scale that never rounds down.',
    colors: { primary: '#c2185b', secondary: '#facc15', accent: '#22c55e', neutral: '#ffe9d6', background: '#fff7ed', text: '#3a1408' },
    display: 'Bungee',
    body: 'Work Sans',
    motif: 'ribbon-band',
    layout: 'catalog',
    radius: 4,
    depth: 'glow',
    density: 'regular',
    accentRole: 'anything past 100k Scoville, once per row',
    author: 'Diego Salas',
    popularity: 84,
  }),
  sys({
    id: 'penny-press',
    name: 'Penny Press',
    category: 'Maximalism',
    tags: ['souvenir', 'coins', 'squash', 'museum', 'collection'],
    useCases: ['Travel', 'Events', 'Community'],
    hero: 'Fifty-one cents, *pressed into memory.*',
    description: 'Souvenir pennies, catalogued like treasure.',
    philosophy:
      'A squashed penny is a machine-made heirloom: two coins, one crank, and a design that survives in a pocket for decades. Penny Press keeps the collection in order — punched cards, brass numbering, and a map of every machine still standing.',
    colors: { primary: '#854d0e', secondary: '#b45309', accent: '#0ea5e9', neutral: '#efe3cf', background: '#faf3e6', text: '#2c2115' },
    display: 'Rye',
    body: 'Source Sans 3',
    motif: 'punched-card',
    layout: 'receipt',
    radius: 2,
    depth: 'hard',
    density: 'compact',
    accentRole: 'machines out of service, one row each',
    author: 'Bea Whitmore',
    popularity: 77,
  }),
  sys({
    id: 'carousel-9',
    name: 'Carousel 9',
    category: 'Maximalism',
    tags: ['airport', 'luggage', 'carousel', 'chaos', 'arrivals'],
    useCases: ['Travel', 'Logistics', 'News'],
    hero: 'Your bag is *on belt nine.* Probably.',
    description: 'Arrivals, rendered at the speed of rumour.',
    philosophy:
      'An arrivals hall is a maximalist environment by accident: overlapping announcements, four languages, and a belt that never quite stops. Carousel 9 keeps that noise but organises it — ticket edges, neon arrows, and a status for every bag that anyone has ever lost.',
    colors: { primary: '#8b5cf6', secondary: '#ec4899', accent: '#facc15', neutral: '#e9e4f5', background: '#f6f3fb', text: '#221a38' },
    display: 'Unbounded',
    body: 'Mulish',
    motif: 'ticket-stub',
    layout: 'mosaic',
    radius: 2,
    depth: 'soft',
    density: 'compact',
    accentRole: 'bags still on the belt, one flare each',
    author: 'Priscilla Navarre',
    popularity: 83,
  }),
  sys({
    id: 'slab-city', name: 'Slab City', category: 'Brutalism',
    tags: ['parking', 'municipal', 'concrete', 'rams'],
    useCases: ['Government', 'Real Estate'],
    hero: 'Pay here. *Then park.*',
    description: 'The municipal parking authority, rendered in concrete.',
    philosophy: 'A parking structure is a public building that refuses to be liked: ramps, numbers, and a booth that has seen everything.',
    colors: { primary: '#5b6068', secondary: '#8a8f96', accent: '#eab308', neutral: '#d6d9dc', background: '#e8eaec', text: '#171b1f' },
    display: 'Archivo', body: 'Work Sans', motif: 'rivet-row', layout: 'docs', radius: 0, depth: 'flat', density: 'compact',
    accentRole: 'fines and overstays, one notice each', author: 'Nils Berg',
  }),
  sys({
    id: 'grit-bin', name: 'Grit Bin', category: 'Brutalism',
    tags: ['roads', 'winter', 'salt', 'depot'],
    useCases: ['Government', 'Logistics'],
    hero: 'Winter is *a logistics problem.*',
    description: 'Road salt, stockpiled before the first frost.',
    philosophy: 'Gritting is a promise made in summer and kept in January: routes, tonnage, and drivers who leave at 4am.',
    colors: { primary: '#2f3d35', secondary: '#7d8891', accent: '#facc15', neutral: '#d9dde0', background: '#ebedef', text: '#161c21' },
    display: 'Bebas Neue', body: 'Manrope', motif: 'slat-shadow', layout: 'full-bleed', radius: 0, depth: 'hard', density: 'compact',
    accentRole: 'untreated routes during a freeze', author: 'Ken Adjei',
  }),
  sys({
    id: 'obelisk-net', name: 'Obelisk Net', category: 'Brutalism',
    tags: ['telecom', 'towers', 'signal', 'night', 'grid'],
    useCases: ['DevOps & Cloud', 'Energy', 'Cybersecurity'],
    hero: 'One tower holds *eleven thousand calls.*',
    description: 'The network, as seen from the mast.',
    philosophy: 'A telecom mast is concrete, steel, and bureaucracy with a red light on top; the signal is the least visible thing about it.',
    colors: { primary: '#a21caf', secondary: '#4b5563', accent: '#22d3ee', neutral: '#2a1833', background: '#170d1f', text: '#f4e9fa' },
    display: 'Oxanium', body: 'IBM Plex Sans', motif: 'sonar-sweep', layout: 'dashboard', radius: 2, depth: 'inset', density: 'compact',
    accentRole: 'degraded masts, one cell each', author: 'Ravi Chandrasekhar',
  }),
  sys({
    id: 'block-house', name: 'Block House', category: 'Brutalism',
    tags: ['storage', 'units', 'locks', 'anonymous', 'concrete'],
    useCases: ['Real Estate', 'Marketplace', 'Logistics'],
    hero: 'Unit 214. *Nobody asks.*',
    description: 'Self-storage for things and their reasons.',
    philosophy: 'A storage facility is architecture with no windows and impeccable records: gated, numbered, and indifferent to what you keep.',
    colors: { primary: '#f59e0b', secondary: '#1f2937', accent: '#ef4444', neutral: '#e7e5e4', background: '#f5f5f4', text: '#1c1917' },
    display: 'Anton', body: 'Karla', motif: 'punched-card', layout: 'catalog', radius: 0, depth: 'hard', density: 'compact',
    accentRole: 'units open past billing, flagged once', author: 'Bridget Osei',
  }),
  sys({
    id: 'black-car', name: 'Black Car', category: 'Luxury',
    tags: ['chauffeur', 'town', 'night', 'discreet'],
    useCases: ['Travel', 'Booking', 'Hotel'],
    hero: 'The driver is already *outside.*',
    description: 'Chauffeured town cars, run like a private airline.',
    philosophy: 'A black car service sells one thing: the absence of friction — a name on a board, a door held open, and a route chosen before you asked.',
    colors: { primary: '#c0a062', secondary: '#3f3f46', accent: '#c0a062', neutral: '#1c1c20', background: '#0e0e10', text: '#f2f0ea' },
    display: 'Bodoni Moda', body: 'Jost', motif: 'glass-sheen', layout: 'spotlight', radius: 999, depth: 'glow', density: 'airy',
    accentRole: 'the pickup time, once per booking', author: 'Idris Bello',
  }),
  sys({
    id: 'oyster-bar', name: 'Oyster Bar', category: 'Luxury',
    tags: ['seafood', 'brine', 'counters', 'marble', 'cold'],
    useCases: ['Restaurant', 'Hotel', 'Events'],
    hero: 'Today the tide brought *twelve kinds.*',
    description: 'A cold counter with a chalkboard list.',
    philosophy: 'An oyster bar is luxury without ceremony: a marble trench, a shucker’s shorthand, and a menu that changes with the water temperature.',
    colors: { primary: '#2c7a7b', secondary: '#b7c9c9', accent: '#e0a458', neutral: '#e3ecec', background: '#f6fafa', text: '#14282a' },
    display: 'Marcellus', body: 'Mulish', motif: 'double-rule', layout: 'receipt', radius: 0, depth: 'hairline', density: 'compact',
    accentRole: 'today’s catch, one line per tide', author: 'Marguerite Chastain',
  }),
  sys({
    id: 'white-glove', name: 'White Glove', category: 'Luxury',
    tags: ['housekeeping', 'hotel', 'standards', 'quiet', 'checklist'],
    useCases: ['Hotel', 'Booking', 'Beauty & Spa'],
    hero: 'Forty-two checks *before you arrive.*',
    description: 'Housekeeping standards, audited nightly.',
    philosophy: 'Five-star housekeeping is an invisible protocol: exact folds, exact angles, and a checklist that is finished before the guest ever sees the room.',
    colors: { primary: '#71717a', secondary: '#a1a1aa', accent: '#e11d48', neutral: '#f4f4f5', background: '#fdfdfd', text: '#18181b' },
    display: 'Gilda Display', body: 'Hanken Grotesk', motif: 'stitch-line', layout: 'film-strip', radius: 6, depth: 'soft', density: 'airy',
    accentRole: 'anything below standard, one flag each', author: 'Sofia Delacroix',
  }),
  sys({
    id: 'lodge-fire', name: 'Lodge Fire', category: 'Luxury',
    tags: ['alpine', 'timber', 'quiet', 'snow', 'hearth'],
    useCases: ['Hotel', 'Travel', 'Wellness'],
    hero: 'Boots off. *Fire on.*',
    description: 'An alpine lodge that books by the season.',
    philosophy: 'A good lodge is built around one chair beside one fire: heavy timber, wool, and a concierge who knows which pass opens first.',
    colors: { primary: '#1f4d3a', secondary: '#8a5a3b', accent: '#e07a5f', neutral: '#e9e2d5', background: '#f7f2e8', text: '#1d2a22' },
    display: 'Newsreader', body: 'Karla', motif: 'paper-cut', layout: 'split-scroll', radius: 8, depth: 'soft', density: 'airy',
    accentRole: 'firewood delivery days, one per week', author: 'Jonas Brenner',
  }),
  // — rows: id, name, cat, tags, useCases, hero, desc, philosophy, colors, display, body, motif, layout, radius, depth, accentRole, author —
  row('sound-booth', 'Sound Booth', 'Creative', 'voice booth acoustics foam warm', 'Podcast|Streaming|Music', 'Say it once, *say it right.*', 'A voice booth tuned for the spoken word.', 'A booth is a small promise: the room disappears, the voice stays, and the edit is short because the take was honest.', '#db2777 #312e81 #22d3ee #fce7f3 #fff7fb #241336', 'Syne', 'Manrope', 'riso-offset', 'centered', 12, 'glow', 'live takes only, one dot each', 'Ana Sofia Reis'),
  row('matte-paint', 'Matte Paint', 'Creative', 'film set paint scenics flats dust', 'Film & TV|Design Tools|Events', 'Paint it, *then light it.*', 'Scenic paint for sets that must not shine.', 'A film set is painted for the camera, not the eye: flat finishes, matched tones, and a green screen that never reflects.', '#52525b #22c55e #f97316 #e4e4e7 #f4f4f5 #18181b', 'Archivo Black', 'Work Sans', 'oil-slick', 'film-strip', 2, 'flat', 'chroma work, kept off every other surface', 'Roland Devereux'),
  row('petal-work', 'Petal Work', 'Creative', 'florist stems bouquets studio stems', 'Art Gallery|Wedding|Beauty & Spa', 'Stems in, *stories out.*', 'A floral studio that books by the season.', 'Floristry is sculpture with a deadline: conditioned stems, a colour story, and a van leaving at six with everything already wilting.', '#6b7c5e #f472b6 #eab308 #f0ede6 #faf8f3 #1f241b', 'Cormorant Garamond', 'Quicksand', 'terrazzo-speck', 'catalog', 999, 'soft', 'seasonal stems, one batch at a time', 'Hana Fujimoto'),
  row('model-shop', 'Model Shop', 'Creative', 'scale kits parts decals bench', 'Design Tools|Gaming|E-commerce', 'Scale is *a discipline.*', 'Scale models, catalogued by sprue.', 'A good model shop sells patience by the box: numbered sprues, decal sheets, and a bench where the carpet monster lives.', '#0369a1 #94a3b8 #ef4444 #dbeafe #f0f9ff #0f172a', 'Chakra Petch', 'Figtree', 'slat-shadow', 'bento', 2, 'hard', 'out-of-stock sprues, flagged once', 'Tobias Lund'),
  row('sketchbook-club', 'Sketchbook Club', 'Creative', 'drawing urban sketch shared weekly', 'Community|Art Gallery|Education', 'Draw where *you stand.*', 'Urban sketchers, one page a week.', 'An urban sketch is a receipt for a place: fifteen minutes, a pen that cannot be erased, and a page that records the weather as much as the architecture.', '#3f3f46 #f59e0b #0ea5e9 #ececec #fafafa #18181b', 'Caveat', 'Karla', 'watermark-glyph', 'field-notes', 4, 'soft', 'the week’s prompt, one page only', 'Elif Kaya'),
  row('docket-line', 'Docket Line', 'Professional', 'court cases hearings counsel diary', 'Legal|Government|Consulting', 'The court *sits at ten.*', 'Case management for a working court.', 'A docket is a queue with consequences: everything listed, everything dated, and nothing allowed to be late twice.', '#6b1d3a #8a8f96 #c2410c #ece4e6 #f9f5f6 #241620', 'Spectral', 'Manrope', 'double-rule', 'timeline', 2, 'flat', 'adjourned matters, one line each', 'Alastair Croft'),
  row('care-rota', 'Care Rota', 'Professional', 'nursing shifts handover wards team', 'Health|HR & Recruiting|Clinic', 'Handover is *sacred.*', 'Shift planning for a ward that never closes.', 'A rota is a promise to patients and staff at once: cover guaranteed, nights shared fairly, and a handover that takes exactly as long as it needs.', '#115e59 #6366f1 #f59e0b #e5f3f1 #f6fbfa #0f2e2b', 'Outfit', 'Source Sans 3', 'ribbon-band', 'dashboard', 8, 'soft', 'uncovered shifts, one banner per ward', 'Grace Mwangi'),
  row('customs-broker', 'Customs Broker', 'Professional', 'tariffs clearance borders forms', 'Logistics|Legal|Government', 'Cleared, *stamped, gone.*', 'Customs paperwork without the queue.', 'A customs broker is a translator between two bureaucracies: codes, duties, and a container that costs money every hour it waits.', '#3f2d20 #8a7965 #0f766e #e8e0d4 #f7f3ea #221a12', 'DM Serif Display', 'Public Sans', 'stamp-seal', 'docs', 3, 'hairline', 'held consignments, one stamp each', 'Lucía Ferrer'),
  row('audit-trail', 'Audit Trail', 'Professional', 'compliance evidence controls testing', 'Accounting|Cybersecurity|Consulting', 'Every control *has a receipt.*', 'Audit evidence, filed as it happens.', 'An audit trail is boring on purpose: timestamps, owners, and proof that the control ran even when nobody was watching.', '#3d4a3a #8d9a8a #dc2626 #e8e9e3 #f8f9f5 #1d221c', 'Familjen Grotesk', 'Inter', 'double-rule', 'docs', 0, 'flat', 'failed controls, one exception each', 'Priya Balan'),
  row('permit-desk', 'Permit Desk', 'Professional', 'municipal permits inspections queue', 'Government|Construction|Real Estate', 'Approved, with *conditions.*', 'Municipal permits, tracked to the day.', 'The permit desk is where a city says yes slowly: applications, inspections, and a queue that is fair because it is visible.', '#5b4a3f #8a7965 #0ea5e9 #e2e8f0 #f7f9fb #0f172a', 'Bitter', 'Public Sans', 'stamp-seal', 'receipt', 2, 'hard', 'stop-work notices, one per parcel', 'Eamon Doyle'),
  row('family-office', 'Family Office', 'Luxury', 'wealth generations trust discretion', 'Banking|Legal|Consulting', 'Wealth, *kept quiet,* across generations.', 'Private wealth, managed like a foundation.', 'A family office exists to make money boring: one strategy, patient capital, and a rulebook that outlives its authors.', '#0b3d2e #7c8b84 #b08d3e #e4e8e4 #f7f9f7 #16221d', 'Newsreader', 'Jost', 'ledger-rules', 'editorial', 2, 'hairline', 'capital calls, one line per quarter', 'Constance Whitfield'),

  row('orchard-row', 'Orchard Row', 'Organic', 'apples harvest rows cider autumn', 'Agriculture|Grocery|Nonprofit', 'Rows picked *in order.*', 'An apple orchard that knows every tree by name.', 'An orchard is a spreadsheet that blossoms: rootstock, row, and variety recorded long before the first fruit is worth eating.', '#7a8b3d #b45309 #e11d48 #eef0e2 #f8faf0 #20261a', 'Petrona', 'Mulish', 'paper-cut', 'mosaic', 6, 'soft', 'ripe varieties, one row per week', 'Imogen Blake'),
  row('hedgerow', 'Hedgerow', 'Organic', 'biodiversity corridors nesting layering', 'Nonprofit|Agriculture|Education', 'A hedge is *a corridor.*', 'Field boundaries that feed everything crossing them.', 'A hedgerow is infrastructure disguised as a fence: layered species, nesting cover, and a corridor between two woods that were once one.', '#3e4a2e #8a9166 #c2410c #e6e6dc #f4f4ec #1d2115', 'Lora', 'Karla', 'torn-edge', 'timeline', 3, 'flat', 'planting years, one entry per stretch', 'Rowan Ellis'),
  row('mushroom-log', 'Mushroom Log', 'Organic', 'fungi logs inoculation shade damp', 'Grocery|Agriculture|Restaurant', 'Inoculate, *then wait* for rain.', 'A gourmet mushroom farm built on logs.', 'Mushroom farming is scheduling rot: hardwood logs, spawn plugs, shade, and a harvest that arrives exactly when it has finished deciding.', '#5f5546 #7d8a5a #d97706 #e5e0d2 #f4f1e6 #221c14', 'Zilla Slab', 'Source Sans 3', 'grain-overlay', 'field-notes', 4, 'soft', 'flushes ready for picking, one mark each', 'Toma Ilić'),
  row('river-keeper', 'River Keeper', 'Organic', 'restoration waterway banks monitoring', 'Nonprofit|Energy|Government', 'Count the mayfly, *read the river.*', 'River restoration, measured in species.', 'A river is healthy when the invertebrates say so: sampling nets, kick tests, and a record that decides where the next meander is rebuilt.', '#2a6f8a #7fa8a0 #d97706 #dce8ec #eef6f9 #10262e', 'Newsreader', 'Work Sans', 'lattice-weave', 'map-plate', 4, 'flat', 'impaired stretches, one reach at a time', 'Siobhán Walsh'),
  row('sun-dry', 'Sun Dry', 'Organic', 'drying fruit solar racks harvest', 'Grocery|Agriculture|Energy', 'The sun is *the kiln.*', 'Solar drying for fruit, fish, and grain.', 'Solar drying is patience with a thermometer: racks angled at the season, turning every two hours, and a moisture reading that ends the day.', '#7c6a12 #b45309 #0ea5e9 #ece4c8 #f8f3df #26200e', 'Archivo', 'Karla', 'halftone-dots', 'catalog', 2, 'hard', 'racks below moisture spec, one flag each', 'Amara Diop'),

  row('milk-bar', 'Milk Bar', 'Retro', 'shakes formica chrome jukebox', 'Restaurant|Events|Community', 'Shakes thick enough *to stand a spoon.*', 'A 1950s milk bar, chrome and all.', 'A milk bar is a social engine: a counter, a jukebox, and a menu that costs less than the bus fare home.', '#1d4ed8 #f5d0a9 #e11d48 #e9edf5 #f7f9fc #101a2e', 'Monoton', 'Quicksand', 'halftone-dots', 'centered', 999, 'glow', 'the day’s special shake, one flavour', 'Dotty Fraser'),
  row('airship-line', 'Airship Line', 'Retro', 'zeppelin duralumin routes lounge', 'Travel|Logistics|Events', 'Dinner at *two thousand feet.*', 'Passenger airships, scheduled like ocean liners.', 'An airship line sold altitude as etiquette: a dining room with windows, a route over the pole, and a timetable measured in days.', '#5d6b7a #c9d2d8 #b91c1c #e4e8eb #f4f6f8 #1a222c', 'Jost', 'EB Garamond', 'inset-frame', 'spotlight', 4, 'soft', 'mooring delays, one per port', 'Cornelius Pike'),
  row('paper-round', 'Paper Round', 'Retro', 'newsboy morning streets bicycle rain', 'News|Publishing|Community', 'Up before *the ink dries.*', 'A morning paper round, mapped street by street.', 'A paper round is a route, a bag, and a hundred small promises delivered before breakfast — the original same-day logistics.', '#6b7280 #9ca3af #b45309 #e5e7eb #f4f4f5 #1f2937', 'Oswald', 'Source Sans 3', 'paper-cut', 'timeline', 2, 'soft', 'missed drops, marked once per street', 'Billy Hart'),
  row('telethon', 'Telethon', 'Retro', 'fundraising phones pledges broadcast', 'Nonprofit|Events|Streaming', 'Keep the lines *open all night.*', 'A charity broadcast that counts every pledge.', 'A telethon is television with a scoreboard: pledge totals climbing, phone banks lit, and a host who has not slept since Thursday.', '#3b0764 #f59e0b #22c55e #e9d5ff #f7f0ff #241033', 'Bungee', 'Nunito', 'glow-pulse', 'manifesto', 8, 'glow', 'pledge milestones, one ring each', 'Marva Jenkins'),
  row('bouncy-castle', 'Bouncy Castle', 'Playful', 'parties inflatables hire squeals', 'Events|Kids|Community', 'Shoes off. *Gravity optional.*', 'Inflatable party hire with a safety record.', 'A bouncy castle is engineering for joy: anchor points, a pressure gauge, and an hour of chaos that ends exactly on schedule.', '#fb7185 #22d3ee #fde047 #fff1f2 #fffbeb #2d1730', 'Baloo 2', 'Quicksand', 'ribbon-band', 'bento', 999, 'soft', 'punctured units, one patch note each', 'Loz Fisher'),
  row('duck-race', 'Duck Race', 'Playful', 'fundraiser rubber ducks river current', 'Nonprofit|Events|Sports', 'Ten thousand ducks, *one finish line.*', 'A charity duck race on a cold river.', 'A duck race is luck made visible: numbered ducks, a current nobody controls, and a finish line photographed from three angles.', '#1b7c8c #fbbf24 #e11d48 #d9f0f4 #f2fbfc #0e2c33', 'Patrick Hand', 'Nunito', 'wave-section', 'film-strip', 999, 'soft', 'first ducks to the weir, three places', 'Charlie Ngata'),
  row('sock-puppet', 'Sock Puppet', 'Playful', 'craft theatre buttons wool making', 'Kids|Education|Community', 'Give it *a voice.*', 'A craft kit for stories that talk back.', 'A sock puppet is theatre with no budget: a button eye, a felt tongue, and an audience that is already laughing.', '#4d7c0f #f59e0b #e11d48 #eef0ff #f8f9ff #1c1b33', 'Patrick Hand', 'Quicksand', 'quilt-patch', 'field-notes', 12, 'hard', 'puppet-show days, one stage each', 'Wren Baker'),
  row('sticker-album', 'Sticker Album', 'Playful', 'collect swaps doubles foil', 'Kids|Community|Marketplace', 'Got any *doubles?*', 'A sticker collection with a trading economy.', 'A sticker album teaches scarcity and friendship: numbered slots, shiny specials, and a playground market that sets its own exchange rate.', '#84cc16 #0ea5e9 #f9a8d4 #eef7e0 #f8fdf2 #1a2b10', 'Fredoka', 'Karla', 'tape-labels', 'catalog', 4, 'soft', 'shiny swaps, one per trade', 'Tilly Morgan'),
]
