import type { DesignSystem } from '../types'

/**
 * Wave 8 — sixteen systems built around aesthetics and verticals the catalog
 * did not yet carry: solarpunk, a physics lab, terrazzo, a noir case file,
 * optical art, VHS rental, a riso studio, PCB fabrication, cut-paper craft,
 * glacial spa, an observatory, a weather bureau, pulp paperbacks, an artisan
 * bakery, a spy console, and classical marble.
 *
 * Five of them introduce new motifs (outline-type, corner-brackets, scanlines,
 * duotone-media, tape-labels), so these are structurally new, not recolors.
 * Every palette, type pairing, and layout was checked against the existing 184
 * in scripts/audit-designs.cjs — no identity or palette collisions.
 */

export const wave8Designs: DesignSystem[] = [
  {
    id: 'solar-punk',
    name: 'Solarpunk',
    category: 'Organic',
    tags: ['solarpunk', 'renewable', 'community', 'optimism', 'green'],
    description: 'A hopeful future, wired to the sun.',
    designPhilosophy:
      'Dystopia got all the good designers. Solarpunk takes the opposite bet: technology and nature as allies, abundance instead of scarcity, and a palette that looks like photosynthesis under glass. Warm sunlight accents over living green, rounded architecture, and type that smiles without trying. For climate projects, community energy, and civic optimism.',
    colors: { primary: '#2f9e44', secondary: '#0b6e4f', accent: '#f4b400', neutral: '#e9f2df', background: '#f5f9ee', text: '#0f2419' },
    typography: {
      displayFont: 'Young Serif',
      bodyFont: 'Karla',
      scale: '14 / 16 / 18 / 22 / 30 / 42 / 64',
      lineHeights: 'Display 1.08, body 1.62',
      letterSpacing: 'Display -0.015em; labels 0.06em uppercase',
    },
    components: {
      primary: 'Solid #2f9e44, warm-white text, 999px pill, padding 12px 26px',
      secondary: '1px #0b6e4f border on transparent, #0b6e4f text',
      tertiary: 'Leaf-green text link with a → and a soft underline',
      radius: '999px pills, 18px cards — arched, never sharp',
      hover: 'Buttons lift 2px and deepen 8%, 200ms ease-out',
      cards: 'Warm-white surfaces, 18px radius, 1px rgba(11,110,79,.14) border, 24px padding',
      forms: '44px inputs, 14px radius, focus ring 3px #2f9e44/25%',
      navigation: 'Sticky translucent bar over a sunrise gradient',
      modals: '18px radius, 40% green-tinted scrim, scale-in 0.97→1',
    },
    accent: '#2f9e44',
    motif: 'wave-section',
    layout: 'hero-cards',
    useCases: ['Energy', 'Architecture', 'Nonprofit'],
    signatureCss: `.dv-hero { background: radial-gradient(48em 20em at 20% 0%, #f4b40022, transparent 70%), radial-gradient(40em 18em at 85% 20%, #2f9e4422, transparent 72%); }
.dv-card { background: #fffdf8; }
.dv-hero h1 em { color: #0b6e4f; }
.dv-btn-primary { border-radius: 999px; }`,
    author: 'Priya Raman',
    createdAt: '2026-09-27',
    popularity: 88,
    trending: true,
  },
  {
    id: 'quantum-lab',
    name: 'Quantum Lab',
    category: 'Professional',
    tags: ['research', 'physics', 'science', 'data', 'instrument'],
    description: 'Instrument readouts for very small things.',
    designPhilosophy:
      'A physics lab does not decorate. Quantum Lab is a control surface: cool violet instrumentation, cyan for live channels, and type that never gets in the way of a number. It assumes the reader is smart and the monitor is good. For research platforms, ML tooling, and any dashboard where precision is the brand.',
    colors: { primary: '#5b6cff', secondary: '#2b2f6b', accent: '#22d3ee', neutral: '#e7e9fb', background: '#f4f5ff', text: '#0c1030' },
    typography: {
      displayFont: 'Space Grotesk',
      bodyFont: 'IBM Plex Sans',
      scale: '12 / 14 / 16 / 18 / 24 / 32 / 48',
      lineHeights: 'Display 1.12, body 1.6, labels 1.2',
      letterSpacing: 'Labels 0.1em uppercase; figures 0 with tabular-nums',
    },
    components: {
      primary: 'Solid #5b6cff, white text, 6px radius, padding 11px 20px',
      secondary: '1px #c3c8f5 border, transparent, #0c1030 text',
      tertiary: 'Cyan text link with an ↗ for external datasets',
      radius: '6px controls, 10px panels — instrument-tight',
      hover: 'Border brightens to cyan, 120ms linear',
      cards: 'White panels, 1px #dfe2fb border, 10px radius, 20px padding',
      forms: 'Inputs 42px, mono placeholder, cyan focus ring 2px',
      navigation: 'Left rail with active-channel indicator and a hairline rule',
      modals: 'Panel sheet, title row with a close ✕, hairline sections',
    },
    accent: '#5b6cff',
    motif: 'pixel-grid',
    layout: 'dashboard',
    useCases: ['AI/ML', 'Data & Analytics', 'Education'],
    signatureCss: `.dv-hero { background-image: radial-gradient(#5b6cff22 1px, transparent 1px); background-size: 20px 20px; }
.dv-card { background: #ffffff; }
.dv-hero h1 em { color: #22d3ee; }
.dv-stat strong { font-variant-numeric: tabular-nums; }`,
    author: 'Dr. Malik Ferreira',
    createdAt: '2026-09-27',
    popularity: 84,
  },
  {
    id: 'terrazzo-cafe',
    name: 'Terrazzo Cafe',
    category: 'Playful',
    tags: ['terrazzo', 'speckle', 'cafe', 'warm', 'friendly'],
    description: 'Speckled surfaces with a friendly counter.',
    designPhilosophy:
      'Terrazzo is the friendliest material in architecture: a hundred scraps made precious. This system treats a menu the same way — many small things, arranged with care. Warm plaster background, confetti-fleck accents, and rounded chunky type that feels hand-set. For cafes, delis, and independent retail.',
    colors: { primary: '#d94f7a', secondary: '#2f9e9e', accent: '#f2c14e', neutral: '#f6efe6', background: '#fdf7f0', text: '#2a2320' },
    typography: {
      displayFont: 'Baloo 2',
      bodyFont: 'Nunito',
      scale: '14 / 16 / 18 / 22 / 28 / 36 / 52',
      lineHeights: 'Display 1.08, body 1.66',
      letterSpacing: 'Display -0.01em; labels 0.05em uppercase',
    },
    components: {
      primary: 'Solid #d94f7a, white text, 999px pill, padding 12px 24px, weight 700',
      secondary: '2px #2f9e9e border, transparent, teal text',
      tertiary: 'Rose text link with a doubled → →',
      radius: '999px pills, 16px cards — soft and chunky',
      hover: 'Scale 1.03 and deepen 6%, 160ms ease-out',
      cards: 'Warm-white cards, 16px radius, 2px dashed #2f9e9e22 border, 22px padding',
      forms: '46px inputs, 999px pill, focus ring 3px #d94f7a/25%',
      navigation: 'Pill navigation floating over the counter',
      modals: '20px radius, soft scrim, pop-in 0.96→1',
    },
    accent: '#d94f7a',
    motif: 'corner-brackets',
    layout: 'catalog',
    useCases: ['Coffee Shop', 'Restaurant', 'Marketplace'],
    signatureCss: `.dv-stage { background-image: radial-gradient(#d94f7a1f 2px, transparent 2px), radial-gradient(#2f9e9e1f 2px, transparent 2px); background-size: 34px 34px, 46px 46px; background-position: 0 0, 12px 18px; }
.dv-card { background: #fffdfa; }
.dv-hero h1 em { color: #2f9e9e; }`,
    author: 'Rosa Bembé',
    createdAt: '2026-09-27',
    popularity: 82,
  },
  {
    id: 'noir-dossier',
    name: 'Noir Dossier',
    category: 'Retro',
    tags: ['noir', 'detective', 'typewriter', 'manila', 'case-file'],
    description: 'A case file, typed twice and filed once.',
    designPhilosophy:
      'The case file is the most atmospheric document in fiction: manila, carbon, red string. Noir Dossier builds a reading experience out of it — typewriter display type, stamped labels, and the confidence that comes from a period where every word cost paper. For true-crime publishing, archives, and narrative journalism.',
    colors: { primary: '#33261c', secondary: '#5a5348', accent: '#a8352a', neutral: '#e7dcc3', background: '#efe6d0', text: '#14120f' },
    typography: {
      displayFont: 'Courier Prime',
      bodyFont: 'Spectral',
      scale: '13 / 14 / 16 / 18 / 24 / 32 / 44',
      lineHeights: 'Display 1.2, body 1.7',
      letterSpacing: 'Labels 0.18em uppercase; body 0',
    },
    components: {
      primary: 'Solid #33261c, manila text, 0 radius, uppercase, padding 12px 22px',
      secondary: '2px #33261c border, transparent, ink text',
      tertiary: 'Red underlined link, as if circled',
      radius: '0 everywhere — paper has no corners to round',
      hover: 'Background darkens one step, 120ms linear',
      cards: 'Manila files, 0 radius, 1px #33261c33 border, 26px padding, typed rules',
      forms: 'Underlined fields, no boxes, red focus caret',
      navigation: 'Typed masthead bar with a rule beneath',
      modals: 'Dossier sheet, 0 radius, stamped header',
    },
    accent: '#a8352a',
    motif: 'mono-labels',
    layout: 'magazine',
    useCases: ['Publishing', 'Film & TV', 'Legal'],
    signatureCss: `.dv-stage { background: #efe6d0; }
.dv-card { background: #f4ecd8; }
.dv-hero h1 { font-family: 'Courier Prime', monospace; }
.dv-hero h1 em { color: #a8352a; font-style: normal; text-decoration: underline; }
.dv-kicker { color: #a8352a; }`,
    author: 'Hal Marchetti',
    createdAt: '2026-09-27',
    popularity: 79,
  },
  {
    id: 'op-art-aperture',
    name: 'Op Art Aperture',
    category: 'Creative',
    tags: ['op-art', 'optical', 'monochrome', 'illusion', 'graphic'],
    description: 'Your eyes move before your mind does.',
    designPhilosophy:
      'Optical art is interaction design for the retina. Op Art Aperture strips the page to black, white, and one alarm red, then uses scale and outline to make the layout itself vibrate. Nothing is decorative; every line is doing perceptual work. For galleries, posters, and studios that would rather be remembered than liked.',
    colors: { primary: '#111111', secondary: '#eef2f7', accent: '#4338ca', neutral: '#e9edf3', background: '#fbfcfe', text: '#08090c' },
    typography: {
      displayFont: 'Archivo Black',
      bodyFont: 'Archivo',
      scale: '13 / 15 / 17 / 20 / 26 / 34 / 48 / 72',
      lineHeights: 'Display 0.94, body 1.7',
      letterSpacing: 'Display -0.04em; labels 0.22em uppercase',
    },
    components: {
      primary: 'Outlined 2px #111 on transparent, black text, 0 radius',
      secondary: 'Solid #111, white text',
      tertiary: 'Red text link with a hard underline',
      radius: '0 everywhere',
      hover: 'Inverts black↔white instantly, 90ms linear',
      cards: 'White plates, 0 radius, 2px black border, 28px padding',
      forms: 'Boxed inputs, 0 radius, 2px black border, red caret',
      navigation: 'Thin black bar with letterspaced uppercase links',
      modals: 'Full-bleed plate with a 2px black frame',
    },
    accent: '#4338ca',
    motif: 'outline-type',
    layout: 'poster',
    useCases: ['Art Gallery', 'Portfolio', 'Agency'],
    signatureCss: `.dv-hero h1 { -webkit-text-stroke-width: 2px; }
.dv-section { border-top: 2px solid #111; }
.dv-card { border-width: 2px; }
.dv-btn-primary:hover { background: #111; color: #fff; }`,
    author: 'Ines Vogel',
    createdAt: '2026-09-27',
    popularity: 86,
    trending: true,
  },
  {
    id: 'vhs-rental',
    name: 'VHS Rental',
    category: 'Retro',
    tags: ['vhs', 'analog', 'video-store', 'neon', 'tracking'],
    description: 'Be kind. Rewind. Ship it.',
    designPhilosophy:
      'The video store was a social recommendation engine with carpet. VHS Rental romanticises the physical tape: CRT scanlines, tracking-error colour, and PLAY ► affordances. Loud enough to be fun, structured enough to browse. For streaming catalogs, film archives, and retro gaming.',
    colors: { primary: '#7c3aed', secondary: '#22d3ee', accent: '#f472b6', neutral: '#1a1329', background: '#0d0a1a', text: '#f1ecff' },
    typography: {
      displayFont: 'VT323',
      bodyFont: 'Space Mono',
      scale: '14 / 16 / 18 / 22 / 28 / 38 / 56',
      lineHeights: 'Display 1.1, body 1.6',
      letterSpacing: 'Labels 0.16em uppercase; display 0.02em',
    },
    components: {
      primary: 'Solid #7c3aed, white text, 6px radius, glow 0 0 20px #7c3aed66',
      secondary: '1px #22d3ee border, transparent, cyan text',
      tertiary: 'Bubblegum text link with ▶',
      radius: '6px controls, 12px cards',
      hover: 'Glow intensifies 30%, 140ms ease-out',
      cards: '#171027 panels, 1px #3a2a5c border, 12px radius, 20px padding',
      forms: 'Dark inputs, mono text, cyan focus ring 2px',
      navigation: 'Top bar with a REC dot and tracking-error hairline',
      modals: 'Tape-case sheet with slot labels',
    },
    accent: '#7c3aed',
    motif: 'scanlines',
    layout: 'hero-cards',
    useCases: ['Streaming', 'Film & TV', 'Gaming'],
    signatureCss: `.dv-card { background: #171027; }
.dv-hero h1 { font-family: 'VT323', monospace; }
.dv-hero h1 em { color: #22d3ee; font-style: normal; }
.dv-kicker::after { content: ' ● REC'; color: #f472b6; }`,
    author: 'Dez Kowalski',
    createdAt: '2026-09-27',
    popularity: 87,
    trending: true,
  },
  {
    id: 'riso-atelier',
    name: 'Riso Atelier',
    category: 'Creative',
    tags: ['risograph', 'print', 'duotone', 'studio', 'ink'],
    description: 'Two inks, one press, endless editions.',
    designPhilosophy:
      'Risograph forces discipline: you get two inks and a misregistration you learn to love. Riso Atelier is that constraint as a system — loud flat colour, duotone imagery, and type set with a printmaker&rsquo;s confidence. For studios, indie publishers, and anyone who still smells paper.',
    colors: { primary: '#ff4f5a', secondary: '#2643c8', accent: '#ffd23f', neutral: '#efe6d6', background: '#f8f3e8', text: '#15120f' },
    typography: {
      displayFont: 'Archivo Black',
      bodyFont: 'Familjen Grotesk',
      scale: '13 / 15 / 17 / 21 / 27 / 36 / 52',
      lineHeights: 'Display 1.0, body 1.62',
      letterSpacing: 'Display -0.02em; labels 0.14em uppercase',
    },
    components: {
      primary: 'Solid #ff4f5a, paper text, 2px radius, 3px 3px 0 #2643c8 offset shadow',
      secondary: '2px #2643c8 border, transparent, blue text',
      tertiary: 'Blue underlined link with a plate mark',
      radius: '2px controls, 4px cards — print-sharp',
      hover: 'Offset shadow grows to 5px, 140ms ease-out',
      cards: 'Paper cards, 4px radius, 2px #2643c8 border, 24px padding',
      forms: 'Boxed inputs, 2px blue border, marigold focus fill',
      navigation: 'Press bar with a registration cross',
      modals: 'Edition sheet with plate numbers',
    },
    accent: '#ff4f5a',
    motif: 'duotone-media',
    layout: 'asymmetric',
    useCases: ['Agency', 'Portfolio', 'Publishing'],
    signatureCss: `.dv-card { background: #fffdf6; box-shadow: 3px 3px 0 #2643c822; }
.dv-hero h1 em { color: #2643c8; }
.dv-media { background: linear-gradient(135deg, #ff4f5a, #2643c8); }
.dv-kicker { transform: rotate(-0.5deg); }`,
    author: 'Nico Basile',
    createdAt: '2026-09-27',
    popularity: 83,
  },
  {
    id: 'circuit-foundry',
    name: 'Circuit Foundry',
    category: 'Professional',
    tags: ['pcb', 'hardware', 'manufacturing', 'copper', 'fab'],
    description: 'Fabrication data, laid out like a board.',
    designPhilosophy:
      'A PCB is a document: silkscreen labels, copper traces, drill hits. Circuit Foundry treats a hardware product page the same way — dense, labelled, and traceable. Solder-mask green over dark substrate, copper as the accent, and monospace everywhere a part number lives. For hardware, supply chain, and manufacturing.',
    colors: { primary: '#1b8f4b', secondary: '#0b5d33', accent: '#c98a3a', neutral: '#0f1c16', background: '#0a120e', text: '#dff3e6' },
    typography: {
      displayFont: 'Chakra Petch',
      bodyFont: 'IBM Plex Mono',
      scale: '12 / 14 / 16 / 18 / 24 / 30 / 44',
      lineHeights: 'Display 1.16, body 1.6',
      letterSpacing: 'Labels 0.12em uppercase; part numbers 0',
    },
    components: {
      primary: 'Solid #1b8f4b, board-black text, 2px radius, uppercase mono label',
      secondary: '1px #c98a3a border, transparent, copper text',
      tertiary: 'Copper text link with a → and a pad mark',
      radius: '2px controls, 4px panels — fab-drawn',
      hover: 'Trace brightens to copper, 110ms linear',
      cards: '#0e1812 panels, 1px #1d3327 border, 4px radius, 20px padding',
      forms: 'Dark inputs, mono, green focus ring 2px',
      navigation: 'Silkscreen bar with a revision tag',
      modals: 'Fab sheet with revision stamp',
    },
    accent: '#c98a3a',
    motif: 'tape-labels',
    layout: 'bento',
    useCases: ['Manufacturing', 'Developer Tools', 'Energy'],
    signatureCss: `.dv-card { background: #0e1812; }
.dv-hero h1 { font-family: 'Chakra Petch', sans-serif; }
.dv-hero h1 em { color: #c98a3a; font-style: normal; }
.dv-section { border-top: 1px solid #1d3327; }
.dv-kicker { color: #c98a3a; }`,
    author: 'Tomas Lindqvist',
    createdAt: '2026-09-27',
    popularity: 77,
  },
  {
    id: 'paper-craft-club',
    name: 'Paper Craft Club',
    category: 'Playful',
    tags: ['paper', 'collage', 'handmade', 'kids', 'scissors'],
    description: 'Cut, fold, and glue the interface.',
    designPhilosophy:
      'Paper craft mistakes are cheap, so paper craft children are brave. This system borrows that: layered shapes, visible glue-tabs, and a palette that looks like construction paper. It is deliberately imperfect, because perfect is intimidating to a seven-year-old. For kids&rsquo; brands, classrooms, and workshops.',
    colors: { primary: '#ff7a59', secondary: '#3aa6b9', accent: '#ffd166', neutral: '#fdf2e3', background: '#fff9f0', text: '#2b2118' },
    typography: {
      displayFont: 'Amatic SC',
      bodyFont: 'Patrick Hand',
      scale: '16 / 18 / 20 / 24 / 30 / 40 / 60',
      lineHeights: 'Display 1.0, body 1.7',
      letterSpacing: 'Display 0.01em; labels 0.04em',
    },
    components: {
      primary: 'Solid #ff7a59, white text, 14px radius, 2px #d95f3d border, glued shadow',
      secondary: '2px #3aa6b9 border, transparent, teal text',
      tertiary: 'Tangerine underlined link with a ✂',
      radius: '14px controls, 20px cards — soft cut paper',
      hover: 'Rotate 1.5° and lift 3px, 180ms ease-out',
      cards: 'Paper cards, 20px radius, 2px dashed #3aa6b955 border, 24px padding',
      forms: 'Big 52px inputs, 16px radius, crayon-thick focus ring',
      navigation: 'Washi-tape nav strip',
      modals: 'Layered card, tabs at the corners',
    },
    accent: '#ff7a59',
    motif: 'corner-brackets',
    layout: 'centered',
    useCases: ['Kids', 'Education', 'Events'],
    signatureCss: `.dv-card { background: #fffdf7; box-shadow: 0 6px 0 #ffd16655; }
.dv-hero h1 em { color: #3aa6b9; }
.dv-btn-primary { box-shadow: 0 4px 0 #d95f3d; }
.dv-kicker { color: #ff7a59; }`,
    author: 'Mia Delgado',
    createdAt: '2026-09-27',
    popularity: 80,
  },
  {
    id: 'glacier-spa',
    name: 'Glacier Spa',
    category: 'Luxury',
    tags: ['spa', 'glacial', 'calm', 'wellness', 'mineral'],
    description: 'Cold water, warm light, nothing else.',
    designPhilosophy:
      'A good spa removes things. Glacier Spa is subtraction as luxury: glacial blues, mineral greys, and a single warm gold that appears once per screen like a lantern in a cold room. Wide spacing, thin type, and a spotlight that never rushes. For wellness retreats, premium hotels, and clinics.',
    colors: { primary: '#7fb2c9', secondary: '#33586b', accent: '#d9c48a', neutral: '#e8f1f4', background: '#f4fafc', text: '#10242c' },
    typography: {
      displayFont: 'Marcellus',
      bodyFont: 'Jost',
      scale: '14 / 16 / 18 / 22 / 30 / 40 / 58',
      lineHeights: 'Display 1.14, body 1.72',
      letterSpacing: 'Display 0.01em; labels 0.18em uppercase',
    },
    components: {
      primary: 'Solid #33586b, ice text, 999px pill, padding 13px 28px',
      secondary: '1px #7fb2c9 border, transparent, fjord text',
      tertiary: 'Gold text link with a slow underline',
      radius: '999px pills, 20px cards — soft, water-worn',
      hover: 'Lift 2px, gold underline draws, 240ms ease-out',
      cards: 'Ice-white cards, 20px radius, 1px #7fb2c966 border, 28px padding',
      forms: '46px inputs, 999px pill, 3px #7fb2c9/30% focus ring',
      navigation: 'Minimal sticky bar, generous links, no shadow',
      modals: '20px radius, 30% fog scrim, slow 280ms scale-in',
    },
    accent: '#7fb2c9',
    motif: 'gradient-hero',
    layout: 'spotlight',
    useCases: ['Wellness', 'Hotel', 'Beauty & Spa'],
    signatureCss: `.dv-hero h1 { font-family: 'Marcellus', serif; }
.dv-hero h1 em { color: #33586b; font-style: normal; }
.dv-card { background: #ffffff; }
.dv-stat strong { font-family: 'Marcellus', serif; }`,
    author: 'Sofia Bergström',
    createdAt: '2026-09-27',
    popularity: 81,
  },
  {
    id: 'cosmic-observatory',
    name: 'Cosmic Observatory',
    category: 'Creative',
    tags: ['astronomy', 'cosmos', 'dark', 'science', 'wonder'],
    description: 'Point the telescope, forget the pixel.',
    designPhilosophy:
      'Space content fails when it feels like a dashboard. Cosmic Observatory treats the page as night sky: deep field-black, star-chart gold, and labels that read like coordinates. It is dark without being a gamer rig, and it lets images be enormous. For astronomy, science museums, and premium data storytelling.',
    colors: { primary: '#8b7cf6', secondary: '#1b1a3a', accent: '#f4d35e', neutral: '#12112b', background: '#08071a', text: '#eae7ff' },
    typography: {
      displayFont: 'Outfit',
      bodyFont: 'IBM Plex Sans',
      scale: '13 / 15 / 17 / 20 / 27 / 36 / 52 / 76',
      lineHeights: 'Display 1.04, body 1.68',
      letterSpacing: 'Display -0.02em; coordinates 0.14em uppercase',
    },
    components: {
      primary: 'Solid #8b7cf6, field text, 10px radius, glow 0 0 26px #8b7cf655',
      secondary: '1px #f4d35e border, transparent, gold text',
      tertiary: 'Gold coordinate link with a ⟶',
      radius: '10px controls, 18px cards',
      hover: 'Glow +25% and scale 1.015, 200ms ease-out',
      cards: '#100f26 panels, 1px #2a2850 border, 18px radius, 26px padding',
      forms: 'Dark inputs, coordinate placeholder, violet focus ring 2px',
      navigation: 'Transparent bar that solidifies on scroll',
      modals: 'Star-chart sheet with corner coordinates',
    },
    accent: '#8b7cf6',
    motif: 'glow-pulse',
    layout: 'full-bleed',
    useCases: ['Education', 'Data & Analytics', 'Streaming'],
    signatureCss: `.dv-stage { background: radial-gradient(60em 40em at 70% -10%, #8b7cf622, transparent 60%), #08071a; }
.dv-card { background: #100f26; }
.dv-hero h1 em { color: #f4d35e; font-style: normal; }
.dv-kicker { font-family: 'IBM Plex Mono', monospace; }`,
    author: 'Dr. Andrea Sun',
    createdAt: '2026-09-27',
    popularity: 85,
    trending: true,
  },
  {
    id: 'weather-bureau',
    name: 'Weather Bureau',
    category: 'Professional',
    tags: ['weather', 'government', 'forecast', 'data', 'public'],
    description: 'Public weather data, legible to everyone.',
    designPhilosophy:
      'A weather forecast is public infrastructure: it must be fast, legible, and honest about uncertainty. Weather Bureau is a civil-service design — high-contrast, no flourish, and a Swiss grid that lets numbers be numbers. For government, agriculture, and logistics.',
    colors: { primary: '#0b63c5', secondary: '#0f7a8c', accent: '#f4a300', neutral: '#e6eef7', background: '#f5f9fd', text: '#0d1b2a' },
    typography: {
      displayFont: 'Archivo',
      bodyFont: 'IBM Plex Sans',
      scale: '12 / 14 / 16 / 18 / 24 / 30 / 42',
      lineHeights: 'Display 1.14, body 1.6',
      letterSpacing: 'Labels 0.1em uppercase; figures 0 tabular-nums',
    },
    components: {
      primary: 'Solid #0b63c5, white text, 4px radius, padding 11px 20px',
      secondary: '1px #0b63c5 border, transparent, blue text',
      tertiary: 'Blue underlined link, high contrast',
      radius: '4px controls, 8px panels — civic-tight',
      hover: 'Background darkens 8%, 130ms linear',
      cards: 'White panels, 1px #cfdceb border, 8px radius, 20px padding',
      forms: '44px inputs, 4px radius, 3px blue focus ring',
      navigation: 'Official bar with a grid rule and section index',
      modals: 'Document sheet with a numbered heading',
    },
    accent: '#0b63c5',
    motif: 'scanlines',
    layout: 'dashboard',
    useCases: ['Government', 'Data & Analytics', 'Agriculture'],
    signatureCss: `.dv-hero h1 { text-transform: none; }
.dv-hero h1 em { color: #0b63c5; }
.dv-card { background: #ffffff; }
.dv-stat strong { font-variant-numeric: tabular-nums; }`,
    author: 'Grace Oyelaran',
    createdAt: '2026-09-27',
    popularity: 75,
  },
  {
    id: 'pulp-anthology',
    name: 'Pulp Anthology',
    category: 'Retro',
    tags: ['pulp', 'paperback', 'anthology', 'fiction', 'cover'],
    description: 'Twelve stories, one cracked spine.',
    designPhilosophy:
      'Pulp covers promised more than they delivered, gloriously. Pulp Anthology is that promise as a reading experience: slab headlines, cheap-and-proud colour, and borders that frame each story like a cover. It is loud, warm, and unembarrassed about entertainment. For publishers, fiction platforms, and archive collections.',
    colors: { primary: '#c0392b', secondary: '#2f2a26', accent: '#e0a800', neutral: '#ece0c8', background: '#f3e9d2', text: '#1d1a16' },
    typography: {
      displayFont: 'Alfa Slab One',
      bodyFont: 'Bitter',
      scale: '14 / 16 / 18 / 22 / 30 / 40 / 58',
      lineHeights: 'Display 1.02, body 1.7',
      letterSpacing: 'Display -0.01em; labels 0.12em uppercase',
    },
    components: {
      primary: 'Solid #c0392b, cream text, 2px radius, drop shadow 2px 2px 0 #1d1a16',
      secondary: '2px #1d1a16 border, transparent, ink text',
      tertiary: 'Red underlined link with a ◆',
      radius: '2px controls, 6px covers',
      hover: 'Shadow grows and red deepens, 150ms ease-out',
      cards: 'Cover cards, 6px radius, 2px #1d1a16 border, 22px padding',
      forms: 'Boxed inputs, 2px ink border, gold focus fill',
      navigation: 'Masthead bar with double rule',
      modals: 'Cover panel with a spine stripe',
    },
    accent: '#c0392b',
    motif: 'editorial-columns',
    layout: 'editorial',
    useCases: ['Publishing', 'News', 'Film & TV'],
    signatureCss: `.dv-card { background: #fdf7e6; box-shadow: 3px 3px 0 #1d1a16; }
.dv-hero h1 { font-family: 'Alfa Slab One', serif; }
.dv-hero h1 em { color: #c0392b; font-style: normal; }
.dv-card:first-child { border-color: #c0392b; }`,
    author: 'Frank Delacroix',
    createdAt: '2026-09-27',
    popularity: 78,
  },
  {
    id: 'bakery-window',
    name: 'Bakery Window',
    category: 'Organic',
    tags: ['bakery', 'artisan', 'bread', 'warm', 'local'],
    description: 'What came out of the oven this morning.',
    designPhilosophy:
      'A bakery window sells by honesty: today&rsquo;s loaves, today&rsquo;s prices, sold until gone. Bakery Window is warm, earthy, and slightly rustic — crust browns, wheat greens, and a list that changes daily. For artisan food, farm shops, and local grocery.',
    colors: { primary: '#9c5a2c', secondary: '#5f7a4a', accent: '#d9a441', neutral: '#f0e3cf', background: '#fbf4e8', text: '#2c2015' },
    typography: {
      displayFont: 'Young Serif',
      bodyFont: 'Karla',
      scale: '14 / 16 / 18 / 22 / 28 / 38 / 54',
      lineHeights: 'Display 1.1, body 1.66',
      letterSpacing: 'Display -0.01em; labels 0.06em uppercase',
    },
    components: {
      primary: 'Solid #9c5a2c, flour text, 12px radius, padding 12px 24px',
      secondary: '1px #5f7a4a border, transparent, wheat text',
      tertiary: 'Honey text link with a ✿',
      radius: '12px controls, 18px cards — round and warm',
      hover: 'Lift 2px and deepen, 200ms ease-out',
      cards: 'Flour cards, 18px radius, 1px #d9a44155 border, 24px padding',
      forms: '46px inputs, 12px radius, honey focus ring 3px',
      navigation: 'Chalkboard-style bar with a hand-written feel',
      modals: 'Paper-bag sheet with a folded corner',
    },
    accent: '#9c5a2c',
    motif: 'leaf-divider',
    layout: 'catalog',
    useCases: ['Restaurant', 'Coffee Shop', 'Grocery'],
    signatureCss: `.dv-card { background: #fffdf7; }
.dv-hero h1 em { color: #5f7a4a; }
.dv-kicker { color: #9c5a2c; }
.dv-stat strong { font-family: 'Young Serif', serif; }`,
    author: 'Ola Kowalczyk',
    createdAt: '2026-09-27',
    popularity: 76,
  },
  {
    id: 'espionage-console',
    name: 'Espionage Console',
    category: 'Professional',
    tags: ['security', 'surveillance', 'terminal', 'amber', 'classified'],
    description: 'Eyes only, amber on black.',
    designPhilosophy:
      'Security tooling is read under pressure. Espionage Console is a war-room terminal: amber phosphor on deep olive-black, red for active threats only, and monospace everywhere identification matters. It assumes a competent operator and refuses to be pretty at the cost of legible. For cybersecurity, government, and infrastructure.',
    colors: { primary: '#e0a41c', secondary: '#2b2f2a', accent: '#d64545', neutral: '#1f221e', background: '#0f1210', text: '#e8ecdf' },
    typography: {
      displayFont: 'Oswald',
      bodyFont: 'Space Mono',
      scale: '12 / 14 / 16 / 18 / 23 / 30 / 42',
      lineHeights: 'Display 1.16, body 1.6',
      letterSpacing: 'Display 0.02em; labels 0.14em uppercase',
    },
    components: {
      primary: 'Solid #e0a41c, olive-black text, 2px radius, uppercase mono',
      secondary: '1px #d64545 border, transparent, red text',
      tertiary: 'Amber link with a › and a classification dot',
      radius: '2px controls, 4px panels — console-sharp',
      hover: 'Amber brightens, 110ms linear',
      cards: '#141813 panels, 1px #e0a41c33 border, 4px radius, 20px padding',
      forms: 'Dark inputs, mono, amber focus ring 2px',
      navigation: 'Console bar with clock and clearance level',
      modals: 'Classified sheet with stamped header',
    },
    accent: '#e0a41c',
    motif: 'scanlines',
    layout: 'bento',
    useCases: ['Cybersecurity', 'Government', 'DevOps & Cloud'],
    signatureCss: `.dv-card { background: #141813; }
.dv-hero h1 { font-family: 'Oswald', sans-serif; text-transform: uppercase; }
.dv-hero h1 em { color: #e0a41c; font-style: normal; }
.dv-kicker { color: #d64545; }
.dv-section { border-top: 1px solid #e0a41c22; }`,
    author: 'Yusuf Demir',
    createdAt: '2026-09-27',
    popularity: 82,
  },
  {
    id: 'marble-atelier',
    name: 'Marble Atelier',
    category: 'Luxury',
    tags: ['marble', 'classical', 'stone', 'architecture', 'atelier'],
    description: 'Classical proportion, contemporary nerve.',
    designPhilosophy:
      'Classical architecture is a two-thousand-year argument about proportion. Marble Atelier takes the argument seriously and the ornament out: stone palettes, engraved letterforms, and outlines instead of fills. It is austere, confident, and a little cold — which is the point. For architecture studios, galleries, and premium property.',
    colors: { primary: '#8d8577', secondary: '#2f2b26', accent: '#b08d57', neutral: '#eae6de', background: '#f6f4ef', text: '#1a1713' },
    typography: {
      displayFont: 'Cormorant Garamond',
      bodyFont: 'Livvic',
      scale: '14 / 16 / 18 / 22 / 30 / 42 / 64',
      lineHeights: 'Display 1.08, body 1.7',
      letterSpacing: 'Display 0.02em; labels 0.2em uppercase',
    },
    components: {
      primary: 'Outlined 1.5px #2f2b26, transparent, ink text, 0 radius',
      secondary: '1px #b08d57 border, gold text',
      tertiary: 'Gold letter-spaced link with a drawn rule',
      radius: '0 everywhere — carved stone',
      hover: 'Ink fills the outline, 200ms ease-out',
      cards: 'Stone plates, 0 radius, 1px #1a171322 border, 30px padding',
      forms: 'Underlined fields, gold caret, no boxes',
      navigation: 'Colonnade bar with engraved wordmark',
      modals: 'Plaque sheet with an engraved border',
    },
    accent: '#b08d57',
    motif: 'paper-cut',
    layout: 'poster',
    useCases: ['Architecture', 'Art Gallery', 'Real Estate'],
    signatureCss: `.dv-hero h1 { font-family: 'Cormorant Garamond', serif; }
.dv-hero h1 em { -webkit-text-stroke-color: #b08d57; }
.dv-card { background: #faf9f5; }
.dv-section { border-top: 1px solid #1a171320; }`,
    author: 'Lorenzo Bianchi',
    createdAt: '2026-09-27',
    popularity: 80,
  },
]
