import type { DesignSystem } from '../types'
import { row } from './build'

/**
 * Wave 16 — Civic Paper: permits, registers, tribunals and the printed
 * machinery of public life.
 * Row format: id, name, category, tags, useCases, hero, description,
 * philosophy, colors, display, body, motif, layout, radius, depth,
 * accentRole, author.
 */

export const wave16Designs: DesignSystem[] = [
  row('permit-office', 'Permit Office', 'Minimalism', 'permits applications counter queue', 'Government|Construction|Real Estate', 'One form, *twelve weeks.*', 'A counter that turns applications into decisions.', 'A permit office is judged by how little it makes people guess: which form, which fee, which week the answer arrives. The design is a checklist with a queue behind it — status in plain words, and one accent for anything waiting on the applicant.', '#2c5199 #9db3c4 #e07a5f #dae2e8 #f5f8fa #101c24', 'Silkscreen', 'Jost', 'underline-accent', 'docs', 0, 'flat', 'applications waiting on the applicant', 'Priya Balan'),
  row('registry-archives', 'Registry Archives', 'Minimalism', 'registry births marriages records', 'Government|Legal|Health', 'Filed once, *kept forever.*', 'Registers that outlive the people in them.', 'A registry is a promise about permanence: an entry written once, amended by rule, and retrievable decades later. The design is clerical and warm — ledger lines, reference formats, and one deep red for an amendment that changes an original.', '#703d21 #c4b39a #7a1f38 #e6dfd2 #faf7f0 #231a12', 'Cormorant Garamond', 'Archivo', 'double-rule', 'receipt', 2, 'hairline', 'entries awaiting an amendment', 'Margaret Ellery'),
  row('land-titles', 'Land Titles', 'Luxury', 'titles deeds ownership parcels registry', 'Real Estate|Legal|Banking', 'A parcel, *a name, a date.*', 'Ownership recorded as a chain of promise.', 'A title register is history in tabular form: parcels, transfers, charges, and a warranty that the state will stand behind. The design is formal and quiet — deep green, a seal for anything guaranteed, and type that never jokes about ownership.', '#29ae5c #9ec4b0 #d4af37 #d9e6de #f4faf7 #0b1c15', 'Gloock', 'Spectral', 'stamp-seal', 'docs', 4, 'soft', 'parcels with a charge registered', 'Gerald Whitby'),
  row('customs-post', 'Customs Post', 'Brutalism', 'customs border duty declarations goods', 'Government|Logistics|E-commerce', 'Declared, *dutied, released.*', 'A border desk for goods and paperwork.', 'A customs post is a decision queue with a warehouse attached: declarations read, values checked, and a release code that moves a lorry. The design is heavy and procedural — tariff tables, inspection flags, and one amber for a consignment held.', '#191a39 #8f9cba #e8b02b #d5dbe6 #f2f5fa #0b1220', 'Archivo', 'Be Vietnam Pro', 'ribbon-band', 'manifesto', 0, 'hard', 'consignments held for inspection', 'Grace Mwangi'),
  row('patent-office', 'Patent Office', 'Creative', 'patents inventions drawings filings', 'Legal|Design Tools|Startup', 'Drawn, *described, claimed.*', 'Inventions registered with a date and a diagram.', 'A patent is a drawing with legal force: figures numbered, claims written to be narrow, and a priority date that decides who owns the idea. The design is drafting-table blue — reference numerals, claim blocks, and one orange for a claim that will be contested.', '#8f39ad #a49ac4 #c2410c #e0dcec #f6f4fc #141024', 'Fraunces', 'Jost', 'blueprint-grid', 'split-scroll', 4, 'hairline', 'claims awaiting examination', 'Tobias Lund'),
  row('census-desk', 'Census Desk', 'Professional', 'census population households counting', 'Government|Data & Analytics|Community', 'Counted *once a decade.*', 'A national count, published in tables.', 'A census is the largest form ever posted and the most argued-over table ever printed: households counted, response rates watched, and a population published to the nearest thousand. The design is statistical and calm.', '#1e4967 #93a8bd #e07a5f #d8e1e8 #f2f7fa #0b1821', 'IBM Plex Sans', 'Archivo', 'big-stat-row', 'dashboard', 2, 'flat', 'areas below response target', 'Priya Balan'),
  row('court-clerk', 'Court Clerk', 'Minimalism', 'court clerk hearings listings files', 'Legal|Government|Community', 'Listed at *ten, called at ten.*', 'A listing office for a busy courthouse.', 'The clerk runs the day: cases listed, files pulled, and a courtroom that starts on time or does not start at all. The design is a cause list — room numbers, times, and one accent for a hearing that has been adjourned.', '#ba2c6b #b39aa4 #d4af37 #e6d8dd #faf4f6 #1f0f16', 'Source Sans 3', 'Lora', 'double-rule', 'catalog', 0, 'hairline', 'hearings adjourned, one listing each', 'Eamon Doyle'),
  row('licence-board', 'Licence Board', 'Professional', 'licences renewal inspections premises', 'Government|Restaurant|Marketplace', 'Renewed, *inspected, displayed.*', 'Licences for premises that serve the public.', 'A licence board is trust made inspectable: categories, conditions, renewal dates, and a register anyone may read. The design is administrative and plain — certificate numbers, inspection outcomes, and one blue for a licence currently suspended.', '#8b870e #d9c08a #1f5f8a #e8e0cc #f9f6ee #241d10', 'Karla', 'Jost', 'numbered-steps', 'docs', 2, 'hard', 'licences suspended, one premises each', 'Priya Balan'),
  row('notary-desk', 'Notary Desk', 'Luxury', 'notary deeds signatures witnessing', 'Legal|Banking|Real Estate', 'Signed *in front of a witness.*', 'A notary who certifies what happened in a room.', 'A notary is a witness with a register: identity checked, signature made, and an entry that proves the moment later. The design is quiet authority — seal marks, certificate wording, and a single green for a document properly executed.', '#3f1b12 #b39a86 #1f5f4a #e2d8cc #f8f4ee #1e150e', 'Marcellus', 'Lora', 'stamp-seal', 'receipt', 0, 'hairline', 'instruments awaiting a signature', 'Gerald Whitby'),
  row('planning-committee', 'Planning Committee', 'Professional', 'planning applications committee decisions', 'Government|Real Estate|Architecture', 'Approved, *refused, deferred.*', 'Applications decided in public, on the record.', 'A planning committee is local politics with drawings attached: officer reports, objections heard, and a vote that changes a street for fifty years. The design is procedural and even-handed — application numbers, decision codes, and no colour that takes a side.', '#25471f #a4c0aa #c2410c #dde8de #f5faf5 #101f14', 'Archivo Black', 'Jost', 'isometric-lattice', 'asymmetric', 2, 'hard', 'applications deferred, one plot each', 'Imogen Blake'),
  row('voter-roll', 'Voter Roll', 'Minimalism', 'voters roll polling districts register', 'Government|Community|Nonprofit', 'Every name *gets a polling card.*', 'The register that decides who may vote.', 'A voter roll is a list with constitutional weight: electors added, removals reviewed, and a polling district for every address. The design is a register — big legible names, district codes, and one yellow for a ward still canvassing.', '#0f1b4d #93a8bd #f2c400 #d6dfe8 #f2f6fa #0a1620', 'Bebas Neue', 'Archivo', 'swiss-grid', 'catalog', 0, 'flat', 'districts behind on canvassing', 'Eamon Doyle'),
  row('tax-returns', 'Tax Returns', 'Professional', 'tax returns filing deadlines allowances', 'Accounting|Banking|Government', 'File it *before midnight.*', 'A self-assessment system for a filing season.', 'Tax is a deadline with arithmetic: allowances applied, deadlines chased, and penalties published in advance so nobody can claim surprise. The design is a worksheet — tabular figures, one field per line, and a green for a return accepted.', '#3f0f4d #9a90b4 #22c55e #dcd9e8 #f5f4fb #121028', 'IBM Plex Sans', 'Merriweather', 'mono-labels', 'docs', 0, 'inset', 'returns overdue, one taxpayer each', 'Gerald Whitby'),
  row('census-enumerator', 'Census Enumerator', 'Professional', 'enumerator visits doorsteps households', 'Government|Community|Data & Analytics', 'Knock, ask, *write it down.*', 'Field staff who count households where they live.', 'An enumerator works a list of addresses with a clipboard and a phone: visits logged, refusals recorded, and households counted without judgement. The design is fieldwork — route numbers, visit states, and one accent for a household that needs a second call.', '#53938d #93bdc0 #e07a3a #d9e8e8 #f3fafa #0b1e20', 'Nunito', 'Outfit', 'tape-labels', 'field-notes', 8, 'soft', 'addresses needing a second visit', 'Grace Mwangi'),
  row('consular-desk', 'Consular Desk', 'Luxury', 'consulate visas citizens assistance', 'Government|Travel|Legal', 'The flag is *open today.*', 'A consulate that helps citizens abroad.', 'A consular desk handles the worst days of a good trip: documents lost, arrests made, and a queue of people who need a country to answer for them. The design is formal but human — case numbers, emergency lines, and one gold for the services that are free.', '#212c78 #93a2b4 #d4af37 #d8e0e8 #f4f7fa #0a141f', 'Gloock', 'Cormorant Garamond', 'double-rule', 'editorial', 2, 'soft', 'cases awaiting a consular decision', 'Constance Whitfield'),
  row('hansard', 'Hansard', 'Creative', 'hansard speeches debates transcript', 'Government|News|Publishing', 'Said in the house, *printed by morning.*', 'The verbatim record of a debate.', 'Hansard is transcription under a constitutional clock: speeches corrected only for accuracy, names spelled right, and an index that lets anyone find the sentence later. The design is a printed column — wide measure, marginal notes, and one accent for a division recorded.', '#a1904a #b3a68a #7a1f38 #e4dfcc #faf8ee #1f1a10', 'Source Sans 3', 'Spectral', 'editorial-columns', 'editorial', 0, 'hairline', 'divisions awaiting a written record', 'Constance Whitfield'),
  row('statute-book', 'Statute Book', 'Maximalism', 'statutes sections schedules law', 'Legal|Government|Publishing', 'Section, schedule, *proviso.*', 'Legislation that expects to be read closely.', 'A statute is a document designed to be argued with: numbered sections, definitions that narrow everything said before, and schedules that carry the exceptions. The design is heavy print — dense cross-references, one accent for a provision in force, and no decoration at all.', '#9e5414 #d9ab74 #1f3f66 #ecdcc4 #fdf6ea #20140a', 'Playfair Display', 'Cabin', 'quote-band', 'manifesto', 0, 'hard', 'provisions not yet in force', 'Gerald Whitby'),
  row('municipal-budget', 'Municipal Budget', 'Professional', 'budget council spending rates tax', 'Government|Accounting|Community', 'Spent here, *raised there.*', 'A town’s money, published before it is spent.', 'A municipal budget is a moral document disguised as a spreadsheet: what a council chooses to fund, what it defers, and the rate that pays for it. The design is transparent and comparable — service lines, variances, and one accent for anything over budget.', '#114b45 #93bda8 #e07a5f #d9e8e0 #f3faf6 #0b1e17', 'Inter', 'Hanken Grotesk', 'grain-overlay', 'dashboard', 4, 'flat', 'lines over budget, one service each', 'Priya Balan'),
  row('procurement-desk', 'Procurement Desk', 'Professional', 'tenders contracts suppliers bids', 'Government|Consulting|Manufacturing', 'Bought well, *audited later.*', 'Public buying, with every step recorded.', 'Procurement is trust purchased by process: specifications written, bids opened in public, and a contract that will be read again by an auditor. The design is a tender file — reference numbers, evaluation criteria, and one amber for a contract awarded without competition.', '#3c5486 #93a8bd #e8b02b #d6dfe8 #f2f6fa #0a1620', 'Manrope', 'Archivo', 'ledger-rules', 'docs', 2, 'flat', 'contracts going to single tender', 'Eamon Doyle'),
  row('ombudsman', 'Ombudsman', 'Minimalism', 'complaints ombudsman investigations redress', 'Government|Legal|Mental Health', 'Complained, *investigated, answered.*', 'An independent desk for complaints about power.', 'An ombudsman exists for the cases where a service failed and its own process will not admit it: complaints read, evidence gathered, and a recommendation published. The design is plain and serious — case references, findings, and one violet for a recommendation not yet accepted.', '#77218c #9a94b4 #f2b705 #dedaec #f6f5fc #131228', 'Sora', 'Inter', 'underline-accent', 'manifesto', 4, 'hairline', 'recommendations awaiting a reply', 'Margaret Ellery'),
  row('appeals-tribunal', 'Appeals Tribunal', 'Professional', 'appeals tribunal hearings decisions', 'Legal|Government|Mental Health', 'The decision *can be argued with.*', 'A tribunal where refusals are heard again.', 'A tribunal is designed for the moment after a no: grounds stated, evidence reheard, and a written decision that stands on its own. The design is hearing-first — bundle indexes, panel lists, and one accent for an appeal allowed.', '#754357 #a894a0 #1f5f8a #e0d8dc #f8f4f6 #1c1016', 'EB Garamond', 'Jost', 'quote-band', 'timeline', 0, 'hairline', 'appeals awaiting a panel', 'Eamon Doyle'),
  row('building-inspector', 'Building Inspector', 'Brutalism', 'inspection sites compliance notices building', 'Construction|Government|Real Estate', 'Inspected *at first fix.*', 'Site inspections that can stop a build.', 'An inspector sees the parts of a building that will never be visible again: footings, fire stops, and a notice served before the concrete goes in. The design is a site clipboard — inspection stages, defect lists, and one yellow for a stop notice.', '#d6d628 #d9c08a #1f3f66 #e6dcc4 #f8f4e8 #221a0c', 'Oswald', 'Jost', 'diagonal-bars', 'field-notes', 0, 'hard', 'sites with an open notice', 'Marek Dolny'),
  row('health-inspector', 'Health Inspector', 'Professional', 'inspection food hygiene kitchens ratings', 'Government|Restaurant|Grocery', 'Scored *from the door.*', 'Hygiene inspections with published scores.', 'A hygiene inspection is a walk through someone’s working day, ending in a score that goes on the window: temperatures, storage, and paperwork checked in order. The design is a checklist with consequences — clauses, photographs, and one green for a premises that passed.', '#20c5a1 #93c4ae #c2410c #d8e8e0 #f2faf6 #0a1e16', 'Livvic', 'Inter', 'numbered-steps', 'docs', 2, 'flat', 'premises due a reinspection', 'Grace Mwangi'),
  row('weights-and-measures', 'Weights and Measures', 'Brutalism', 'scales calibration standards verified', 'Government|Logistics|Manufacturing', 'Calibrated *to the gram.*', 'A laboratory that keeps trade honest.', 'Weights and measures is metrology as public trust: standards kept under glass, instruments tested, and a stamp that means a scale may be used to sell by weight. The design is precise and mechanical — tolerance tables, certificate numbers, and no colour that suggests a rounding.', '#2228aa #93a2bd #f2c400 #d6dee8 #f2f5fa #0a1220', 'Space Mono', 'Jost', 'rivet-row', 'poster', 0, 'hard', 'instruments out of tolerance', 'Frank Delaney'),
  row('trade-licensing', 'Trade Licensing', 'Professional', 'licensing trades permits registration', 'Government|Construction|Marketplace', 'Registered, *then insured.*', 'A register of who may work on what.', 'Trade licensing answers a simple question with a paper trail: is this person allowed to do this work, and who is insured if it goes wrong. The design is a directory — registration numbers, endorsements, and one green for a licence in good standing.', '#95750e #d9b48a #1f6b52 #e8dcc8 #faf5ec #221608', 'Red Hat Display', 'Outfit', 'tape-labels', 'catalog', 4, 'flat', 'licences near expiry, one trade each', 'Frank Delaney'),
  row('border-check', 'Border Check', 'Brutalism', 'border passport control lanes arrivals', 'Government|Travel|Cybersecurity', 'Next, *please.*', 'A passport lane designed for throughput.', 'Border control is a queue with a legal decision inside it: documents read, travellers matched, and a lane that has to clear a planeload in under an hour. The design is dark and immediate — big directives, minimal words, and one amber for a referral.', '#114b5b #8fa8b4 #e8b02b #cfdae0 #eef4f7 #08161d', 'Chakra Petch', 'Be Vietnam Pro', 'scanlines', 'centered', 2, 'inset', 'travellers held for a secondary check', 'Grace Mwangi'),
  row('passport-issuance', 'Passport Issuance', 'Luxury', 'passports issuance identity documents', 'Government|Travel|Banking', 'Nine years, *then renew.*', 'A document office that checks identity twice.', 'A passport office is identity verification with a printed output: referees, photographs, and a book that lets someone cross a border. The design is security-first — holographic accents used sparingly, document numbers, and one gold for a collection appointment.', '#2f5776 #93a2b4 #d4af37 #d8e0e8 #f4f7fa #0a1420', 'Merriweather', 'Jost', 'inset-frame', 'catalog', 2, 'soft', 'applications awaiting interview', 'Constance Whitfield'),
  row('school-admissions', 'School Admissions', 'Creative', 'admissions places offers appeals schools', 'Education|Kids|Community', 'Offered, *held, or waiting.*', 'Places allocated by rule, not by taste.', 'School admissions is a matching problem that decides a child’s morning: catchments measured, siblings counted, and offers sent on one day. The design is bright and fair-minded — distance bands, waitlist positions, and one accent for an appeal in progress.', '#eac52f #e8d18a #2f5d8a #f0e6c8 #fdf9ec #2a220c', 'Nunito', 'Lora', 'pill-nav', 'split-hero', 12, 'soft', 'places still on a waitlist', 'Margaret Ellery'),
  row('housing-allocation', 'Housing Allocation', 'Brutalism', 'housing allocation tenancy waiting list', 'Government|Real Estate|Nonprofit', 'Band three, *sixteen months.*', 'A waiting list that has to explain itself.', 'Housing allocation is need ranked in public: bands explained, waiting times published, and every decision reviewable by the person it affects. The design is plain and unsentimental — band tables, tenancy states, and one orange for a property refused.', '#2cb0ba #a4c4b4 #c2410c #dce8e0 #f4faf6 #0a1c15', 'Unbounded', 'Outfit', 'quilt-patch', 'bento', 0, 'flat', 'properties refused, one household each', 'Rowan Ellis'),
  row('benefits-desk', 'Benefits Desk', 'Minimalism', 'benefits claims entitlements payments support', 'Government|Nonprofit|Mental Health', 'Entitled, *then paid.*', 'Support claims processed without humiliation.', 'A benefits desk is the state at its most consequential: eligibility read, evidence requested once, and a payment date people plan around. The design is plain, large-typed and patient — no jargon where a sentence will do, and one accent for a claim that needs a document.', '#1b278f #93a8bd #e07a5f #d8e1e8 #f4f8fa #0a1820', 'Inter', 'Merriweather', 'inset-frame', 'receipt', 4, 'flat', 'claims waiting on a document', 'Imogen Blake'),
  row('employment-office', 'Employment Office', 'Professional', 'jobs vacancies coaching claimants', 'Government|HR & Recruiting|Community', 'Matched, *not just listed.*', 'A job centre that tracks outcomes.', 'An employment office is measured by placements, not listings: vacancies matched, interviews arranged, and support that continues after the first payslip. The design is practical and encouraging — vacancy cards, appointment slots, and one blue for a role closing soon.', '#2592c1 #93bdb4 #e8b02b #d9e8e4 #f3faf8 #0a1e1c', 'Rubik', 'Jost', 'numbered-steps', 'timeline', 2, 'hard', 'vacancies closing soon', 'Eamon Doyle'),
  row('pension-registry', 'Pension Registry', 'Professional', 'pensions contributions retirement records', 'Government|Banking|Accounting', 'Paid in, *thirty years later out.*', 'Records that have to survive a working life.', 'A pension registry is a long document: contributions recorded, transfer values quoted, and a statement sent once a year to people who rarely read it. The design is steady and legible — year bands, projected figures, and one green for a record that is complete.', '#5029ae #9a94b4 #22c55e #dcd9e8 #f5f4fb #111028', 'Lora', 'Spectral', 'tape-labels', 'receipt', 0, 'hairline', 'records with a gap in contributions', 'Gerald Whitby'),
  row('driving-licence', 'Driving Licence', 'Playful', 'licence driving categories endorsements', 'Automotive|Government|Logistics', 'Categories *you may drive.*', 'A licence that lists what you are allowed to do.', 'A driving licence is a permissions list with a photograph: categories earned, endorsements recorded, and expiry that arrives quietly. The design is friendly and practical — category blocks, provisional markers, and one pink for a restriction.', '#d4c144 #e8c48a #1f6b8a #f0e0c8 #fdf8ee #241808', 'Righteous', 'Outfit', 'corner-brackets', 'hero-cards', 8, 'hard', 'endorsements nearing expiry', 'Charlie Mbeki'),
  row('vehicle-registration', 'Vehicle Registration', 'Retro', 'vehicles registration plates records', 'Automotive|Government|Insurance', 'Plate, *keeper, history.*', 'A register that keeps track of what is on the road.', 'Vehicle registration is a database people meet at a desk: plates read, keepers recorded, and a history that decides whether a car may be sold. The design is paperwork with chrome — plate formats, keeper changes, and one accent for a record under query.', '#934424 #d9b08a #2f5d8a #e8dcc8 #f7f4ee #221408', 'Anton', 'Archivo', 'mono-labels', 'dashboard', 0, 'flat', 'records flagged for query', 'Frank Delaney'),
  row('boundary-commission', 'Boundary Commission', 'Minimalism', 'boundaries constituencies review maps', 'Government|Data & Analytics|News', 'Redrawn *every eight years.*', 'Reviews that move the lines on the map.', 'A boundary review is geography with arithmetic: electorates counted, wards grouped, and a map that has to be defended in consultation. The design is cartographic and neutral — draft lines, deviation percentages, and no accent that favours a proposal.', '#5839a1 #9a94bd #e07a5f #dedaec #f6f5fc #141228', 'Syne', 'Space Grotesk', 'pixel-grid', 'map-plate', 0, 'hairline', 'seats outside tolerance', 'Owen Pryce'),
  row('electoral-count', 'Electoral Count', 'Professional', 'counts ballots results declaration', 'Government|News|Community', 'Counted, *verified, declared.*', 'A results night that reports as it counts.', 'A count is transparency performed in a hall: ballot boxes opened, batches verified, and a declaration made before the hall empties. The design is a results board — turnout, batch states, and one amber for a recount requested.', '#1c1372 #94a2bd #e8b02b #d6dfe8 #f2f5fa #0a1220', 'Be Vietnam Pro', 'Red Hat Display', 'big-stat-row', 'dashboard', 2, 'inset', 'wards awaiting declaration', 'Eamon Doyle'),
  row('public-records', 'Public Records', 'Creative', 'records requests documents access', 'Government|Legal|News', 'Requested, *redacted, released.*', 'Documents released to whoever asks correctly.', 'Public records work is a pipeline of judgement: requests read, exemptions applied, and a release that has to be defensible line by line. The design is archival and neutral — reference numbers, redaction counts, and one blue for a release made in full.', '#8d844f #c4b39a #1f4a6b #e8e2d4 #fbf9f2 #221c10', 'Literata', 'Jost', 'grain-overlay', 'docs', 0, 'hairline', 'requests past the statutory clock', 'Tobias Lund'),
  row('national-archives', 'National Archives', 'Luxury', 'archives preservation catalogues collections', 'Government|Education|Publishing', 'Kept *for the next century.*', 'A building that stores a country’s memory.', 'An archive is a promise about the future made by people who will not see it: acid-free boxes, catalogue entries, and a reading room where gloves are mandatory. The design is deep and dignified — catalogue references, condition notes, and one gold for a document newly available.', '#77524b #b39a8a #d4af37 #e2d8cc #f8f4ee #1e140e', 'Bodoni Moda', 'Lora', 'stamp-seal', 'split-scroll', 4, 'hairline', 'items awaiting conservation', 'Constance Whitfield'),
  row('freedom-of-information', 'Freedom of Information', 'Creative', 'foi transparency disclosure requests', 'Government|News|Nonprofit', 'Ask, *and be answered.*', 'A regime that assumes disclosure by default.', 'Freedom of information only works when the default is disclosure: requests logged, deadlines published, and refusals explained in writing. The design is open and unfussy — request IDs, response times, and one accent for anything answered late.', '#6b8f56 #a4bd94 #1f3f66 #dce4d4 #f5f8f0 #101a0c', 'Archivo', 'Space Grotesk', 'outline-type', 'magazine', 2, 'hairline', 'requests answered after deadline', 'Tobias Lund'),
  row('civic-charter', 'Civic Charter', 'Luxury', 'charter services standards promise', 'Government|Community|Consulting', 'What you *may expect of us.*', 'A charter of service standards, in plain words.', 'A civic charter is a promise written down so it can be measured: response times, opening hours, and a complaints route that does not require a lawyer. The design is calm and formal — numbered pledges, published standards, and one gold for a promise met early.', '#39707f #93a8b4 #c9971b #d8e4e8 #f4fafa #0a1c20', 'Gilda Display', 'Lora', 'serif-italic-hero', 'manifesto', 6, 'soft', 'pledges missed this quarter', 'Margaret Ellery'),
  row('typing-pool', 'Typing Pool', 'Retro', 'typists pool carbon letters queue', 'Government|Publishing|Accounting', 'Dictated once, *typed twice.*', 'A room of typists and a tray of dictation.', 'A typing pool was throughput measured in keystrokes: dictation trays, carbon copies, and a supervisor who could hear a mistake from across the room. The design is office retro — tray labels, revision counts, and one accent for a job marked urgent.', '#bab345 #d9c08a #7a1f38 #f0e4cc #fdf8ec #241c0c', 'Silkscreen', 'Lora', 'halftone-dots', 'centered', 12, 'hard', 'jobs over their typing window', 'Billy Hart'),
  // __W16__
]
