import type { DesignSystem } from '../types'
import { row } from './build'

/**
 * Wave 17 — Trades and Bench Work: the workshops where things are still made
 * by hand, from binding to blacksmithing.
 * Row format: id, name, category, tags, useCases, hero, description,
 * philosophy, colors, display, body, motif, layout, radius, depth,
 * accentRole, author.
 */

export const wave17Designs: DesignSystem[] = [
  row('bookbindery', 'Bookbindery', 'Creative', 'binding signatures thread boards press', 'Publishing|Art Gallery|Education', 'Sewn, glued, *pressed overnight.*', 'A bindery that repairs what printing left loose.', 'Binding is the part of a book that decides whether it survives being read: signatures sewn, spines rounded, and a case that opens flat. The design is thread and board — gauge notes, stitch counts, and one deep blue for a spine waiting on its case.', '#8e4850 #c49a8a #1f4a5f #e8dad2 #faf5f1 #241512', 'Cormorant Garamond', 'Cabin', 'stitch-line', 'editorial', 4, 'soft', 'books waiting on a case, one shelf each', 'Juno Vasquez'),
  row('glazier', 'Glazier', 'Professional', 'glass cutting panes windows putty', 'Construction|Real Estate|Automotive', 'Measured twice, *cut once.*', 'A glazier who works to the millimetre.', 'Glazing is a trade of tolerances: panes measured on site, cut on a bench, and set with a clearance that lets a building move. The design is clear and cool — pane schedules, edge finishes, and one amber for glass that has not yet arrived.', '#256dc1 #a4c4d4 #e8b02b #dce8ee #f4f9fc #0c1c24', 'Livvic', 'Jost', 'glass-sheen', 'catalog', 2, 'hairline', 'panes still on order', 'Marek Dolny'),
  row('plumber', 'Plumber', 'Brutalism', 'pipe plumbing fittings valves leaks', 'Construction|Real Estate|Government', 'Water goes *where you tell it.*', 'Pipes, fittings and a very short list of rules.', 'Plumbing is a trade with two laws: water runs downhill, and payday is Friday. Everything else is fittings, fall, and a pressure test that either holds or does not. The design is a service sheet — pipe sizes, fall per metre, and one orange for a leak logged.', '#1d59af #93a8bd #e07a3a #d6dfe8 #f2f6fa #0a1620', 'Bebas Neue', 'Jost', 'rivet-row', 'docs', 0, 'hard', 'jobs with an open leak', 'Frank Delaney'),
  row('electrician', 'Electrician', 'Professional', 'wiring circuits boards testing certification', 'Construction|Energy|Real Estate', 'Tested, *certified, signed.*', 'Wiring that has to be provable on paper.', 'An electrician leaves behind a certificate as much as a circuit: loop impedances recorded, boards labelled, and a test sheet that a buyer will read one day. The design is a test sheet — circuit numbers, readings, and one blue for a board that failed.', '#c0a807 #d9c08a #1f3f8a #efe4c4 #fdf8ec #241d0c', 'Oxanium', 'Jost', 'diagonal-bars', 'timeline', 0, 'inset', 'boards failing a test, one circuit each', 'Frank Delaney'),
  row('upholsterer', 'Upholsterer', 'Luxury', 'upholstery fabric frames stuffing cushions', 'Fashion|Real Estate|Hotel', 'Stripped back, *built up again.*', 'Furniture rebuilt from the frame out.', 'Upholstery is archaeology with a staple gun: webbing replaced, horsehair reused where it is still good, and a frame that outlives three covers. The design is textile-forward — fabric swatches, frame notes, and one violet for a piece awaiting its second fitting.', '#9b4b91 #c4a4b4 #1f6b52 #ece0e8 #fbf6f9 #241626', 'Gilda Display', 'Figtree', 'quilt-patch', 'bento', 12, 'soft', 'pieces waiting on a second fitting', 'Marguerite Chastain'),
  row('tiler', 'Tiler', 'Creative', 'tiles setting grout patterns gridded', 'Construction|Real Estate|Design Tools', 'Level, spaced, *grouted.*', 'A tiler who lives inside a grid.', 'Tiling is set-out geometry: a datum line, a layout that puts whole tiles where they will be seen, and grout that forgives a millimetre. The design is a grid — tile counts, spacing widths, and one orange for a cut that has to be redone.', '#153479 #a4b8cc #d97706 #dce4ec #f4f8fb #0b1722', 'Silkscreen', 'Archivo', 'swiss-grid', 'mosaic', 2, 'flat', 'rooms awaiting set-out, one wall each', 'Marek Dolny'),
  row('plasterer', 'Plasterer', 'Minimalism', 'plaster skim lime walls trowel', 'Construction|Real Estate|Architecture', 'Two coats, *no sanding.*', 'Walls finished by hand, to the light.', 'Plastering is judged by raking light: a wall is flat when nothing catches the sun, and lime has to be worked before it goes off. The design is quiet and pale — coat schedules, drying times, and one cool accent for a wall still curing.', '#a7a296 #d9d2c8 #1f6b8a #ece7e0 #faf8f5 #241f1a', 'Karla', 'Lora', 'soft-shadows', 'centered', 8, 'soft', 'rooms still curing, one wall each', 'Gethin Price'),
  row('cabinetmaker', 'Cabinetmaker', 'Organic', 'cabinets joinery drawers dovetails wood', 'Manufacturing|Real Estate|E-commerce', 'Drawers that *close themselves.*', 'Furniture joined without a single screw.', 'Cabinetmaking is joinery as a promise: dovetails cut to fit by hand, drawers that run on wood, and a finish that lets the grain speak. The design is workshop-warm — board lists, joint details, and one green for timber that is drying.', '#a46b46 #d4b48a #2f5d3a #ece0cc #fdf7ec #241708', 'Fraunces', 'Cabin', 'paper-cut', 'catalog', 4, 'soft', 'boards still drying, one rack each', 'Tobias Lund'),
  row('watchmaker', 'Watchmaker', 'Luxury', 'watches movements escapements servicing', 'E-commerce|Fashion|Manufacturing', 'Serviced *to the second a day.*', 'Movements cleaned, oiled and regulated.', 'Watchmaking is repair at the scale of hairsprings: a movement stripped, cleaned, oiled at six points, and regulated until it keeps time in every position. The design is loupe-close — service records, rate charts, and one gold for a watch that left specification.', '#4e396e #9a94b0 #c9971b #e0dce8 #f7f6fa #12101c', 'Bodoni Moda', 'Figtree', 'moire-rings', 'spotlight', 2, 'soft', 'watches outside rate limits', 'Roland Devereux'),
  row('luthier', 'Luthier', 'Creative', 'instruments guitars spruce repair setups', 'Music|Manufacturing|E-commerce', 'Seasoned *before it sings.*', 'Instruments built and kept in tune.', 'A luthier works in wood that has already waited years: tops thinned by ear, braces shaped, and a setup adjusted until a player stops thinking about the instrument. The design is warm and precise — wood grades, planting dates, and one deep blue for a repair in progress.', '#603f10 #cfa87f #1f4a5f #eeddcc #fdf6ec #241508', 'Cormorant Garamond', 'Hanken Grotesk', 'serif-italic-hero', 'split-scroll', 4, 'soft', 'instruments awaiting setup', 'Roland Devereux'),
  row('cooper-works', 'Cooper Works', 'Brutalism', 'barrels casks staves hoops coopering', 'Manufacturing|Restaurant|Marketplace', 'Staves, hoops, *no glue.*', 'Casks built to hold liquid and last decades.', 'A cooper raises a barrel from staves and fire: no adhesive, just a shape that swells shut and a hoop tension that keeps it that way. The design is workshop-heavy — stave counts, toast levels, and one gold for a cask about to be filled.', '#9a601f #b39a8a #c9971b #e2d8cc #f8f4ee #1e140e', 'Archivo Black', 'Cabin', 'rivet-row', 'film-strip', 0, 'hard', 'casks awaiting filling, one batch each', 'Gerard Ilunga'),
  row('milliner', 'Milliner', 'Luxury', 'hats millinery brims felting', 'Fashion|Wedding|E-commerce', 'Blocked, *steamed, finished.*', 'Hats shaped by hand over wooden blocks.', 'Millinery is sculpture at head size: felt steamed over a block, brims wired, and a shape that has to survive a wedding and a car journey. The design is elegant and exact — block sizes, trim notes, and one accent for a hat awaiting a fitting.', '#b93c42 #e0a4bc #d4af37 #f0dce4 #fdf6f9 #241018', 'Mrs Saint Delafield', 'Figtree', 'stamp-seal', 'spotlight', 999, 'soft', 'hats awaiting a fitting', 'Marguerite Chastain'),
  row('basket-weaver', 'Basket Weaver', 'Organic', 'baskets weaving willow rushes handles', 'Manufacturing|Grocery|Art Gallery', 'Soaked, woven, *dried in the sun.*', 'Willow and rush worked into shapes that carry.', 'Basket weaving is tension management: rods soaked until they bend, stakes set, and a weave that holds its shape once it dries. The design is woven and rural — rod counts, weave patterns, and one blue for harvest baskets still on order.', '#655420 #d4c49a #2f5d8a #ece4cc #fbf7ec #241d0c', 'Petrona', 'Jost', 'lattice-weave', 'mosaic', 8, 'soft', 'orders for harvest season', 'Siobhán Walsh'),
  row('potters-wheel', 'Potter’s Wheel', 'Organic', 'pottery clay throwing glazes kiln', 'Art Gallery|E-commerce|Education', 'Centred, *then everything else.*', 'A studio that measures nothing and logs everything.', 'Throwing is a negotiation with a spinning lump: centre it and the rest follows, or lose it entirely. The design is clay and kiln — glaze recipes, firing curves, and one deep teal for a piece about to be bisqued.', '#a53d0d #d9b4a4 #2f5d6b #efe0d8 #fdf6f2 #241410', 'Literata', 'Figtree', 'terrazzo-speck', 'split-hero', 12, 'soft', 'pieces awaiting bisque, one shelf each', 'Hana Fujimoto'),
  row('marbler', 'Marbler', 'Creative', 'marbling paper ink baths patterns', 'Publishing|Design Tools|Art Gallery', 'One dip, *no retakes.*', 'Patterns floated on water and lifted once.', 'Marbling is a process you cannot correct: ink floated on size, combed once, and a sheet laid down for exactly one chance at the pattern. The design is fluid — bath recipes, pattern names, and one deep red for a sheet that lifted clean.', '#3d4a71 #93a8bd #a82f4a #d8e0e8 #f5f8fa #0a1420', 'Playfair Display', 'Merriweather', 'oil-slick', 'poster', 0, 'hard', 'baths run this week, one pattern each', 'Wren Baker'),
  row('gilder', 'Gilder', 'Luxury', 'gilding gold leaf frames restoration', 'Art Gallery|Real Estate|Publishing', 'Loose gold, *laid with a breath.*', 'Leaf applied where a surface must look priceless.', 'Gilding is delicacy with a deadline: size applied, leaf laid before it goes tacky, and a burnish that either sings or streaks. The design is metallic and careful — leaf counts, carat notes, and one gold reserved for a surface freshly gilded.', '#be8d08 #d4c08a #1f4a5f #ece2c8 #fdf9ee #241c0c', 'Gloock', 'Jost', 'stamp-seal', 'editorial', 2, 'soft', 'frames awaiting a burnish', 'Cornelius Pike'),
  row('woodturner', 'Woodturner', 'Organic', 'lathe turning bowls spokes grain', 'Manufacturing|E-commerce|Art Gallery', 'Green wood, *turned wet.*', 'Bowls turned from timber that is still moving.', 'Turning green wood is working with a material that will change shape after you finish: wall thickness guessed, grain read, and a bowl that warps into its final form. The design is shavings and oil — block lists, moisture readings, and one green for timber ready to turn.', '#b8641e #c4a894 #2f6b52 #e8dcd0 #faf5ee #221810', 'Spectral', 'Jost', 'isometric-lattice', 'catalog', 8, 'soft', 'blanks ready to turn, one log each', 'Tobias Lund'),
  row('blacksmith', 'Blacksmith', 'Brutalism', 'forge anvil hammer steel heat', 'Manufacturing|Construction|Art Gallery', 'Yellow hot, *then shaped.*', 'Iron worked in a narrow band of temperature.', 'Smithing is timing in colour: a heat that lasts ninety seconds, a hammer that only moves metal while it glows, and a finish that is decided at the anvil. The design is soot and scale — heat colours, tool lists, and one orange for a piece that must return to the fire.', '#4e5a49 #9a9a9a #e8630a #d6d6d8 #f2f2f3 #17171a', 'Anton', 'Jost', 'hard-shadows', 'full-bleed', 0, 'hard', 'pieces needing another heat', 'Gerard Ilunga'),
  row('cutler', 'Cutler', 'Brutalism', 'knives blades steel handles sharpening', 'Manufacturing|Grocery|E-commerce', 'Sharp enough *to be boring.*', 'Blades ground, hardened, and honed.', 'A cutler’s work is metallurgy with an edge: steels hardened to a hardness, bevels ground by eye, and a finished knife that cuts without drama. The design is dark and precise — steel grades, bevel angles, and one gold for a blade that passed the paper test.', '#353555 #93a2ad #c9971b #d5dde2 #f2f6f8 #0c1419', 'Bebas Neue', 'Cabin', 'inset-frame', 'poster', 0, 'hard', 'blades awaiting honing, one batch each', 'Cornelius Pike'),
  row('cobbler', 'Cobbler', 'Retro', 'shoes repair soles leather resoling', 'Fashion|Real Estate|Community', 'Resoled, *not replaced.*', 'A repair shop that keeps good shoes going.', 'A cobbler is a repair trade with a stubborn belief: a well-made shoe is worth more than the repair costs. Soles stitched, heels rebuilt, and a last that has held a customer’s shape for years. The design is bench-worn and practical.', '#bf7b18 #b3987a #2f5d8a #e6d8c4 #faf5ec #221608', 'Rye', 'Jost', 'stitch-line', 'catalog', 4, 'hard', 'repairs waiting on parts', 'Roland Devereux'),
  row('tailor', 'Tailor', 'Luxury', 'tailoring suits fittings cloth measurements', 'Fashion|Wedding|E-commerce', 'Cut for *one body only.*', 'Suits built from a paper pattern and three fittings.', 'Tailoring is a conversation held in cloth: measures taken, a basted fitting worn, and a jacket that finally stops pulling at the shoulder. The design is cloth and chalk — measurement tables, fitting stages, and one gold for a suit ready to collect.', '#262230 #9a9fb4 #c9971b #dcdde8 #f6f6fa #10121c', 'Gilda Display', 'Mulish', 'ribbon-band', 'editorial', 2, 'hairline', 'suits awaiting a second fitting', 'Marguerite Chastain'),
  row('framer', 'Framer', 'Creative', 'framing mounts glass conservation frames', 'Art Gallery|Photography|E-commerce', 'Measured, *mounted, sealed.*', 'Frames built so the artwork outlives the frame.', 'Framing is a conservation decision disguised as a look: mounts cut to a margin, glazing chosen for UV, and a backing sealed so nothing migrates. The design is quiet and exact — aperture sizes, mount depths, and one accent for a frame awaiting glazing.', '#ae6832 #b3a882 #7a1f38 #e6dfc8 #faf7ec #221c0d', 'EB Garamond', 'Lora', 'inset-frame', 'catalog', 0, 'hairline', 'frames awaiting glazing, one mount each', 'Wren Baker'),
  row('papermill', 'Papermill', 'Brutalism', 'paper pulp deckle screens drying', 'Manufacturing|Publishing|Art Gallery', 'Pulp in, *sheets out.*', 'Paper made a sheet at a time by hand.', 'Hand papermaking is a wet process with a long memory: pulp beaten for hours, a sheet couched onto felt, and a drying stack that decides the surface. The design is industrial and damp — fibre mixes, couching counts, and one orange for a batch still under weight.', '#556a8c #9aa8b4 #c2410c #d9e0e6 #f3f6f8 #0e141a', 'Anton', 'Be Vietnam Pro', 'torn-edge', 'film-strip', 0, 'flat', 'batches under weight, one vat each', 'Rowan Ellis'),
  row('ink-works', 'Ink Works', 'Creative', 'ink pigment grinding varnish presses', 'Manufacturing|Publishing|Design Tools', 'Ground fine, *then finer.*', 'Pigment milled into ink that behaves.', 'Ink making is a grinding problem: pigment dispersed, varnish matched, and a drawdown test that shows whether a colour will print the same twice. The design is dark and printing-room ready — batch numbers, tack readings, and one gold for an ink that passed the drawdown.', '#4a2688 #8f94b4 #c9971b #d8dae8 #f4f5fa #0a0c18', 'Fraunces', 'Hanken Grotesk', 'halftone-dots', 'manifesto', 2, 'hard', 'batches awaiting a drawdown', 'Tobias Lund'),
  row('dye-house', 'Dye House', 'Organic', 'dyeing vats colours fibres recipes', 'Manufacturing|Fashion|Agriculture', 'Dip, wait, *rinse, repeat.*', 'Colour fixed with heat and patience.', 'Dyeing is chemistry with a memory: mordants measured, vats held at temperature, and a shade matched to a sample that may be fifty years old. The design is saturated and industrial — recipe cards, liquor ratios, and one accent for a dye lot off shade.', '#f00fd2 #d4a4c4 #d9a441 #ece0e8 #fdf6fa #241026', 'Caveat', 'Jost', 'gradient-hero', 'mosaic', 12, 'glow', 'lots off shade, one vat each', 'Hana Fujimoto'),
  row('weavers-loom', 'Weaver’s Loom', 'Organic', 'weaving loom warp weft cloth', 'Manufacturing|Fashion|Art Gallery', 'Warp first, *then everything.*', 'Cloth built thread by thread, to a draft.', 'Weaving is planning done in advance: a warp wound to length, a draft that decides the pattern, and a loom that only forgives so much. The design is thread and draft — sett tables, picks per inch, and one blue for a warp still to be tied on.', '#ad7b2b #cfa87f #2f5d6b #ece0cc #fbf6ec #241808', 'Lora', 'Figtree', 'lattice-weave', 'split-scroll', 6, 'soft', 'warps awaiting tying on, one loom each', 'Hana Fujimoto'),
  row('lacemaker', 'Lacemaker', 'Luxury', 'lace bobbins pillows threads patterns', 'Fashion|Wedding|Art Gallery', 'Two hundred bobbins, *one pattern.*', 'Lace made at a cushion, pin by pin.', 'Bobbin lace is memory held in the hands: pairs worked in order, pins placed to hold a shape, and a pattern that only reveals itself near the end. The design is delicate and pale — pattern pricking, thread counts, and one accent for a piece still on the pillow.', '#a55f59 #dcd0cc #2f5d6b #efe8e4 #fcfaf9 #26201e', 'Mrs Saint Delafield', 'Cabin', 'watermark-glyph', 'spotlight', 999, 'hairline', 'pieces still on the pillow', 'Constance Whitfield'),
  row('glass-engraver', 'Glass Engraver', 'Luxury', 'engraving glass wheel stipple awards', 'Art Gallery|Manufacturing|E-commerce', 'Cut *without breaking.*', 'Engraving that has to survive the glass.', 'Engraving glass is drawing with a wheel against a material that will not forgive a slip: stipple shaded, letters cut, and a rim that must stay perfect. The design is cool and exact — wheel sizes, stipple grinds, and one gold for a piece that has been polished.', '#11124a #9aa8bd #c9971b #d9e2ea #f4f8fb #0b1420', 'Bodoni Moda', 'Hanken Grotesk', 'glass-sheen', 'spotlight', 4, 'soft', 'pieces awaiting polishing', 'Roland Devereux'),
  row('silversmith', 'Silversmith', 'Luxury', 'silver raising hammers polishing hallmarks', 'Manufacturing|Fashion|Art Gallery', 'Raised *from a flat disc.*', 'Silver formed by hammers and annealing.', 'Raising silver is patience with heat: a disc hammered to a bowl, annealed before it tears, and planished until the surface reads like water. The design is monochrome with one metallic accent — gauge notes, anneal counts, and a hallmark block.', '#8c737b #a8a8b4 #1f5f4a #dcdee4 #f6f7f9 #15151c', 'Marcellus', 'Figtree', 'stamp-seal', 'bento', 4, 'soft', 'pieces awaiting hallmarking', 'Marguerite Chastain'),
  row('calligrapher', 'Calligrapher', 'Creative', 'calligraphy nibs ink commissions scripts', 'Wedding|Publishing|Design Tools', 'One pass, *no pencil first.*', 'Lettering written once, at size.', 'Calligraphy is a performance with a tool: nib loaded, guides ruled, and a line written without a second attempt. The design is ink and paper — script samples, nib widths, and one deep red for a commission in progress.', '#56434a #8f8f9a #a82f4a #dcdce2 #f7f7fa #101018', 'Caveat', 'Lora', 'underline-accent', 'editorial', 0, 'hairline', 'commissions in progress', 'Wren Baker'),
  row('cartwright', 'Cartwright', 'Retro', 'carts wheels axles timber carriage', 'Manufacturing|Agriculture|Travel', 'Spokes shaved *to a whisper.*', 'Wheels and carts built to carry loads on bad roads.', 'A cartwright works on the part of a vehicle that fails first: hubs, spokes, and an axle bed that has to take a rut at speed. The design is timber and iron — wheel sizes, spoke counts, and one accent for a cart awaiting its iron tyres.', '#d3ab17 #cfae82 #2f5d8a #eaddc8 #fbf6ec #241808', 'Rye', 'Cabin', 'rivet-row', 'timeline', 8, 'hard', 'carts awaiting tyres, one frame each', 'Cornelius Pike'),
  row('brass-polish', 'Brass Polish', 'Retro', 'brass polishing fittings plaques restoration', 'Manufacturing|Real Estate|Hotel', 'Dull in, *bright out.*', 'A bench that makes brass look new again.', 'Polishing is abrasive work with a finish line: mops loaded with compound, corners masked by hand, and a lacquer that decides how long the shine lasts. The design is metallic and warm — compound grades, timing notes, and one deep blue for a plaque still on the bench.', '#7a7329 #d9c68a #1f4a5f #efe6c8 #fdf9ec #241d0a', 'Oswald', 'Figtree', 'glow-pulse', 'centered', 6, 'glow', 'pieces still on the bench', 'Billy Hart'),
  row('sign-carver', 'Sign Carver', 'Creative', 'carving signs letters wood gilding', 'Design Tools|Real Estate|Art Gallery', 'Cut deep, *then painted.*', 'Signs carved to be read from fifty metres.', 'A carved sign is resolved at a distance: letterforms drawn by hand, incised with a chisel or a router, and painted so the counters stay open in rain. The design is bold and legible — letter heights, carve depths, and one gold for a line still to be gilded.', '#51902a #9ab49a #c9971b #dae4da #f4f9f4 #0c1a0c', 'Playfair Display', 'Jost', 'torn-edge', 'poster', 2, 'soft', 'signs awaiting gilding', 'Wren Baker'),
  row('key-cutter', 'Key Cutter', 'Retro', 'keys cutting locks cylinders copies', 'E-commerce|Community|Real Estate', 'Copied *while you wait.*', 'A shop that turns blanks into keys.', 'Key cutting is a machine trade with a satisfying result: a blank selected from a board, a pattern traced, and a key that either turns first try or goes back to the wheel. The design is shop-window ready — keyway codes, blank stock, and one amber for a lock still to be matched.', '#3f3e73 #9aa4b4 #d9a441 #d9dde4 #f4f6f9 #0e1420', 'Silkscreen', 'Cabin', 'pixel-grid', 'catalog', 0, 'flat', 'blanks out of stock, one keyway each', 'Billy Hart'),
  row('clock-tower', 'Clock Tower', 'Brutalism', 'tower clock mechanism chiming maintenance', 'Government|Architecture|Nonprofit', 'Wound by hand, *every week.*', 'A public clock with a mechanism to keep alive.', 'A tower clock is public infrastructure with an audience: the movement wound by hand, the bells checked, and a face that has to be right because the town below times its day by it. The design is monumental and plain.', '#43504a #9aa8a8 #c9971b #d8e0e0 #f2f6f6 #0c1414', 'Anton', 'Cabin', 'big-stat-row', 'poster', 0, 'flat', 'clocks out of adjustment', 'Owen Pryce'),
  row('bench-room', 'Bench Room', 'Professional', 'bench tools workshop shared hire', 'Design Tools|Education|Manufacturing', 'The bench *is the membership.*', 'A shared workshop rented by the hour.', 'A bench room is a makerspace with rules that matter: tools signed out, dust extracted, and a booking system that stops two people needing the same mortiser. The design is practical and indexed — bench numbers, tool states, and one accent for a bench left messy.', '#47422a #b3a68a #2f5d8a #e4dcc8 #faf7f0 #1f1a10', 'IBM Plex Sans', 'Jost', 'blueprint-grid', 'asymmetric', 4, 'hairline', 'benches left unbooked, one tool each', 'Gerard Ilunga'),
  // __W17__
]
