import type { DesignSystem } from '../types'
import { row } from './build'

/**
 * Wave 13 — working rooms, trades, and the machinery of ordinary days.
 * Row format: id, name, category, tags, useCases, hero, description,
 * philosophy, colors, display, body, motif, layout, radius, depth,
 * accentRole, author.
 */

export const wave13Designs: DesignSystem[] = [
  row('xray-view', 'X-Ray View', 'Minimalism', 'radiology scans light diagnosis', 'Health|Clinic|Data & Analytics', 'Look through, *not at.*', 'A reading room where the scans do the talking.', 'A radiologist reads in a dark room with one lamp: high contrast, no colour where it would mislead, and findings that arrive before the patient sits up.', '#2b6cb0 #90cdf4 #f56565 #e2e8f0 #f7fafc #1a202c', 'Inter', 'IBM Plex Sans', 'inset-frame', 'docs', 2, 'flat', 'findings that need a second read', 'Dr. Amara Osei'),
  row('carbon-copy', 'Carbon Copy', 'Minimalism', 'forms duplicates pink files ink', 'Legal|Government|Accounting', 'Two copies, *one keystroke.*', 'Carbonless forms for offices that still sign things.', 'A carbon copy is bureaucracy’s backup plan: a pink sheet, a pressed impression, and proof that both parties hold the same truth.', '#6c4d74 #a3a3a3 #ec4899 #e5e5e5 #fafafa #171717', 'Courier Prime', 'Inter', 'underline-accent', 'receipt', 0, 'hairline', 'the pink copy, always the pink one', 'Gerald Whitby'),
  row('glass-lab', 'Glass Lab', 'Minimalism', 'glassblowing science beakers bench', 'Education|Design Tools|Manufacturing', 'Melt, *gather, blow.*', 'A scientific glassblowing bench.', 'Scientific glassblowing is craft held to laboratory tolerances: borosilicate, a torch, and joints that must fit an instrument built in 1974.', '#55a0a9 #a5f3fc #f59e0b #e0f2fe #f8fdff #0c2a33', 'Space Grotesk', 'Inter', 'blueprint-grid', 'field-notes', 2, 'hairline', 'calibration marks, one per joint', 'Viktor Havel'),
  row('quiet-floor', 'Quiet Floor', 'Minimalism', 'library study silence desks stacks', 'University|Education|Productivity', 'Silence, *enforced kindly.*', 'A library floor with a waiting list for desks.', 'The quiet floor is a shared agreement with a seating chart: if you leave for more than an hour, the desk belongs to someone else.', '#44403c #a8a29e #0ea5e9 #e7e5e4 #fafaf9 #1c1917', 'Newsreader', 'Public Sans', 'vignette', 'centered', 4, 'soft', 'desks held for one hour only', 'Margaret Ellery'),
  row('sub-basement', 'Sub-Basement', 'Maximalism', 'records crates vinyl digging dust', 'Music|Marketplace|Community', 'Downstairs, *past the smell.*', 'A record shop that organises by feeling.', 'A record shop basement is an archive with no catalogue: crates by genre, a listening deck, and staff picks written on index cards.', '#fb923c #7c2d12 #22d3ee #3a2a1f #1d1410 #fdf3e7', 'Bangers', 'Public Sans', 'oil-slick', 'catalog', 4, 'hard', 'staff picks, one card per crate', 'Dexter Moore'),
  row('zine-rack', 'Zine Rack', 'Maximalism', 'zines photocopy staples rack diy', 'Publishing|Community|Art Gallery', 'Stapled, *numbered, gone.*', 'A rack of small-press zines.', 'A zine rack is a bookshelf with a pulse: editions of forty, photocopied covers, and a till that is a jar.', '#ad2976 #0f172a #fde047 #ffe4e6 #fff5f7 #1f1235', 'Bungee', 'Karla', 'riso-offset', 'bento', 2, 'flat', 'editions under fifty, marked by hand', 'Juno Vasquez'),
  row('carnival-row', 'Carnival Row', 'Maximalism', 'fairground rides lights tickets queue', 'Events|Kids|Travel', 'The queue is *part of the ride.*', 'A fairground strip that runs till midnight.', 'A carnival is a temporary city: generators, candy floss, and a lighting plan that makes every ride look like the best one.', '#8106f9 #f59e0b #22c55e #ede9fe #fdf4ff #241333', 'Righteous', 'Nunito', 'sonar-sweep', 'mosaic', 12, 'glow', 'rides running late, one flare each', 'Rosa Delgado'),
  row('bumper-stickers', 'Bumper Stickers', 'Maximalism', 'bumper opinions traffic satire', 'Automotive|Community|News', 'Your car has *opinions.*', 'A shop for slogans that fit on a bumper.', 'A bumper sticker is politics at 100 km/h: short, loud, and impossible to argue with before the light changes.', '#eab308 #111827 #ef4444 #fef08a #fffbeb #1c1917', 'Rubik Mono One', 'Work Sans', 'quilt-patch', 'catalog', 4, 'hard', 'one-liners that survived a road trip', 'Marcy Kane'),
  row('water-tower', 'Water Tower', 'Brutalism', 'reservoir pressure steel skyline', 'Energy|Construction|Government', 'Everything below *depends on this.*', 'Water pressure, published by the metre.', 'A water tower is a promise about gravity: the higher the tank, the more ordinary the shower — and nobody thinks about it twice.', '#2e9d78 #6b7280 #38bdf8 #d1d5db #e5e7eb #111827', 'Anton', 'IBM Plex Sans', 'lattice-weave', 'full-bleed', 0, 'hard', 'pressure drops, one district at a time', 'Owen Pryce'),
  row('rail-siding', 'Rail Siding', 'Brutalism', 'freight shunting yards wagons rails', 'Logistics|Manufacturing|Energy', 'Six wagons, *one shunter.*', 'A freight yard that moves by timetable and horn.', 'A rail siding is choreography for heavy things: shunt, couple, brake, and never stand where the wagons will be in ninety seconds.', '#78350f #404040 #facc15 #d4d4d4 #e5e5e5 #171717', 'Oswald', 'Archivo', 'slat-shadow', 'timeline', 0, 'hard', 'wagons overdue at the gate', 'Frank Delaney'),
  row('boom-gate', 'Boom Gate', 'Brutalism', 'toll barrier access control queue', 'Automotive|Logistics|Government', 'Lift, *pay, done.*', 'A toll plaza built for throughput.', 'A boom gate is a decision made mechanical: a ticket, a barrier, and a lane that has to clear a car every eleven seconds.', '#9d174d #525252 #f59e0b #e4e4e7 #f5f5f5 #171717', 'Oxanium', 'Familjen Grotesk', 'ribbon-band', 'dashboard', 0, 'hard', 'violations, one lane at a time', 'Petra Novak'),
  row('mineshaft', 'Mineshaft', 'Brutalism', 'underground shifts ventilation ore', 'Energy|Manufacturing|Data & Analytics', 'The shift goes *down at six.*', 'A working shaft, ventilated and counted.', 'A mineshaft is a vertical factory with a headcount: cage schedules, ventilation records, and a lamp room that knows exactly who is underground.', '#1c1917 #44403c #f97316 #d6d3d1 #e7e5e4 #0c0a09', 'Anton', 'Bitter', 'punched-card', 'docs', 0, 'flat', 'headcounts that do not match the lamp room', 'Gethin Price'),
  row('harbour-wall', 'Harbour Wall', 'Brutalism', 'breakwater storms concrete tides', 'Construction|Government|Energy', 'Built for the *hundred-year storm.*', 'Coastal defence, poured and surveyed.', 'A harbour wall is designed around the worst day of the next century: armourstone, wave loading, and a maintenance log that never closes.', '#274050 #64748b #ef4444 #d7dee3 #eef2f5 #12202b', 'Archivo Black', 'IBM Plex Sans', 'torn-edge', 'map-plate', 0, 'flat', 'storm damage, one section per survey', 'Ingrid Solheim'),
  row('truffle-hunter', 'Truffle Hunter', 'Luxury', 'foraging dogs earth oak seasons', 'Restaurant|Agriculture|Travel', 'The dog knows *before you do.*', 'Oak forests, patient dogs, and a very short season.', 'Truffle hunting is a partnership with a nose: trails walked twice, harvests weighed in grams, and a market that sets the price by lunchtime.', '#5c4a32 #8a765a #c9a227 #eae2d4 #f7f3ea #221a10', 'Cormorant Garamond', 'Manrope', 'paper-cut', 'map-plate', 6, 'soft', 'finding days, one dog per walk', 'Étienne Rocher'),
  row('cashmere-mill', 'Cashmere Mill', 'Luxury', 'fibre soft looms heritage', 'Fashion|Manufacturing|Marketplace', 'Warmth you can *measure in microns.*', 'A heritage mill that grades by fibre.', 'Cashmere is a fibre argument measured in microns: the finer the grade, the rarer the goat, the quieter the price tag.', '#8c7853 #d6cbb8 #6b7280 #efe9dd #faf7f1 #241f17', 'Lora', 'Mulish', 'torn-edge', 'editorial', 4, 'soft', 'grade lots, one batch per season', 'Bridget Osei'),
  row('wax-seal', 'Wax Seal', 'Luxury', 'letters wax crest envelopes post', 'Publishing|Wedding|Legal', 'Some letters *deserve ceremony.*', 'Correspondence stationery with a crest.', 'A wax seal is the original signature: hot wax, a press, and a small risk that makes the letter feel intentional.', '#881337 #0f172a #d4af37 #f5e6ea #fbf7f8 #241016', 'Marcellus', 'Spectral', 'stamp-seal', 'centered', 4, 'soft', 'editions of one, pressed by hand', 'Constance Whitfield'),
  row('gondola-lift', 'Gondola Lift', 'Luxury', 'mountain cabins snow quiet', 'Travel|Hotel|Sports', 'Above the treeline *by nine.*', 'A mountain lift with a weather window.', 'A gondola is a hotel corridor hanging over a valley: cabins cleaned overnight, wind holds announced politely, and a view that ends arguments.', '#1d4e89 #9ec5e8 #f59e0b #e3edf7 #f6fafe #0f1e33', 'Outfit', 'Figtree', 'glass-sheen', 'film-strip', 8, 'soft', 'wind holds, one per lift', 'Marta Keskküla'),
  row('tide-lounge', 'Tide Lounge', 'Luxury', 'beach club loungers salt dusk', 'Wellness|Hotel|Travel', 'Barefoot until *the sun goes down.*', 'A beach club that books by the tide.', 'A good beach club plans around water: loungers above the tideline, towels warmed at dusk, and a bar that opens when the flats appear.', '#c96f4a #2a4a5a #f2c14e #f0dfd2 #fbf2ea #26201c', 'Gilda Display', 'Poppins', 'terrazzo-speck', 'spotlight', 999, 'glow', 'high tide, one line per day', 'Marguerite Chastain'),
  row('diorama-room', 'Diorama Room', 'Creative', 'miniatures sets scale lighting', 'Design Tools|Film & TV|Art Gallery', 'Everything is *1:35 scale.*', 'Miniature sets built to be photographed.', 'A diorama is a lie told in scale: forced perspective, hidden lighting, and a room that only exists where the lens points.', '#6b21a8 #f0abfc #f59e0b #ece0f7 #f9f4fd #1d1030', 'Space Grotesk', 'Work Sans', 'blueprint-grid', 'film-strip', 2, 'hard', 'sets past deadline, one per build', 'Tobias Lund'),
  row('mask-maker', 'Mask Maker', 'Creative', 'masks theatre papier mache paint', 'Art Gallery|Events|Education', 'A face is *a costume too.*', 'Theatrical masks, built up in layers.', 'A mask is a portrait with a job: it has to read from the back row, survive a season, and still come off in one piece.', '#a1381f #facc15 #0f766e #f5e3d5 #fbf1e8 #241408', 'Amatic SC', 'Cabin', 'paper-cut', 'mosaic', 12, 'hard', 'season stock, one face per shelf', 'Wren Baker'),
  row('sign-writer', 'Sign Writer', 'Creative', 'pinstriping enamel brushes letters', 'Automotive|Marketplace|Design Tools', 'One shot, *no corrections.*', 'Hand-lettered signs, painted to last a decade.', 'A sign writer loads a brush to a point and paints the letter once — the enamel dries faster than regret.', '#2f5d8a #d4a017 #e11d48 #e2e8f0 #f8fafc #0f1c2b', 'Jost', 'Work Sans', 'inset-frame', 'poster', 2, 'soft', 'rush jobs, one board per week', 'Roland Devereux'),
  row('marionette', 'Marionette', 'Creative', 'strings puppets stage drama carving', 'Art Gallery|Film & TV|Events', 'Twelve strings, *one temper.*', 'Puppet theatre for audiences that flinch.', 'A marionette is an actor with a maintenance schedule: strings tuned, joints waxed, and a curtain that still falls on time.', '#9f1239 #4c1d95 #facc15 #f7e3e8 #fdf7f8 #2a1220', 'Bodoni Moda', 'Cabin', 'ticket-stub', 'spotlight', 8, 'soft', 'matinees with a spare puppet', 'Juno Vasquez'),
  row('paint-by-number', 'Paint by Number', 'Creative', 'canvases numbers kits colours', 'Kids|E-commerce|Community', 'Stay inside *the lines.* Or don’t.', 'Numbered canvases for nervous painters.', 'Paint by number is a promise that the result will look like the box: thirty colours, numbered wells, and no decisions left to make.', '#0284c7 #f97316 #22c55e #e0f2fe #f7fcff #122336', 'Baloo 2', 'Quicksand', 'terrazzo-speck', 'bento', 4, 'hard', 'kits with a missing colour, replaced free', 'Pia Lindqvist'),
  row('claims-queue', 'Claims Queue', 'Professional', 'insurance claims adjusters files', 'Insurance|Banking|Legal', 'Every claim *has a queue position.*', 'Claims handling with the clock visible.', 'An insurance claim is a promise with paperwork: first notice, adjuster notes, and a settlement that arrives before patience runs out.', '#0416a4 #94a3b8 #ef4444 #e8eefc #f8faff #101a33', 'Inter', 'Source Sans 3', 'ledger-rules', 'dashboard', 2, 'flat', 'claims at risk of breach, one row each', 'Priya Balan'),
  row('ward-round', 'Ward Round', 'Professional', 'hospital rounds clinicians notes', 'Health|Clinic|Mental Health', 'The round *starts at eight.*', 'Clinical notes that follow the patient.', 'A ward round is a walking meeting with consequences: observations, escalations, and a plan that the next shift must be able to read.', '#3d5a80 #98c1d9 #ee6c4d #e0e6ef #f7f9fc #14202e', 'Red Hat Display', 'Figtree', 'double-rule', 'timeline', 4, 'hairline', 'escalations, one flag per patient', 'Dr. Amara Osei'),
  row('dispatch-console', 'Dispatch Console', 'Professional', 'emergency calls units response', 'Government|Health|Logistics', 'Calls answered *in eight seconds.*', 'Emergency dispatch, timed to the second.', 'A dispatch console is calm as a method: the call is triaged, the nearest unit is chosen, and the timer starts before anyone hangs up.', '#d64545 #1b2b3a #facc15 #cfd8e0 #eef2f5 #0b1219', 'Bebas Neue', 'IBM Plex Sans', 'scanlines', 'dashboard', 0, 'inset', 'units held past target, one beacon each', 'Grace Mwangi'),
  row('roll-call', 'Roll Call', 'Professional', 'precinct shifts briefing officers', 'Government|Legal|Community', 'Briefing at *0600 sharp.*', 'Shift briefings for a busy precinct.', 'Roll call is institutional memory by the minute: who is on, what happened last night, and which corner needs a car before noon.', '#243b53 #829ab1 #f59e0b #dbe4ee #f2f6fa #0d1a26', 'Archivo', 'Source Sans 3', 'punched-card', 'timeline', 2, 'hard', 'open incidents, one pin per beat', 'Eamon Doyle'),
  row('crop-cover', 'Crop Cover', 'Professional', 'agronomy soil covers rotation yield', 'Agriculture|Insurance|Data & Analytics', 'The soil *is the asset.*', 'Agronomy records that banks trust.', 'Cover cropping is a balance sheet written in the ground: species mixes, rooting depth, and a yield history that gets a farm its credit line.', '#5c8a3c #8a9a5b #b45309 #e6ead9 #f5f7ee #1f2414', 'Bitter', 'Public Sans', 'paper-cut', 'docs', 2, 'flat', 'fields below rotation target', 'Imogen Blake'),
  row('rice-terrace', 'Rice Terrace', 'Organic', 'paddies irrigation slope harvest', 'Agriculture|Energy|Travel', 'Water walks *down the hill.*', 'Ancient irrigation, maintained by hand.', 'A rice terrace is hydrology as heritage: gates opened in order, water shared by rule, and a harvest that starts at the top of the hill.', '#1b7a52 #8fc7a8 #d97706 #dcece1 #f2f8f4 #0e2a1d', 'Literata', 'Manrope', 'isometric-lattice', 'map-plate', 4, 'flat', 'gate schedules, one terrace at a time', 'Amara Diop'),
  row('olive-grove', 'Olive Grove', 'Organic', 'trees harvest oil press seasons', 'Grocery|Agriculture|Restaurant', 'First press, *nothing added.*', 'A grove that harvests by the moon and the frost.', 'Olives reward patience twice: the tree takes a decade, the oil takes an afternoon, and both are judged in a single sip.', '#9db620 #a3b18a #d97706 #e6e8d8 #f6f7ee #1c2113', 'Literata', 'Mulish', 'leaf-divider', 'field-notes', 6, 'soft', 'press dates, one batch per grove', 'Siobhán Walsh'),
  row('sheep-fold', 'Sheep Fold', 'Organic', 'flock grazing wool hills seasons', 'Agriculture|Fashion|Nonprofit', 'The flock *counts itself.*', 'Hill farming, recorded by the flock.', 'A sheep fold is a ledger kept in wool: lambing percentages, grazing rotations, and a dog that knows the far gate better than you do.', '#7a5c3e #c9bda8 #4d7c0f #ece4d6 #f8f3ea #241d14', 'Lora', 'Cabin', 'stitch-line', 'field-notes', 4, 'soft', 'lambing records, one entry per ewe', 'Gethin Price'),
  row('tide-mill', 'Tide Mill', 'Organic', 'estuary water wheel grain grinding', 'Energy|Agriculture|Travel', 'The tide grinds *the grain.*', 'A mill that runs on the estuary’s clock.', 'A tide mill is patience with a wheel: the pond fills, the gate drops, and the stones turn for exactly as long as the water allows.', '#b34a2f #354f52 #d9a441 #e8dfd2 #f6f1e7 #241812', 'Spectral', 'Public Sans', 'ribbon-band', 'split-scroll', 6, 'soft', 'grinding windows, two a day', 'Rowan Ellis'),
  row('super-8', 'Super 8', 'Retro', 'home movies reels projector family', 'Film & TV|Photography|Community', 'Three minutes, *no sound.*', 'Home movies that still smell of the attic.', 'Super 8 was cinema by the reel: three minutes of family, a splice that jumps, and a projector that whirrs like it remembers.', '#cc7722 #3f3f46 #e11d48 #e7ddd0 #f6f1e8 #1f1a14', 'Oswald', 'Karla', 'vignette', 'film-strip', 2, 'glow', 'reels not yet transferred, one per box', 'Ruth Anders'),
  row('rotary-phone', 'Rotary Phone', 'Retro', 'dial exchange bakelite calls', 'Community|Nonprofit|Productivity', 'Dial *zero* for the operator.', 'A switchboard culture, one number at a time.', 'A rotary phone makes you commit to a number: each digit is a decision, and there is no backspace, only a redial.', '#2d2d2d #8a8a8a #c2410c #e2e0dc #f4f2ee #141414', 'Courier Prime', 'Inter', 'halftone-dots', 'centered', 999, 'flat', 'party lines, one household at a time', 'Billy Hart'),
  row('penny-farthing', 'Penny-Farthing', 'Retro', 'bicycle victorian wheel race', 'Sports|Events|Travel', 'One wheel *to rule the ride.*', 'Victorian cycling, restored and raced.', 'The penny-farthing is engineering before safety: a huge wheel, a small one, and a rider who commits at the mount.', '#3f3a2f #8a7f68 #b8860b #e6e0d2 #f5f1e6 #1c1811', 'Gloock', 'Lora', 'lattice-weave', 'poster', 0, 'hairline', 'restoration grants, one per frame', 'Cornelius Pike'),
  row('shortwave', 'Shortwave', 'Retro', 'radio dial frequencies distant stations', 'Podcast|News|Community', 'Somewhere out there, *a signal.*', 'A radio dial that listens past the map.', 'Shortwave is the last analogue mystery: a dial, a wire antenna, and a station from six thousand kilometres that fades as you find it.', '#1f5f8b #94a3b8 #d97706 #dde5eb #f2f6f9 #0f2030', 'VT323', 'IBM Plex Sans', 'sonar-sweep', 'spotlight', 2, 'inset', 'frequencies logged, one card per catch', 'Halvard Ness'),
  row('water-park', 'Water Park', 'Playful', 'slides splash queues sunscreen', 'Kids|Events|Sports', 'Queue wet, *ride wetter.*', 'Slides, splash pools, and a very loud whistle.', 'A water park is a hydraulic machine with a queue attached: throughput per hour, height rules, and a whistle that means business.', '#1b6ef3 #fde047 #ff5da2 #e3edff #f6faff #0d1b3a', 'Baloo 2', 'Poppins', 'wave-section', 'bento', 999, 'soft', 'height checks, one slide at a time', 'Charlie Ngata'),
  row('firework-night', 'Firework Night', 'Playful', 'rockets bonfire november sparks', 'Events|Community|Kids', 'Stand back *from the fuse.*', 'A bonfire night with a safety briefing.', 'Fireworks are choreography with a burn time: fuse lengths, fall-out zones, and a crowd that gasps on cue.', '#ff4ecd #1b2a4a #fde047 #ffe9fb #1a1226 #f7ecff', 'Bungee Shade', 'Nunito', 'glow-pulse', 'hero-cards', 8, 'glow', 'finale shells, three per show', 'Marcy Kane'),
  row('mud-run', 'Mud Run', 'Playful', 'obstacles mud ropes teams wet', 'Sports|Events|Fitness', 'Finish dirty, *laugh harder.*', 'Obstacle runs for teams that like laundry.', 'A mud run is teamwork with a hose at the end: walls, ropes, waist-deep water, and a medal that smells like a field.', '#7a4a3a #4d7c0f #f59e0b #e8ded6 #f7f2ee #241a14', 'Anton', 'Work Sans', 'torn-edge', 'full-bleed', 2, 'hard', 'waves released, one every twenty minutes', 'Loz Fisher'),
  row('bubble-blaster', 'Bubble Blaster', 'Playful', 'bubbles machines lawn parties', 'Kids|Events|E-commerce', 'Bigger bubbles, *smaller worries.*', 'Bubble machines for lawns and birthdays.', 'Bubbles are physics children can hold: surface tension, a plastic wand, and a minute of wonder before the pop.', '#12b886 #f472b6 #facc15 #e0f7f0 #f4fdf9 #123027', 'Patrick Hand', 'Poppins', 'terrazzo-speck', 'centered', 999, 'soft', 'refill days, one per machine', 'Posy Nakamura'),
]
