import type { DesignSystem } from '../types'
import { row } from './build'

/**
 * Wave 18 — Sea, Lab and Counter: the trades that work from a shed, a bench
 * above the water, and a small window the public walks past.
 * Row format: id, name, category, tags, useCases, hero, description,
 * philosophy, colors, display, body, motif, layout, radius, depth,
 * accentRole, author.
 */

export const wave18Designs: DesignSystem[] = [
  row('sailmaker', 'Sailmaker', 'Luxury', 'sails canvas loft cutting seams', 'Manufacturing|Fashion|Travel', 'Cut flat, *sewn strong.*', 'A sail loft that measures twice and sews once.', 'A sail is a wing that has to survive its own weather: cloth laid flat, broadseams shaped by hand, and a finished luff that sets without a wrinkle. The loft reads like a drafting table — panel plans, thread weights, and one rust stitch for a seam still open.', '#4980b6 #b9b6a8 #bf5f3d #cfd2d4 #f3f5f6 #1e2426', 'Instrument Serif', 'Manrope', 'stitch-line', 'asymmetric', 2, 'soft', 'marking the one seam still open', 'Roland Devereux'),
  row('shipwright', 'Shipwright', 'Brutalism', 'boats hulls frames planking keel', 'Manufacturing|Travel|Construction', 'Frames first, *planks after.*', 'Boats built from the keel up, in a shed that smells of oak.', 'A wooden hull is a sequence you cannot reorder: keel laid, frames steamed and bent, and planking fitted while the timber still moves. The page is a shed wall of station numbers and plank widths, with one red paint mark for a butt that needs refitting.', '#8d5d2a #8d8f86 #a63b22 #cdc6b6 #efeadf #1c1509', 'Alfa Slab One', 'Courier Prime', 'slat-shadow', 'field-notes', 1, 'hard', 'flagging a butt joint to refit', 'Gerard Ilunga'),
  row('ropewalk', 'Ropewalk', 'Retro', 'rope hemp twisting yarns rigging', 'Manufacturing|Construction|Agriculture', 'Twist, lay, *twist again.*', 'Rope made the long way, one yarn at a time.', 'Rope is arithmetic done by hand: yarns twisted one way, strands laid the other, and a stretch of ropewalk long enough to keep the tension even. The layout runs like the walk itself — yarn counts, lay lengths, and one bar of colour for a batch gone slack.', '#ae9e3d #b3a487 #b8492a #ded4ba #f6f0df #201909', 'Rye', 'Work Sans', 'ticker-marquee', 'timeline', 8, 'flat', 'barring a batch that lost its lay', 'Owen Pryce'),
  row('chandlery', 'Chandlery', 'Retro', 'chandler shackles paint lamps charts', 'E-commerce|Marketplace|Travel', 'Everything a boat *forgets to bring.*', 'A dockside shop for the things nobody lists.', 'A chandler sells small necessities to people leaving in a hurry: shackles, lamp oil, a chart of the harbour, and the one bolt nobody stocked. The page reads like a stock list — shelf codes, tally marks, and one red tag for a line out of stock.', '#2783a5 #9aa6ad #c9542e #c9ced2 #eef2f3 #131d24', 'Oswald', 'Familjen Grotesk', 'ticket-stub', 'catalog', 4, 'flat', 'tagging the line that ran out', 'Piotr Kowalczyk'),
  row('lobster-pot', 'Lobster Pot', 'Organic', 'lobster creels buoys hauling strings', 'Agriculture|Restaurant|Marketplace', 'Sunk overnight, *lifted at dawn.*', 'Pots hauled before the harbour wakes.', 'Potting is patience with a buoy on it: strings set along a reef, soaked overnight, and hauled at first light before the wind picks up. The design is wet rope and salt — string positions, soak times, and one warm cork float for a string still down.', '#32a58e #a8a479 #bf5530 #cfd2c0 #eef1e6 #14201a', 'Petrona', 'Public Sans', 'lattice-weave', 'map-plate', 12, 'soft', 'counting the strings still on the bottom', 'Siobhán Walsh'),
  row('marina-berth', 'Marina Berth', 'Professional', 'marina moorings pontoon fees waiting', 'Travel|Real Estate|Booking', 'Every hull *has an address.*', 'Berths, moorings, and the woman who remembers them all.', 'A marina is a spreadsheet that floats: berth lengths, shore power, and a waiting list that moves the day somebody sells. The page is harbour administration — pontoon plans, meter readings, and one amber line for a mooring fee past due.', '#28a6bd #8fb0ac #cf7a2a #cad8d6 #f0f6f5 #0e2024', 'Red Hat Display', 'Mulish', 'ledger-rules', 'map-plate', 2, 'flat', 'underlining a fee past due', 'Nadia Ferraro'),
  row('seismograph', 'Seismograph', 'Professional', 'seismic stations tremors drums traces', 'Government|Data & Analytics|Energy', 'The needle *writes its own record.*', 'A station that never stops listening to the ground.', 'A seismic station logs the planet whether or not anything happens: drums inked, clocks checked, and traces archived for a decade so that one afternoon can be read again later. The layout is a recording drum — channel numbers, gain settings, and one amber band for a trace that needs re-reading.', '#4f5a72 #868e94 #d99a2a #cdd2d4 #f1f4f5 #10161a', 'Chakra Petch', 'Familjen Grotesk', 'scanlines', 'dashboard', 1, 'flat', 'banding the trace to re-read', 'Priya Balan'),
  row('darkroom', 'Darkroom', 'Creative', 'film developing enlarging prints chemistry', 'Photography|Art Gallery|Film & TV', 'Develop, fix, *and hope.*', 'A room lit by one red bulb and nothing else.', 'Film is chemistry you cannot watch: developer timed to the second, a stop bath that smells of vinegar, and an image that appears while you are already committed. The design works in safelight — exposure tests, tank times, and one rust red for a sheet that came out wrong.', '#d43c11 #8a8d8f #d9a02a #cfcabf #f2efe9 #17120e', 'Space Mono', 'Lora', 'vignette', 'film-strip', 0, 'flat', 'marking a sheet spoiled in the wash', 'Mei-Lin Chow'),
  row('optics-bench', 'Optics Bench', 'Minimalism', 'optics lenses polishing alignment coating', 'Manufacturing|Developer Tools|Cybersecurity', 'Aligned *to a quarter wavelength.*', 'Glass polished until it behaves like mathematics.', 'Optical work is tolerance made visible: a lens ground for days, centred on a bench, and tested against an interferometer that shows every remaining error. The design is white-room quiet — surface figures, centring errors, and one teal ring for a coating that passed.', '#53acaa #aebfbd #bf4a2a #d3dedc #f4f8f7 #10181a', 'Quicksand', 'Archivo', 'moire-rings', 'centered', 4, 'hairline', 'ringing a coating that passed', 'Hana Fujimoto'),
  row('insect-drawer', 'Insect Drawer', 'Organic', 'entomology specimens pins drawers labels', 'Education|University|Nonprofit', 'Pinned, labelled, *and filed.*', 'A collection that outlives the people who made it.', 'An insect collection is data with legs: specimens pinned to a standard height, labels written in waterproof ink, and a drawer that keeps its own climate. The page is drawer furniture — species counts, locality strings, and one green dot for a record awaiting identification.', '#7ca824 #b0a479 #9c4a2a #dbd5bb #f5f1e2 #1c1a0c', 'EB Garamond', 'Nunito', 'punched-card', 'catalog', 2, 'flat', 'dotting a specimen awaiting a name', 'Junko Arai'),
  row('planetarium-dome', 'Planetarium Dome', 'Playful', 'planetarium stars projection domes shows', 'Education|Events|Kids', 'Lights down, *sky on.*', 'A theatre where the ceiling is the whole point.', 'A planetarium sells a fifteen-minute illusion: a projector aligned to the dome, a room gone dark, and an audience that stops talking when the stars come up. The design is night-blue and gold — show times, dome geometry, and one gold pin for a seat still free.', '#4f2d76 #8f86bd #d9a92a #cfcade #f2f0f9 #0e0c22', 'Bungee Shade', 'Outfit', 'duotone-media', 'spotlight', 999, 'glow', 'pinning the last empty seat', 'Nostalgia Engine'),
  row('radar-array', 'Radar Array', 'Brutalism', 'radar dishes sweeps echoes operators', 'Government|Cybersecurity|Energy', 'Listening *for the one return.*', 'A dish that scans weather, ships and silence.', 'Radar is a sweep repeated until something appears: dish trained, gain set on the receiver, and a screen that must be watched rather than photographed. The design is a concrete compound with a phosphor display — azimuth notes, echo counts, and one amber ring for a contact still unidentified.', '#1c7d46 #86a894 #cf9a2a #cdd8ce #eff5f0 #0a1810', 'Oxanium', 'Red Hat Display', 'pcb-trace', 'map-plate', 1, 'glow', 'ringing a contact with no name yet', 'Dmitri Volkov'),
  row('cold-lab', 'Cold Lab', 'Minimalism', 'samples freezers racks alarms cryogenic', 'Health|Clinic|Education', 'Kept at *minus eighty.*', 'Freezers that hold years of someone else’s work.', 'A cold lab is a promise kept by electricity: samples frozen in numbered boxes, alarms tested every month, and a log that matters the day the power blinks. The page is clinical and blue — rack maps, temperature traces, and one red dot for a freezer door left ajar.', '#4089d9 #a0b8c4 #bf3a2a #cedbe2 #f1f7fa #0e1a22', 'Manrope', 'Lora', 'watermark-glyph', 'centered', 6, 'soft', 'flagging a door left open', 'Dr. Andrea Sun'),
  row('ice-core', 'Ice Core', 'Professional', 'glaciology layers drilling depth dust', 'Energy|Government|Education', 'Read *from the bottom up.*', 'Climate history, drilled and bagged in metres.', 'An ice core reads backwards: snow that fell a thousand years ago, compressed into layers a drill lifts in metre-long tubes. The page is a field log — depth markers, dust bands, and one rust stripe for a layer that needs a second look.', '#3c569a #a0aab2 #bf5530 #ccd4d8 #eff3f5 #101a20', 'Sora', 'Source Sans 3', 'isometric-lattice', 'timeline', 0, 'hairline', 'striping a layer marked for retest', 'Ingrid Sørholt'),
  row('cheese-cave', 'Cheese Cave', 'Organic', 'affinage caves rinds wheels turning', 'Restaurant|Grocery|E-commerce', 'Turned daily, *rind by rind.*', 'A cellar where time does the cooking.', 'Affinage is patience with a schedule: wheels brushed, humidity held, and a rind that tells you whether the cave is doing its job. The design is stone and straw — cave temperatures, turning rotas, and one amber tag for a wheel ready to leave.', '#d8af1c #c0aa80 #9c5230 #ded4b8 #f8f2e2 #1e1a0c', 'Fraunces', 'Mulish', 'terrazzo-speck', 'field-notes', 8, 'soft', 'tagging wheels ready to leave the cave', 'Aurélie Fontaine'),
  row('chocolatier', 'Chocolatier', 'Luxury', 'chocolate tempering moulds ganache couverture', 'E-commerce|Grocery|Wedding', 'Tempered *to the degree.*', 'Chocolate worked at exactly thirty-one degrees.', 'Tempering is a narrow window managed by feel: chocolate taken up and down the curve, seeded, and poured while the crystals still behave. The page is dark and glossy — batch percentages, mould counts, and one gilt line for a bar that bloomed in the case.', '#5f2911 #a8805f #c9992a #d4c4b2 #f2ece2 #160d06', 'Bodoni Moda', 'Hanken Grotesk', 'oil-slick', 'spotlight', 999, 'soft', 'gilding the batch that bloomed', 'Marguerite Chastain'),
  row('roastery', 'Roastery', 'Professional', 'coffee roasting profiles drums airflow', 'Coffee Shop|E-commerce|Manufacturing', 'First crack, *then listen.*', 'Bean profiles logged roast by roast.', 'Roasting is a conversation with a drum: charge temperature set, airflow trimmed, and a first crack you learn to hear through the noise. The design is burlap and smoke — roast curves, drop times, and one amber row for a profile that needs another try.', '#864727 #9c8a78 #c98a2a #d4c8b8 #f2ebe2 #180f08', 'Archivo Black', 'Public Sans', 'halftone-dots', 'dashboard', 4, 'flat', 'highlighting a profile to repeat', 'Tobias Lund'),
  row('preserve-kitchen', 'Preserve Kitchen', 'Organic', 'preserves jam pickles jars canning', 'Grocery|Restaurant|Marketplace', 'Sealed *while still hot.*', 'A kitchen that puts summer in glass.', 'Preserving is timing plus hygiene: fruit picked at its peak, jars sterilised, and a lid that pops on the bench when the seal is true. The page is labels and cooling racks — batch codes, sugar percentages, and one beet-red tick for a jar that failed.', '#801961 #bd9aa6 #bd8a2a #dcd0d6 #f8f0f4 #1c0d14', 'Caveat', 'Work Sans', 'tape-labels', 'catalog', 2, 'hairline', 'ticking the jars that did not seal', 'Elsie Fairweather'),
  row('pastry-kitchen', 'Pastry Kitchen', 'Luxury', 'pastry lamination croissants butter turns', 'Restaurant|Hotel|Coffee Shop', 'Folded, rested, *folded again.*', 'Lamination counted in turns, not minutes.', 'Pastry work is rest as much as effort: dough folded and chilled between turns, butter kept exactly as firm as the dough, and a bake that shows every layer. The design is butter and flour — turn counts, prove times, and one berry note for a batch overproofed.', '#c39054 #cdb89c #9c4260 #ded2c0 #f7f0e4 #1e1508', 'Gilda Display', 'Raleway', 'ribbon-band', 'split-scroll', 12, 'soft', 'noting a batch left to overproof', 'Colette Amara'),
  row('butcher-block', 'Butcher Block', 'Brutalism', 'butchery cuts counters carcass trim', 'Grocery|Restaurant|Marketplace', 'Cut to order, *wrapped in paper.*', 'A counter with a chalkboard and no secrets.', 'Butchery is a whole animal and a fixed list of cuts: primals broken down in order, trim kept back for sausages, and a case that empties by closing time. The design is steel and paper — cut names, hanging weights, and one blood-red slash on a cut sold out.', '#9b222e #a39595 #c99a2a #d3cbc7 #f2eeec #160b0d', 'Bebas Neue', 'Raleway', 'hard-shadows', 'full-bleed', 0, 'hard', 'slashing the cut that sold out', 'Gerard Ilunga'),
  row('spice-stall', 'Spice Stall', 'Maximalism', 'spices blends scoops sacks heat', 'Marketplace|Grocery|Restaurant', 'Weighed *by the scoop.*', 'Forty jars, one brass scale, no labels you can read.', 'Spice trading runs on the nose: blends mixed to a house memory, jars refilled from sacks, and a scoop that is never quite a standard measure. The design is loud and dusty — blend names, heat ratings, and one indigo band for a mix running low.', '#ef2506 #bd9c6f #7d2f8a #dcc9b2 #f8f0e0 #1e0f06', 'Bungee', 'Rubik', 'gradient-hero', 'mosaic', 8, 'flat', 'banding the blend that ran low', 'Amara Diop'),
  row('haberdasher', 'Haberdasher', 'Retro', 'haberdashery buttons ribbons notions zips', 'E-commerce|Fashion|Community', 'Buttons, ribbon, *and the odd zip.*', 'A shop of small things sold singly.', 'Haberdashery is retail at the scale of a card of hooks: drawers labelled in a hand nobody else can read, and a customer who needs exactly four buttons. The page is drawer-front — stock numbers, colour cards, and one mint tab on a notion to reorder.', '#c73d5a #bdaeae #2a7a6a #d6caca #f4eeee #1a0d10', 'DM Serif Display', 'Livvic', 'stitch-line', 'bento', 6, 'hairline', 'tabbing a notion to reorder', 'Posy Nakamura'),
  row('knit-mill', 'Knit Mill', 'Professional', 'knitting machines yarn cones gauge fabric', 'Manufacturing|Fashion|E-commerce', 'Twenty needles, *one yarn.*', 'Fabric knitted in the round, cone by cone.', 'Machine knitting is a pattern carried on punch cards: needles selected, yarn fed at tension, and a tube of cloth that either holds its gauge or does not. The design is industrial and violet — gauge swatches, cone counts, and one coral flag for a machine drifting.', '#6422be #a096bd #bf4a2a #cec8dc #f0eef7 #120e22', 'Unbounded', 'Karla', 'punched-card', 'dashboard', 2, 'flat', 'flagging a machine out of gauge', 'Marta Keskküla'),
  row('tannery', 'Tannery', 'Brutalism', 'tanning hides drums lime tannin leather', 'Manufacturing|Fashion|Automotive', 'Hides in, *leather out.*', 'The smelliest trade on the industrial estate.', 'Tanning is chemistry on a schedule: hides limed and dehaired, tanned in rotating drums, and finished to a surface a customer will judge by touch alone. The page admits the smell — drum rotations, tannin strengths, and one rust coat on the hide still soaking.', '#684126 #8d8880 #a8452a #c9c0b2 #eee7dc #180f06', 'Anton', 'Courier Prime', 'rivet-row', 'docs', 0, 'hard', 'coating the hide still in the drum', 'Grzegorz Nowak'),
  row('glover', 'Glover', 'Luxury', 'gloves leather panels cutting fitting', 'Fashion|E-commerce|Wedding', 'Five fingers, *one seam.*', 'Gloves cut from the best part of a hide.', 'Glove-making is cutting to the hand: a pattern of small panels, leather chosen for stretch, and a seam placed where it will not be felt. The design is hushed and dark — hand measures, leather grades, and one gold stitch for a pair still in fitting.', '#492749 #9c8f9c #bd832a #cdc2cd #f0ecf1 #130b14', 'Marcellus', 'Manrope', 'dashed-borders', 'editorial', 4, 'hairline', 'stitching a pair still in fitting', 'Marguerite Chastain'),
  row('locksmith', 'Locksmith', 'Professional', 'locks cylinders keyways entry pinning', 'Community|Real Estate|E-commerce', 'Open in *one attempt.*', 'Entry work, done on other people’s doors.', 'A locksmith is trusted with the wrong side of every door: cylinders tolerated, keyways recorded, and an emergency call that arrives at midnight. The design is brass and steel — keyway codes, pin heights, and one teal pin on a lock awaiting parts.', '#b8a32d #8f969a #2a6a7a #c9c6b8 #eeece1 #17150a', 'IBM Plex Mono', 'Outfit', 'blueprint-grid', 'docs', 2, 'flat', 'pinning the lock short of parts', 'Billy Hart'),
  row('chimney-sweep', 'Chimney Sweep', 'Retro', 'chimneys flues brushes soot sheets', 'Real Estate|Community|Construction', 'Brush up, *soot down.*', 'A trade still done with a brush and a sheet.', 'Sweeping is unglamorous and exact: flue brushed from above, sheets taped to keep a room clean, and a phone that rings hardest the week before winter. The page is soot and ember — flue diameters, sweep counts, and one orange glow on a chimney booked out.', '#494158 #8a827e #c96a1a #c9c2bc #eeeae6 #100e10', 'Abril Fatface', 'Source Sans 3', 'grain-overlay', 'poster', 4, 'hard', 'lighting the flue booked until spring', 'Frank Delaney'),
  row('squeegee-crew', 'Squeegee Crew', 'Playful', 'windows squeegees harnesses rise glass', 'Construction|Real Estate|Community', 'Six floors, *no streaks.*', 'High-rise windows, cleaned from the outside.', 'Window cleaning is rope work with a finish line: harness checked, glass scraped, and an edge that has to look invisible from the inside. The design is bright and breezy — floor counts, rinse passes, and one amber job tag on a pane left off the round.', '#13c1ec #a0c4cd #cf8a2a #c8dfe4 #eff8fa #0a161c', 'Righteous', 'Public Sans', 'diagonal-bars', 'hero-cards', 999, 'soft', 'tagging a pane still on the list', 'Loz Fisher'),
  row('appliance-repair', 'Appliance Repair', 'Professional', 'appliances faults parts washers diagnostics', 'Community|E-commerce|Real Estate', 'Fixed, *or no fee.*', 'White goods diagnosed at the kitchen table.', 'Appliance repair is diagnostics under a sink: a fault code read, a part ordered, and a customer deciding whether the machine is worth saving. The page is workmanlike — model numbers, fault codes, and one amber ticket for a job waiting on a part.', '#40588c #9399b2 #cf8a2a #c9ccd8 #eff1f7 #0e1220', 'Silkscreen', 'Space Grotesk', 'pcb-trace', 'receipt', 2, 'flat', 'ticketing a job waiting on a part', 'Ken Adjei'),
  row('paint-decorator', 'Paint & Paper', 'Creative', 'decorating painting wallpaper taping rooms', 'Real Estate|Hotel|Community', 'Two coats, *sharp edges.*', 'A decorating firm that tapes before it talks.', 'Decorating is preparation disguised as colour: surfaces filled, edges taped, and a finish judged in raking light. The page is swatch-book bright — colour cards, drying windows, and one terracotta line on a room still to be cut in.', '#27c479 #9cbdac #bf5530 #cadcd0 #f0f7f2 #0c1a12', 'Amatic SC', 'Lora', 'swiss-grid', 'asymmetric', 0, 'flat', 'lining the room still to cut in', 'Tilly Morgan'),
  row('slate-roof', 'Slate Roof', 'Brutalism', 'roofing slate courses lead flashing gutters', 'Construction|Real Estate|Architecture', 'Laid *from the gutter up.*', 'Roofs that outlast the people who pay for them.', 'Slating is a craft of overlap and fixings: courses set to a gauge, every slate nailed twice, and a lead flashing that has to move with the building. The design is weatherproof and grey — course counts, lap widths, and one copper strip on a roof awaiting scaffold.', '#585f88 #8d929c #bf5f2a #c6cad0 #edeff2 #101216', 'Rubik Mono One', 'Familjen Grotesk', 'double-rule', 'manifesto', 0, 'hard', 'stripping the roof still on hold', 'Callum Mackay'),
  row('salvage-yard', 'Salvage Yard', 'Maximalism', 'salvage reclaim doors ironwork lots', 'Construction|E-commerce|Art Gallery', 'Everything *gets a second life.*', 'A yard of doors, sinks and ironwork, sorted badly.', 'Architectural salvage is a market in things nobody made twice: a door priced by its hinges, a sink by its crack, and a buyer measuring a gap in a wall. The page is stacked and dusty — lot numbers, condition grades, and one gold tag on a piece already spoken for.', '#a14576 #a3938a #bd9a2a #d4c9c4 #f2edea #160c10', 'Monoton', 'Space Grotesk', 'torn-edge', 'mosaic', 4, 'inset', 'tagging the piece spoken for', 'Dex Harlow'),
  row('rowing-club', 'Rowing Club', 'Retro', 'rowing boats oars crews tideway eights', 'Sports|Community|Nonprofit', 'Eight oars, *one boat.*', 'A club that launches before the river traffic.', 'Rowing is timing sold as strength: a crew seated by weight, oars matched, and a stroke rate that only works if nobody rows alone. The page is river-blue and blade-red — boat allocations, tide times, and one red flag on a seat still open.', '#1638ca #8fa4b2 #bf3a2a #c6d2da #edf2f6 #0c1620', 'Playfair Display', 'Hanken Grotesk', 'wave-section', 'split-hero', 2, 'flat', 'flagging the seat nobody took', 'Eamon Doyle'),
  row('boxing-club', 'Boxing Club', 'Brutalism', 'boxing bags rounds corners wraps bouts', 'Sports|Community|Fitness', 'Wrap up, *then work.*', 'A gym of bags, bells and no mirrors.', 'A boxing gym runs on rounds: hands wrapped, bag work timed, and a corner that tells you the truth between bells. The design is taped and worn — round counts, bout cards, and one gold belt line for a fighter still on the undercard.', '#b84623 #968c84 #cf9a2a #d1c7bf #f2eeea #160d09', 'Rubik Doodle Shadow', 'Bitter', 'hard-shadows', 'spotlight', 0, 'hard', 'gilding the name on the undercard', 'Curtis Bowen'),
  row('climbing-wall', 'Climbing Wall', 'Playful', 'climbing bouldering holds grades routes', 'Sports|Fitness|Community', 'Read the route *before you pull.*', 'Plastic holds rearranged every Tuesday.', 'A climbing wall is a puzzle reset weekly: holds bolted to a colour, grades set by consensus, and a route that rewards silence before movement. The page is chalk and neon — route numbers, hold counts, and one jade tag on a problem awaiting its setter.', '#d01197 #cda0bd #2a8a72 #dcc8d6 #f7eff4 #1c0c18', 'Baloo 2', 'Figtree', 'isometric-lattice', 'bento', 8, 'soft', 'tagging the problem still unset', 'Charlie Ngata'),
  row('archery-range', 'Archery Range', 'Minimalism', 'archery bows draws targets rounds field', 'Sports|Education|Community', 'Breathe out, *then loose.*', 'A field, a line, and a very quiet coach.', 'Archery is a still sport: bow tuned to the archer, distance marked, and a shot that is over before the string stops buzzing. The design is measured and green — draw weights, round formats, and one gold ring on a target yet to be scored.', '#447e67 #9cb0a0 #bd7a2a #c8d4c9 #eef4ef #0f1912', 'Young Serif', 'Manrope', 'corner-brackets', 'centered', 1, 'hairline', 'ringing the target unscored', 'Gethin Price'),
  row('bowling-alley', 'Bowling Alley', 'Retro', 'bowling lanes pins leagues shoes averages', 'Sports|Events|Community', 'Oil, throw, *repeat.*', 'Thirty lanes and one machine that always jams.', 'League bowling is administration with a soundtrack: lanes oiled to a pattern, handicaps published, and a pin setter that decides how the evening goes. The page is retro neon — lane assignments, averages, and one amber light on a lane out of service.', '#b814a9 #bd9cac #c99a2a #dcccd4 #f7eff3 #180a14', 'Hi Melody', 'Rubik', 'stencil-mask', 'full-bleed', 20, 'glow', 'lighting the lane that is down', 'Nostalgia Engine'),
  row('cycle-clinic', 'Cycle Clinic', 'Professional', 'bicycles wheels spokes truing servicing', 'Community|E-commerce|Sports', 'Trued, tensioned, *out the door.*', 'A workshop where every repair gets a test ride.', 'Bicycle repair is a queue of small certainties: wheel trued, drivetrain cleaned, brakes set so they do not rub, and a test ride that finds what the stand could not. The page is a job board — work orders, spoke tensions, and one rust tag for a bike awaiting a hub.', '#258e5f #93b0a4 #bd4a2a #c6d6ce #eef5f1 #0c1a14', 'Bricolage Grotesque', 'Sora', 'numbered-steps', 'docs', 4, 'soft', 'tagging the bike waiting on a hub', 'Marek Dolny'),
  row('fire-station', 'Fire Station', 'Brutalism', 'engines turnout hydrants drills crews', 'Government|Community|Construction', 'Down the pole *in ninety seconds.*', 'A station timed from the alarm to the gate.', 'A fire station is readiness made routine: kit loaded on the engine, hydrants tested on a rota, and a turnout clock everybody pretends not to watch. The design is red and practical — appliance rolls, drill schedules, and one amber marker on a hydrant out of service.', '#db0d06 #a0938d #cf9a2a #d3cbc6 #f4f0ed #180c08', 'Archivo', 'Inter', 'diagonal-bars', 'dashboard', 0, 'hard', 'marking a hydrant out of service', 'Owen Pryce'),
  row('lifeguard-tower', 'Lifeguard Tower', 'Playful', 'lifeguards beaches flags patrols rips', 'Community|Travel|Sports', 'Eyes on the water, *always.*', 'A wooden tower with a flag system and a megaphone.', 'Lifeguarding is observation with a whistle: flags set for the swell, patrols timed to the tide, and a beach that changes its mind twice a day. The page is sun-faded — swell reports, flag states, and one blue note on a rip current logged.', '#d8bf64 #bdae8a #2a6a9c #dcd2b2 #f7f1dd #1c160a', 'Nunito', 'Figtree', 'sonar-sweep', 'split-hero', 8, 'flat', 'noting the rip current of the day', 'Sunny Marchetti'),
  row('mountain-rescue', 'Mountain Rescue', 'Professional', 'callouts crags stretchers teams weather', 'Community|Sports|Government', 'Called out *in any weather.*', 'Volunteers who leave warm rooms at midnight.', 'Mountain rescue is logistics in bad weather: a callout logged, a route chosen, and a stretcher carried over ground nobody would walk for fun. The design is high-contrast — callout numbers, grid references, and one alpine panel for a team still out on the hill.', '#2f3cc1 #a8a095 #2a5a8a #d1c9c0 #f3f0ec #17120c', 'Spectral', 'IBM Plex Sans', 'outline-type', 'field-notes', 2, 'soft', 'panelling the team still on the hill', 'Selin Aydın'),
  row('lost-and-found', 'Lost & Found', 'Creative', 'property umbrellas labels shelves claims', 'Community|Travel|Government', 'Someone *is missing you.*', 'A cupboard of forgotten things, patiently labelled.', 'Lost property is grief in miniature: an item bagged, described in neutral language, and shelved for a claimant who may never come. The page is orderly and wistful — shelf numbers, found dates, and one slate seal on an umbrella nobody claimed.', '#e08c48 #bdae9a #2f6a86 #d8cec2 #f7f1e9 #1c1208', 'Gaegu', 'Figtree', 'rotated-stickers', 'catalog', 12, 'soft', 'sealing the umbrella nobody claimed', 'Poppy Lang'),
  row('tram-depot', 'Tram Depot', 'Retro', 'trams depots shunting overhead inspection bays', 'Logistics|Government|Construction', 'Shunted, washed, *back at five.*', 'Sheds where trams sleep in rows.', 'A tram depot is a timetable made physical: vehicles shunted in order, inspection pits checked, and a morning departure that waits for nobody. The design is municipal and green — berth allocations, inspection notes, and one amber line on a tram stuck for a part.', '#31beb4 #9cb0ac #bd7a2a #c9d8d4 #eff5f3 #0f1c1a', 'VT323', 'Jost', 'tape-labels', 'timeline', 2, 'flat', 'lining the tram stuck for a part', 'Rhiannon Vale'),
  row('wash-bay', 'Wash Bay', 'Minimalism', 'valeting foam rinse bays dilution timings', 'Automotive|Community|E-commerce', 'Soap, rinse, *spot-free.*', 'Six minutes per car, timed on a board.', 'Valeting is repetition held to a standard: pre-rinse, foam, agitation where it actually matters, and a dry that decides whether the customer returns. The page is wet concrete and chrome — bay timings, chemical dilutions, and one amber tab on a bay out of soap.', '#2096e6 #a0c4d1 #cf8a2a #c8dee8 #eff7fa #0a161e', 'Inter', 'Inter', 'wave-section', 'centered', 6, 'glow', 'tabbing the bay that ran dry', 'Billy Hart'),
  row('projection-booth', 'Projection Booth', 'Creative', 'projection reels lamps screens screenings', 'Film & TV|Events|Community', 'Twenty-four frames, *every second.*', 'A small room above the audience, full of heat.', 'Projection is a performance nobody watches: reels checked, lamp aligned, and a screen that must not flicker while the room is silent. The design is amber and dust — reel schedules, lamp hours, and one gold marker on a screening almost full.', '#68352c #91847f #cf9a2a #cfc6c1 #f0ebe9 #140a0c', 'Cormorant Garamond', 'Inter', 'glow-pulse', 'film-strip', 0, 'hairline', 'marking the screening nearly full', 'Bea Solano'),
  row('foley-pit', 'Foley Pit', 'Creative', 'foley footsteps props cues gravel studio', 'Film & TV|Music|Podcast', 'Every footstep *is coconut.*', 'A pit of gravel, glass and broken crockery.', 'Foley is acting with objects: a walk recorded in sync with picture, a door slammed to taste, and a floor of debris kept for exactly one sound. The page is tactile and brown — cue sheets, prop inventories, and one slate-blue marker on a cue still to record.', '#ab7d35 #a39284 #426a8a #d4c9bc #f2ede5 #1a1007', 'Rubik Doodle Shadow', 'Poppins', 'wave-section', 'split-scroll', 12, 'glow', 'marking the cue still unrecorded', 'Marcy Kane'),
  row('costume-house', 'Costume House', 'Luxury', 'costumes wardrobe hire fittings periods', 'Film & TV|Wedding|E-commerce', 'Dressed *for any century.*', 'Racks arranged by decade and by disaster.', 'A costume house is a library of other people: garments tagged by period, alterations pinned, and a fitting that has to survive a shooting schedule. The design is velvet and gilt — rail numbers, period notes, and one gold ticket on a costume out on hire.', '#893a92 #a894b2 #bd832a #d5c9d9 #f3eef5 #170c1c', 'Mrs Saint Delafield', 'Spectral', 'quilt-patch', 'mosaic', 4, 'soft', 'ticketing a costume still on hire', 'Imogen Blake'),
  row('canteen-line', 'Canteen Line', 'Retro', 'canteens trays menus service portions puddings', 'Education|Community|Restaurant', 'Tray, plate, *pudding.*', 'Lunch served to four hundred in twenty minutes.', 'A canteen is throughput with manners: a menu planned a week ahead, a line that has to keep moving, and a pudding that decides how the afternoon goes. The page is tray-coloured — service times, portion counts, and one teal tab on a dish that ran out early.', '#e3a24f #bdae94 #2a7a6a #dcd0b8 #f7f0e2 #1c150a', 'Cabin', 'Karla', 'underline-accent', 'timeline', 4, 'flat', 'tabbing the dish that ran out', 'Dee Ramírez'),
  row('allotment-assoc', 'Allotment Association', 'Organic', 'allotments plots sheds rota rents water', 'Community|Agriculture|Nonprofit', 'Plot forty-two, *runner beans.*', 'Thirty plots, one water butt, endless minutes.', 'An allotment association is governance at the size of a shed: rents collected, a waiting list kept, and a rota for the water that nobody enjoys. The page is greenhouse-green — plot numbers, rent states, and one terracotta tag on a plot gone to seed.', '#74b927 #a0b08d #bd5a2a #ccd9c0 #eff5e8 #101a0a', 'Lora', 'Source Sans 3', 'leaf-divider', 'field-notes', 6, 'flat', 'tagging the plot gone to seed', 'Gethin Price'),
  row('wool-store', 'Wool Store', 'Organic', 'wool fleece grading bales lots crimp', 'Agriculture|Manufacturing|Marketplace', 'Graded, baled, *and weighed.*', 'Fleece sorted by hand before it becomes anything.', 'Wool handling is appraisal at speed: fleece thrown on a table, graded by crimp and colour, and packed into bales that will travel further than the sheep ever did. The design is hessian and fleece — grade codes, bale weights, and one indigo band on a lot still unsold.', '#a7a081 #a8a294 #3f5a80 #d4cfc4 #f2efe9 #17150d', 'Bitter', 'Poppins', 'stitch-line', 'asymmetric', 2, 'soft', 'banding the lot still unsold', 'Siobhán Walsh'),
  // __W18__
]
