import type { DesignSystem } from '../types'
import { row } from './build'

/**
 * Wave 15 — Weather, Water and Wild: the systems that read the sky, the
 * tide, and the soil, plus the trades that work outdoors.
 * Row format: id, name, category, tags, useCases, hero, description,
 * philosophy, colors, display, body, motif, layout, radius, depth,
 * accentRole, author.
 */

export const wave15Designs: DesignSystem[] = [
  row('tide-table', 'Tide Table', 'Minimalism', 'tides predictions tables heights', 'Government|Travel|Energy', 'High water *at 04:12.*', 'Predictions for anyone whose day depends on the water.', 'A tide table is a document about the future: heights at fixed times, springs and neaps, and a margin for weather that the table cannot know. The system is deliberately plain — a list of times, a curve, and one accent for the moment the water turns.', '#527f93 #a8c3d1 #e07a5f #d8e4ea #f4f9fb #0d2029', 'Silkscreen', 'Outfit', 'slat-shadow', 'timeline', 2, 'flat', 'windows shorter than forecast', 'Owen Pryce'),
  row('rain-gauge', 'Rain Gauge', 'Minimalism', 'rainfall gauges network records', 'Government|Agriculture|Data & Analytics', 'Every millimetre *is somebody’s job.*', 'A gauge network that reports by radio.', 'A rain gauge is a boring instrument with an interesting job: a funnel, a tipping bucket, and a message sent every fifteen minutes so a catchment can be warned. The design is instruments first — one reading per site, and a total nobody is allowed to round.', '#394386 #9fb2c0 #f0a500 #dbe3e9 #f5f8fa #101d26', 'Karla', 'Sora', 'big-stat-row', 'docs', 6, 'flat', 'gauges silent past an hour, one site each', 'Imogen Blake'),
  row('snow-science', 'Snow Science', 'Minimalism', 'snowpack avalanche crystal pits', 'Education|Energy|Sports', 'Read the layers, *then the slope.*', 'Snowpack studies that decide where people may go.', 'Snow science is a pit dug in the cold: layers, grain shape, a stability test, and a judgment that other people depend on. The design is quiet and exact — white space, crystal diagrams, and one violet reserved for the layer that will not hold.', '#8577bb #c2c8e0 #22d3ee #e2e5f0 #f7f8fc #141a2e', 'Inter', 'Lora', 'outline-type', 'field-notes', 4, 'hairline', 'layers failing the test, one pit each', 'Cornelius Pike'),
  row('ferry-timetable', 'Ferry Timetable', 'Minimalism', 'ferry sailings crossings islands', 'Travel|Logistics|Booking', 'The boat leaves *whether you are on it.*', 'Island sailings that depend on the weather.', 'A ferry timetable is a promise with a caveat: sailings are hourly in summer, the last one is final, and a swell will change everything. The design is a departure board — big times, small print about cars, and a single colour for a cancelled crossing.', '#1f3ca3 #8fa6bd #ffb020 #d5dfe9 #f1f6fa #0a1723', 'Livvic', 'Red Hat Display', 'ledger-rules', 'receipt', 0, 'flat', 'sailings at risk, one crossing each', 'Halvard Ness'),
  row('harvest-fair', 'Harvest Fair', 'Maximalism', 'fair harvest produce prizes tents', 'Events|Community|Agriculture', 'Best in show, *then best in tent.*', 'An autumn fair that fills a field for a day.', 'A harvest fair is a village measuring itself: jams judged, rosettes pinned, and a produce tent that smells of apples and competition. The design is cheerful clutter — stickers at angles, bunting colours, and category cards a volunteer can fill in by hand.', '#a22706 #e8b06a #2f7a4f #f2ddc2 #fdf4e8 #2a1a0e', 'Rye', 'Zilla Slab', 'rotated-stickers', 'mosaic', 12, 'hard', 'classes short of entries, one stall each', 'Rosa Delgado'),
  row('corn-maze', 'Corn Maze', 'Playful', 'maze corn paths map autumn', 'Events|Kids|Travel', 'Three miles *of dead ends.*', 'A maze cut into a field every September.', 'A corn maze is cartography as entertainment: numbered posts, a map that lies a little, and staff who can see the whole field from a tower. The design is friendly wayfinding — path lines, checkpoint stamps, and a sun-faded yellow that reads in daylight.', '#d1d147 #e8d18a #e07a3a #f0e6c8 #fdf9ec #2a220e', 'Bangers', 'Mulish', 'wave-section', 'full-bleed', 999, 'hard', 'posts needing a re-stamp, one path each', 'Posy Nakamura'),
  row('pumpkin-patch', 'Pumpkin Patch', 'Playful', 'pumpkins patch harvest weigh', 'Grocery|Kids|Events', 'Weighed, *then carved.*', 'A pick-your-own patch that weighs at the gate.', 'A pumpkin patch is retail that happens in a field: wheelbarrows, a scale at the gate, and a family argument about which one is best. The design is bright and simple — sizes by weight, a map of rows, and one green for the ones still growing.', '#ca6402 #e8a56b #4d7c0f #f0dcc8 #fdf6ee #2a1a10', 'Permanent Marker', 'Fredoka', 'quilt-patch', 'hero-cards', 8, 'hard', 'rows picked out early, one field each', 'Marcy Kane'),
  row('wellington-boots', 'Wellington Boots', 'Playful', 'boots rain wellington puddles', 'Fashion|Kids|E-commerce', 'Built for puddles, *sized for growing.*', 'Rubber boots for weather that means it.', 'Wellies are a product with one job and a long tradition of failing at it: seams split, grips wear, and children grow out of them in a season. The design is practical and cheerful — size charts, tread patterns, and a colour palette that survives mud.', '#27682c #a8c7b0 #e8c04b #dfe9e1 #f6faf7 #142019', 'Nunito', 'Quicksand', 'soft-shadows', 'bento', 24, 'soft', 'sizes low in stock, one boot each', 'Elsie Fairweather'),
  row('scarecrow-rows', 'Scarecrow Rows', 'Playful', 'scarecrows fields birds crops', 'Agriculture|Kids|Community', 'Dressed to *frighten birds.*', 'A village competition for the best scarecrow.', 'Scarecrows are folk art with a job description, and a village competition turns them into a gallery along a footpath. The design is homemade — stitched labels, straw yellows, and an entry form that asks for the story as well as the name.', '#c1bc71 #d9c69a #c2410c #e8e0cc #faf6ec #2b2415', 'Rubik Doodle Shadow', 'Gaegu', 'dashed-borders', 'catalog', 4, 'hard', 'entries without a story attached', 'Wren Baker'),
  row('flood-barrier', 'Flood Barrier', 'Brutalism', 'barrier flood surge gates river', 'Government|Construction|Insurance', 'Closed *before the surge arrives.*', 'A movable barrier that sleeps until it is needed.', 'A flood barrier spends almost all of its life open, and the whole design question is what happens in the four hours before it closes. The system is operational and unsentimental — gate states, clearance times, and a chart of the tide it is arguing with.', '#6f85b9 #9aa9bb #e8b02b #1b2836 #101a24 #e2ebf2', 'Archivo Black', 'Red Hat Display', 'diagonal-bars', 'asymmetric', 0, 'hairline', 'gates behind schedule, one span each', 'Gerard Ilunga'),
  row('quarry-bench', 'Quarry Bench', 'Brutalism', 'quarry stone blasting benches', 'Construction|Manufacturing|Energy', 'Blast at *two, load by four.*', 'A quarry run on benches and blasts.', 'A quarry is a hole measured in benches: drill patterns, blast windows, and a haul road that has to stay passable in the wet. The design is stone and schedule — face heights, tonnage out, and one red for the blast horn nobody may miss.', '#64556d #a8a8a2 #c2410c #2b2b2e #17171a #e6e4e8', 'Anton', 'Zilla Slab', 'hard-shadows', 'poster', 0, 'hard', 'benches behind tonnage, one face each', 'Marek Dolny'),
  row('dry-stone-wall', 'Dry Stone Wall', 'Brutalism', 'wall stone dry courses mend', 'Construction|Agriculture|Nonprofit', 'No mortar, *no shortcuts.*', 'Walls built to stand for a century without cement.', 'Dry stone walling is structural patience: stones chosen by shape, courses laid so each one bears on the next, and a gap at the base that lets water through. The design is stony and calm — course diagrams, a repair log, and one green for gaps that need mending.', '#aca356 #c4bfae #4d7c0f #e2ded2 #f6f4ec #26241c', 'Oswald', 'Raleway', 'lattice-weave', 'docs', 0, 'hard', 'gaps open past a season, one course each', 'Gethin Price'),
  row('storm-drain', 'Storm Drain', 'Brutalism', 'drainage culverts catchments storm', 'Government|Construction|Real Estate', 'Everything runs *downhill eventually.*', 'A drainage network nobody sees until it rains.', 'A storm drain is a hidden hierarchy: gullies feed culverts, culverts feed the river, and one blocked grate can flood a street three blocks away. The design leans dark and schematic — catchment maps, capacity figures, and a yellow reserved for a drain at its limit.', '#8aa2a8 #7f96a5 #f2c400 #16242c #0b141b #dbe6ee', 'Bebas Neue', 'Oxanium', 'blueprint-grid', 'map-plate', 0, 'inset', 'culverts at capacity, one catchment each', 'Gerard Ilunga'),
  row('river-lock', 'River Lock', 'Brutalism', 'canal lock gates levels narrowboat', 'Travel|Government|Logistics', 'Two gates, *one water level.*', 'A canal lock that lifts boats by hand.', 'A lock is a chamber of water with a schedule: gates swung, paddles opened slowly, and a boat raised the height of a house in twenty minutes. The design is Victorian engineering kept alive — gate numbers, level gauges, and a queue that respects the water.', '#66b29b #8fb5b0 #c2410c #d6e5e3 #f2f9f8 #0d1f1f', 'Unbounded', 'Familjen Grotesk', 'numbered-steps', 'split-scroll', 4, 'flat', 'locks behind schedule, one chamber each', 'Rowan Ellis'),
  row('sea-salt', 'Sea Salt', 'Luxury', 'salt pans evaporation flakes harvest', 'Grocery|Restaurant|Manufacturing', 'Sun, wind, *and patience.*', 'Salt pans worked by hand and weather.', 'Sea salt is a harvest you cannot hurry: seawater in, sun and wind out, and a fleur de sel that only forms when the day is exactly right. The design is pale and mineral — crystal textures, harvest dates, and gold used as sparingly as the flakes themselves.', '#93a3c8 #c8d8e2 #d4af37 #e6edf1 #f8fbfc #16242c', 'Gilda Display', 'Marcellus', 'stamp-seal', 'catalog', 2, 'soft', 'pans ready to rake, one bed each', 'Marguerite Chastain'),
  row('vineyard-terrace', 'Vineyard Terrace', 'Luxury', 'vineyard terraces vintage harvest', 'Restaurant|Agriculture|Hotel', 'The slope makes *the wine.*', 'Terraced vines worked by hand.', 'Vineyards are geology with a harvest date: aspect, drainage, and a pick decided by sugar and rain. The design is a tasting note — deep wine reds, parcel names, and vintage cards that read like a cellar book rather than a product page.', '#662c31 #b08a94 #d4af37 #ecd8dd #fbf4f6 #25101a', 'Cormorant Garamond', 'Spectral', 'serif-italic-hero', 'editorial', 4, 'soft', 'parcels picked late, one terrace each', 'Étienne Rocher'),
  row('sugar-bush', 'Sugar Bush', 'Luxury', 'maple syrup tapping boil sap', 'Grocery|Travel|Manufacturing', 'Forty litres in, *one litre out.*', 'A sugar bush that boils sap all spring.', 'Sugaring is a short season with long days: taps set when nights freeze, sap collected before it sours, and an evaporator that runs until the syrup sheets off a spoon. The design is steam and amber — batch numbers, sugar content, and a boil log kept by the door.', '#75551a #cfa87f #f0c04b #ece0d0 #fdf8f0 #241a10', 'Gloock', 'Poppins', 'paper-cut', 'split-hero', 12, 'soft', 'batches below grade, one boil each', 'Nadia Ferraro'),
  row('seed-library', 'Seed Library', 'Luxury', 'seeds library varieties heritage', 'Agriculture|Education|Nonprofit', 'Lent out, *grown, returned.*', 'A lending library for seeds.', 'A seed library is a small institution with a long horizon: varieties catalogued, packets lent, and a rule that whatever grows must come back. The design is archival and green — accession numbers, germination rates, and one gold for the varieties that cannot be replaced.', '#407869 #9ec4ae #d4af37 #d9e8df #f3faf6 #0c1f16', 'Lora', 'Hanken Grotesk', 'watermark-glyph', 'docs', 2, 'hairline', 'varieties overdue for return', 'Amara Diop'),
  row('fog-station', 'Fog Station', 'Retro', 'foghorn signal coast ships', 'Travel|Government|Energy', 'Heard *long before seen.*', 'A fog station that still tests its horn.', 'A fog signal is a sound designed for the worst visibility: a compressed-air horn, a schedule of blasts, and a log of every test. The design is grey and mechanical — blast patterns, hearing checks, and one orange for the switch that starts the compressor.', '#5a679c #9aa8b0 #e07a3a #dbe2e6 #f4f7f8 #161f24', 'Silkscreen', 'Courier Prime', 'scanlines', 'centered', 2, 'glow', 'horns overdue for a test', 'Billy Hart'),
  row('thatch-line', 'Thatch Line', 'Retro', 'thatch roofing straw ridge reed', 'Construction|Real Estate|Travel', 'Cut, combed, *laid thick.*', 'Roofers who still work in straw.', 'Thatching is a craft measured in decades: reed cut in winter, laid in courses, and a ridge that has to shed water for thirty years. The design is warm and textured — bundle counts, ridge details, and one green for the reeds still curing.', '#ad8f23 #c8ab7a #4d7c0f #e8dfcc #faf5ea #241c0f', 'Caveat', 'Zilla Slab', 'torn-edge', 'manifesto', 6, 'soft', 'roofs awaiting a ridge, one cottage each', 'Gethin Price'),
  row('harness-room', 'Harness Room', 'Retro', 'leather harness saddlery tack', 'Agriculture|Sports|Marketplace', 'Repaired, *not replaced.*', 'A saddler who keeps working tack alive.', 'A harness room smells of oil and leather: stitching awls, brass fittings, and a bridle repaired for the third time because it still fits. The design is a workbench ledger — hide grades, stitch counts, and a stamp for anything that has been back twice.', '#bc7864 #b08f70 #c9971b #33241a #1d130c #f0e4d4', 'Rye', 'Marcellus', 'stitch-line', 'editorial', 8, 'hard', 'tack out for repair, one item each', 'Cornelius Pike'),
  row('cider-press', 'Cider Press', 'Retro', 'cider apples press orchard barrels', 'Grocery|Restaurant|Manufacturing', 'Pressed in October, *drunk in June.*', 'An orchard press that runs by the crate.', 'Cider is a harvest with a calendar: apples milled, pomace pressed, and juice left to argue with yeast for months. The design is rustic and specific — blend ratios, tannin notes, and barrel numbers that only the cellar understands.', '#a8733b #d9ab74 #7a1f38 #f0e0c8 #fdf7ec #26170c', 'Bangers', 'Poppins', 'grain-overlay', 'bento', 12, 'soft', 'barrels still fermenting, one press each', 'Rowan Ellis'),
  row('apiary-log', 'Apiary Log', 'Organic', 'bees hives honey swarm queens', 'Agriculture|Grocery|Education', 'Counted by *the frame.*', 'Hive records for a keeper with forty boxes.', 'Beekeeping is bookkeeping with wings: brood counts, queen ages, and a swarm that happens the one week you are away. The design is honey-warm and methodical — hive numbers, inspection dates, and one green marking a colony that is thriving.', '#d38305 #e8cf8a #4d7c0f #f0e6c8 #fdf9ee #2a220c', 'Literata', 'Cabin', 'pill-nav', 'mosaic', 999, 'soft', 'hives overdue an inspection', 'Siobhán Walsh'),
  row('seaweed-farm', 'Seaweed Farm', 'Organic', 'kelp lines harvest ocean ropes', 'Agriculture|Energy|Grocery', 'Grown on ropes, *cut at low tide.*', 'Kelp lines worked from a small boat.', 'Seaweed farming is agriculture with no soil: seeded lines, a crop that grows in winter, and a harvest lifted before it breaks free. The design is tidal and practical — line numbers, wet weights, and a map of the bay the farm shares with everyone else.', '#267d24 #8fb3a0 #c2410c #d9e6df #f3f9f6 #0d1f18', 'Spectral', 'Cabin', 'wave-section', 'map-plate', 8, 'soft', 'lines ready to cut, one stretch each', 'Amara Diop'),
  row('peat-bog', 'Peat Bog', 'Organic', 'peat bog restoration sphagnum', 'Nonprofit|Energy|Government', 'Wet again, *slowly.*', 'Bog restoration measured in millimetres.', 'A peat bog grows a millimetre a year and holds more carbon than a forest, which makes restoration an exercise in patience. The design is dark and damp — water tables, sphagnum counts, and one amber for the areas still draining.', '#b28a80 #8a755a #d97706 #2a1d16 #170f0a #e8dcd0', 'Inter', 'Space Grotesk', 'vignette', 'field-notes', 2, 'soft', 'sites still draining, one plot each', 'Imogen Blake'),
  row('tree-nursery', 'Tree Nursery', 'Organic', 'seedlings nursery planting forests', 'Agriculture|Nonprofit|Government', 'Planted by the *thousand.*', 'A nursery growing the next woodland.', 'A tree nursery is a long bet: seed collected locally, seedlings graded, and a planting season that lasts six weeks. The design is green and optimistic — bed numbers, provenance notes, and a count of trees that made it through their first summer.', '#22d35d #a8c4a0 #d97706 #dde8d8 #f5faf2 #111f0e', 'Petrona', 'Cabin', 'leaf-divider', 'catalog', 12, 'soft', 'beds ready to lift, one species each', 'Amara Diop'),
  row('greenhouse-rows', 'Greenhouse Rows', 'Organic', 'glasshouse tomatoes rows vents', 'Agriculture|Grocery|Energy', 'Picked warm *off the vine.*', 'A glasshouse that runs on weather and vents.', 'A greenhouse is climate as a daily job: vents opened by temperature, water by need, and a crop that ripens in sequence down the row. The design is glass-bright and precise — row numbers, humidity, and one tomato red for what is ready today.', '#4f8b65 #a4c4b0 #e2543a #dce9e2 #f4faf7 #0e1f18', 'Source Sans 3', 'Mulish', 'swiss-grid', 'bento', 2, 'flat', 'rows ready for picking, one house each', 'Siobhán Walsh'),
  row('hop-yard', 'Hop Yard', 'Organic', 'hops vines harvest poles kiln', 'Agriculture|Manufacturing|Restaurant', 'Twelve metres *and climbing.*', 'Hop gardens cut and dried in September.', 'Hops are a crop with an architecture: poles, strings, and bines trained upward until they are cut down in a single week. The design is tall and ordered — row counts, variety blocks, and one amber for the kiln that has to run all night.', '#38ac23 #b3c48a #c2410c #e4e8d0 #f7f9ee #1e2210', 'Fraunces', 'Public Sans', 'isometric-lattice', 'mosaic', 4, 'hard', 'varieties ready to cut, one block each', 'Rowan Ellis'),
  row('weather-station', 'Weather Station', 'Professional', 'instruments readings forecast station', 'Government|Data & Analytics|Energy', 'Readings out *every hour.*', 'An instrument site that reports on the hour.', 'A weather station is a small site with strict rules: instruments sited away from buildings, readings taken at fixed minutes, and a log that must survive scrutiny. The design is dark and numeric — tabular figures, sensor states, and one amber for an instrument that has stopped reporting.', '#334fac #8fa8bd #f2b705 #1b2536 #0e1622 #dce5f0', 'IBM Plex Sans', 'Zilla Slab', 'big-stat-row', 'dashboard', 4, 'hairline', 'sensors offline, one instrument each', 'Halvard Ness'),
  row('coastguard-watch', 'Coastguard Watch', 'Professional', 'coastguard rescue watch cliffs', 'Government|Health|Travel', 'Watching *so nobody has to.*', 'A cliff-top station that answers maydays.', 'A coastguard watch is hours of nothing followed by four minutes of everything: binoculars, a radio log, and a decision about which lifeboat launches. The design is high-contrast and immediate — huge status, minimal chrome, and one red reserved for a live call.', '#b60802 #e8b06a #1f5f8a #f0dcc4 #fdf5ea #2a1408', 'Manrope', 'Zilla Slab', 'corner-brackets', 'dashboard', 0, 'hard', 'watches short of cover, one station each', 'Elsie Fairweather'),
  row('avalanche-desk', 'Avalanche Desk', 'Professional', 'avalanche forecast snow slopes bulletins', 'Government|Sports|Energy', 'Published *before the lifts open.*', 'A morning bulletin that closes slopes.', 'An avalanche desk publishes a hazard level before anyone boards a lift: snow profiles, wind loading, and a rating that has to be right more often than it is wrong. The design is a bulletin — five levels, one accent on the level of the day, and no hedging in the type.', '#6181db #9aa8c4 #e07a5f #1d2438 #0e1322 #e4e9f5', 'Chakra Petch', 'Hanken Grotesk', 'sonar-sweep', 'dashboard', 0, 'hairline', 'slopes above the day’s rating', 'Marta Keskküla'),
  row('forest-fire-watch', 'Forest Fire Watch', 'Professional', 'wildfire lookout towers detection smoke', 'Government|Energy|Nonprofit', 'Spotted *before it spreads.*', 'Lookout towers that watch the horizon all summer.', 'A fire lookout is a job of scanning: bearings taken on a smoke column, a radio call, and a position reported in degrees from a tower. The design is hot and urgent — bearing dials, dryness codes, and one glow reserved for a column that has not been identified.', '#cf574a #e0a878 #4d7c0f #3a2418 #22150d #f5e6d8', 'Oxanium', 'Courier Prime', 'glow-pulse', 'map-plate', 4, 'glow', 'sightings awaiting identification, one bearing each', 'Tomás Reyes'),
  row('glacier-survey', 'Glacier Survey', 'Professional', 'glacier ice mass balance survey', 'Energy|Government|Data & Analytics', 'Measured *in metres lost.*', 'Ice surveys with stakes and satellites.', 'Glacier surveying is subtraction at scale: stakes drilled, ablation measured, and a mass balance that nobody wants to publish. The design is cold and honest — annual deltas, a retreat timeline, and one warm colour for the number that keeps getting worse.', '#2fc3c8 #a8cdd8 #e07a5f #dcebf0 #f4fbfd #0c1f26', 'Space Mono', 'Public Sans', 'pixel-grid', 'field-notes', 0, 'flat', 'stakes not yet re-read, one transect each', 'Marta Keskküla'),
  row('herbarium-sheet', 'Herbarium Sheet', 'Creative', 'botanical specimens pressed labels', 'Education|University|Art Gallery', 'Pressed, *labelled, filed.*', 'Specimens archived on archival paper.', 'A herbarium sheet is a plant turned into a document: pressed flat, mounted, and labelled with a place and a date that outlive the collector. The design is paper-first — a specimen plate, a typed label block, and one deep red for the accession stamp.', '#655d36 #b3a882 #7a1f38 #e6dfc8 #faf7ec #221c0d', 'EB Garamond', 'Marcellus', 'editorial-columns', 'field-notes', 0, 'hairline', 'specimens awaiting mounting, one sheet each', 'Tobias Lund'),
  row('plankton-net', 'Plankton Net', 'Creative', 'plankton sampling microscope water', 'Education|Nonprofit|Data & Analytics', 'A litre of sea *is a census.*', 'Sampling that finds a food web in a bucket.', 'Plankton sampling is microscopy as routine: a net hauled, a sample fixed, and a count that underpins every fishery model. The design is aquatic and odd — translucent greens, cell outlines, and one gold for a bloom that is out of the ordinary.', '#7fbdbd #9fc4c0 #d4af37 #0f3b3b #08211f #dcf5f0', 'Sora', 'Raleway', 'moire-rings', 'catalog', 999, 'glow', 'blooms above the seasonal norm', 'Dr. Amara Osei'),
  row('bird-atlas', 'Bird Atlas', 'Creative', 'birds atlas surveys distribution records', 'Education|Nonprofit|Photography', 'Ten years, *one square at a time.*', 'A breeding atlas built by volunteers.', 'An atlas is a survey with a fixed grid: squares walked, birds recorded, and a distribution map assembled from thousands of notebooks. The design is cartographic and patient — grid references, evidence codes, and one orange for a square that changed.', '#504e80 #9aa8c4 #c2410c #d9e0ec #f4f7fc #0d1524', 'Be Vietnam Pro', 'Lora', 'numbered-steps', 'map-plate', 0, 'flat', 'squares without a recent visit', 'Wren Baker'),
  row('soil-charts', 'Soil Charts', 'Creative', 'soil profiles texture drainage', 'Agriculture|Education|Real Estate', 'Dig a pit, *read the layers.*', 'Soil survey data for anyone who plants anything.', 'A soil survey is a drawing of what lies under a field: horizons, texture, drainage class, and a boundary that decides what can be built. The design is earthy and technical — profile charts, pH bands, and one green for the classes that drain well.', '#5d3930 #a89478 #4d7c0f #e0d6c4 #f6f1e6 #1c150c', 'Archivo', 'Cabin', 'swiss-grid', 'docs', 4, 'flat', 'fields without a recent survey', 'Imogen Blake'),
  row('monsoon-desk', 'Monsoon Desk', 'Maximalism', 'monsoon rainfall forecast deluge', 'Government|Agriculture|News', 'Six weeks of rain, *in three days.*', 'Seasonal forecasting for a country that waits for rain.', 'A monsoon desk tracks a system that decides a harvest: onset dates, spell lengths, and a distribution nobody controls. The design is heavy weather — saturated indigo, cyan for water on the move, and statistics presented the way a bulletin board demands.', '#7b52c3 #9a90bd #22d3ee #251f45 #151130 #e8e4fb', 'Syne', 'Zilla Slab', 'gradient-hero', 'dashboard', 8, 'glow', 'districts past their onset date', 'Mei-Lin Tan'),
  row('salt-marsh', 'Salt Marsh', 'Organic', 'saltmarsh estuary reeds habitats', 'Nonprofit|Energy|Government', 'Half land, *half tide.*', 'Estuary habitat that absorbs the storm.', 'A salt marsh is coastal defence that grows itself: cordgrass, creeks, and a budget that treats flooding as a design brief. The design is green and tidal — habitat zones, creek surveys, and one gold for the marsh that is accreting rather than eroding.', '#4e9c6d #a8c4b3 #d9a441 #dce8e0 #f4faf6 #10201a', 'Newsreader', 'Figtree', 'leaf-divider', 'field-notes', 8, 'soft', 'creeks closed to access, one marsh each', 'Amara Diop'),
  row('wind-rose', 'Wind Rose', 'Minimalism', 'wind direction speeds rose data', 'Energy|Data & Analytics|Construction', 'Which way *the wind comes from.*', 'A century of wind records in one diagram.', 'A wind rose is a data graphic that people actually use: direction, frequency, and speed, drawn as petals so a turbine or a runway can be placed. The design is diagram first — thin strokes, one accent on the prevailing arm, and nothing that competes with the drawing.', '#15264f #93a8bb #e07a3a #d8e1e8 #f3f7fa #0d1a24', 'Jost', 'Cabin', 'ticker-marquee', 'poster', 2, 'hairline', 'directions above design limits', 'Owen Pryce'),
  // __W15__
]
